### ISSUE TITLE
INFO: sisl will be Python 3 "only" from 2019

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#101]
The sisl toolbox will be Py3 *only* from 2019.

This is to follow the development of the scientific community which already establishes this relation ship with Py3: https://python3statement.org/

From 2019, sisl will be Python >=3.6 only. Just before switching I will release a Py2 compatible version which will be the last one to enable Py2.

This should release some code. 

- [x] remove need for 'six'
- [x] remove metaclass workaround 
- [ ] add type annotations where applicable
- [x] remove `object` inheritance
- [x] remove py 2.7 from test suite
- [x] remove all `_zip`/`izip` usages (and similar for other)
- [ ] merge #114 to accommodate `pathlib`

**Comment by zerothi** [comment]
numpy and scipy will only support 3.6 and beyond, so I will too.

**Comment by pfebrer96** [comment]
Does this mean we can use f strings ? :)

**Comment by zerothi** [comment]
@pfebrer96 indeed it does! ;) please rebase your branch rather than merge! ;)
