### ISSUE TITLE
.density, .wavefunction should fail if not 0 < fxyz < 1

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#102]
**Describe the issue**
Calculating the wavefunction for a grid with geometries having intrinsic coordinates outside the unit-cell box should fail.

This is because it isn't supported due to reasons dealing with "supercell" interactions.

**Comment by pfebrer** [comment]
I'm encountering this problem myself. I think at least a warning should be issued, because I was hitting my head against the wall trying to figure out why some part of my wavefunction was missing :)
