### ISSUE TITLE
Installation requires: pyparsing>=1.5.7

### ISSUE THREAD

**Issue by juijan** [zerothi/sisl#121]
While installing sisl I noticed that sisl requires pyparsing version 1.5.7. or higher.

I would like to suggest adding this to the requirements.

``unit.base.py`` uses the method ``infixNotation`` which seems to be present only present in version 1.5.7 or higher.

Expert from pyparsing CHANGES.txt:
```
Version 1.5.7 - November, 2012
-----------------------------
...
- 'operatorPrecedence' is being renamed 'infixNotation' as a better
  description of what this helper function creates. 'operatorPrecedence'
  is deprecated, and will be dropped entirely in a future release.
```

**Comment by zerothi** [comment]
Thanks for reporting this! Should be fixed now! :)
