### ISSUE TITLE
time  reversal averaged hamiltonian

### ISSUE THREAD

**Issue by oroszl** [zerothi/sisl#125]
**Describe the feature**
Some times it can happen that a DFT calculation in SIESTA violates time reversal symmetry a bit (on the order of a fraction of a meV) spontaneously if a calculation was not performed with enough k-points or Mesh cutoff for calculations involving spin-orbit coupling.
In these cases, it would  be beneficial (for example when calculating the TRI topological invariant)
if a time reversal symmetrized Hamiltonian would be available for post-processing purposes. 

my suggestion would be to write a method that yields 
$H_{TRI}=[H(k)+(is_y) (H(-k)^*) (-is_y)]/2$ 
this guarantees degeneracy of the spectrum in time reversal invariant momenta.

**Comment by oroszl** [comment]
something along this line:
```python
dh=sisl.get_sile('my.fdf').read_hamiltonian()

def trHk(k,dh):
    Hk=dh.Hk(k=k)
    Hmk=conj(dh.Hk(k=(-k[0],-k[1],-k[2])))
    isy=array([[0,1],[-1,0]])
    iSy=korn(ss.eye(dh.no),isy)
    return (Hk-iSy@Hmk@iSy)/2
    
```

**Comment by zerothi** [comment]
This is a good idea. I think the best way to do this is to implement this in the `Hamiltonian.transpose` function. Simply because this allows one to ensure transpositions.

I'll have time next week to look into this.

**Comment by zerothi** [comment]
I am trying to generalize this, could you provide a TSHS file which has this TRS problem?

**Comment by oroszl** [comment]
What do you mean by TSHS? 
Take any system with strong spin-orbit coupling and check the spectrum at the gamma point.
All levels should be doubly degenerate.

**Comment by oroszl** [comment]
I can look for my runs and post it somewhere. Is that what you require?

**Comment by zerothi** [comment]
Ah, sorry, I need the Hamiltonian to have something to check against ;)

Yes, any thing you have would be nice for me to use (I am no spin-orbit expert, so something you know has difficulties would be nice) :)

**Comment by oroszl** [comment]
ok will try to get so stuff together!

**Comment by zerothi** [comment]
And sorry for the delay ;)

**Comment by oroszl** [comment]
I think I still owe you code for the magnetic moment picture.. :)

**Comment by oroszl** [comment]
It seems that the code with the picture has also a use case for the symmetrization.
I put a small package  [here](http://oroszl.web.elte.hu/tmp_files/magnetic_moment_picture.tgz).

**Comment by zerothi** [comment]
This is now fixed.

In order to change a Hamiltonian into a Hermitian one, simply do:
```python
H = sisl.get_sile(...).read_hamiltonian()
H = (H + H.transpose(True)) / 2
# H is now forced Hermitian
```

PS. I'll keep this open for me to remember some tests with @oroszl file.

**Comment by oroszl** [comment]
the point is not simply to make the hamiltonian hermitian 
but rather to make it time-reversal symmetric the two are not the same.
I attach the real spectrum for a symmetrized and unsymmetrized Hamiltonians.
![image](https://user-images.githubusercontent.com/1990999/62429808-9e52d100-b713-11e9-88b1-c38be160db50.png)
The point is that it can happen that for some external reason one performs a SIESTA calculation that breaks time-reversal symmetry but never the less one once to perform a time-reversal symmetric calculation in the post-processing step. 
I am not entirely sure if this is precisely what is implemented in the fix.

**Comment by zerothi** [comment]
Ah, thanks. I see. I will see if I can enable this *once* in the Hamiltonian (like `transpose`).

In fact I think this approach could also be implemented in siesta.

**Comment by zerothi** [comment]
Could you try now:

```python
H = sisl.get_sile(...).read_hamiltonian()
H = (H + H.transpose(True)) / 2
H = (H + H.trs()) / 2
# H is now forced Hermitian and preserving TRS
```

**Comment by zerothi** [comment]
Also, this should never be needed for the overlap matrix since it is *only* a real matrix.

**Comment by oroszl** [comment]
Yep I think this is the case. I will try it out. Did you already push it to conda ?

**Comment by zerothi** [comment]
No, conda is only for new versions. So you have to install manually :)

**Comment by zerothi** [comment]
@oroszl also, could you try the new workbook which provides quite a performance improvement:
https://gist.github.com/zerothi/8c2a1788ec08db092af1c8df5429492d

**Comment by oroszl** [comment]
Will do. Thanks for the update!

**Comment by zerothi** [comment]
A note on the implementation, I have done this:

$H_{TRI}=[H(k)+(s_y) (H(-k)^*) s_y]/2$

which should be equivalent. But please let me know if this is wrong. :)

**Comment by oroszl** [comment]
Yes I think is ok, two "i"-s make a + :)

**Comment by oroszl** [comment]
I tried your notebook, it works as it should! I also see the performance gain. Is it because of the considerable amount of cython you introduced recently?

**Comment by zerothi** [comment]
Thats what I got ;)

And yes, the Cython stuff really improves the performance immensely, but also because there is no conversion between the scipy.sparse and a numpy array when calling `Hamiltonian.eigh` (it will automatically know that it needs the `ndarray`.

I think there is basically no advantage of using `H.Hk/H.Sk` and do your own diagonalization anymore (unless you want to change `H` or `S`). I.e. `H.eigenstate` should be the preferred way of dealing with eigenstates and eigenvectors.

**Comment by zerothi** [comment]
@oroszl a side note.

If you add `TS.HS.Save` to your fdf files then when you read the Hamiltonian from the fdf file it will automatically shift E_F to 0, AND the TSHS file contains the Hamiltonian in double precision (HSX files only contain single precision, so probably you will get better precision). :)

**Comment by oroszl** [comment]
oh.. this is good to know!

**Comment by oroszl** [comment]
hm there is something amiss in the final picture in your example..
it might be that I am wrong and my test case is wrong but if you look at the winding of the moments at the bottom in your case it looks like this:
![nick](https://user-images.githubusercontent.com/1990999/62454485-b1e25400-b774-11e9-82a6-88f5e2f9f606.png)
while in my case it looks like this:
![laszlo](https://user-images.githubusercontent.com/1990999/62454508-bd357f80-b774-11e9-9c49-5bf0969342b1.png)
that is in my case the two circles rotate in opposite direction (like a Rashba spin-orbit pattern)
while in your case they rotate in the same direction.. 
This is an important point since in this system spin-orbit coupling is such that in principle depending on energy both cases can show up.. but if I undersand it correctly we were looking at the same energy!

**Comment by zerothi** [comment]
That is a simple typo on my part, see the updated gist :)
