### ISSUE TITLE
Accessing Fermi energy from SIESTA output.

### ISSUE THREAD

**Issue by oroszl** [zerothi/sisl#126]
**Describe the feature**
I was wondering if there is a simple way to have access to the Fermi energy calculated by SIESTA after I do 
`fdf = sisl.get_sile('sys.fdf').`
It seems from the documentation that I can recalculate it but I do not have an explicit value for it that was produced from SIESTA.

**Comment by zerothi** [comment]
Sadly, no. There is no current method by which output from the output reads the fermi level.

This is a good idea.

/label feature
/label enhancement

**Comment by oroszl** [comment]
Nice!
Thanks, I will try it out!

**Comment by zerothi** [comment]
great :)
