### ISSUE TITLE
Reading .xsf: leading spaces before keywords not allowed

### ISSUE THREAD

**Issue by juijan** [zerothi/sisl#127]
Sisl expects keywords in '''xsf''' to be placed at the beginning of a line. File format allows spaces before keywords.

I propose to remove leading white spaces before `startswith` query in lines 149, 154, 160 of io/xsf.py

This leads to issues when trying to read .XSF file produced by the siesta tool "xv2xsf" or similar, because these utilities include a single whitespace in front keywords.

The [XSF Format Specification](http://www.xcrysden.org/doc/XSF.html) is not really addressing whether these spaces are allowed or not. The examples given however do include space at the beginning of line.

XCrysDen reads files either way.

**Comment by zerothi** [comment]
@juijan thanks for the bug-report! Fixed!
