### ISSUE TITLE
Geometry.close(...,idx=...) behaves strangely

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#13]
**Revision sisl/6a25a7a**

**Test code**
from __future__ import print_function, division
import sisl

xyz = [[i,0,0] for i in range(10)]
geom = sisl.Geometry(xyz)
dR = (0.1,1.1)

r1 = range(5)
r2 = range(5,10)

for ia in r1:
   idx = geom.close(ia, dR=dR, idx=r2)
   print(idx)

for ia in r2:
   idx = geom.close(ia, dR=dR, idx=r1)
   print(idx)

**Observations**
The arrays idx returned in first and second loop are structurally inequivalent

**The above test script returns:**
python test.py
[]
[]
[]
[]
[array([], dtype=int32), array([5], dtype=int32)]
[array([], dtype=int32), array([4], dtype=int32)]
[[], []]
[[], []]
[[], []]
[[], []]

i.e., why is "[]" returned in the first loop, and "[[],[]]" in the second?

**Comment by zerothi** [comment]
Thanks for bringing this inconsistency to my attention.

I have now added tests for both your cases with additional variations.

I *think* and **hope** all inconsistencies should now have been ironed out.

**Comment by zerothi** [comment]
Please use 4f6d520, I forgot a check.
