### ISSUE TITLE
Changing the Hamiltonian elements of a TSHS file

### ISSUE THREAD

**Issue by gadass** [zerothi/sisl#133]
Dear all, 

I would like some help to manipulate the Hamiltonian elements of a TSHS file using the sisl code. 

I'm using the following procedure:

First, importing the TSHS file

```'python
TSHS = 'OPE-Au-1K.TSHS'
Hf  = sisl.get_sile (TSHS).read_hamiltonian()          # get the Full hamiltonian 
Hf.shape

(1722, 129150, 2)
```

As discussed before in [https://github.com/zerothi/sisl/issues/129], I can get the eigenvalues from this Hamiltonian with:

```python
Hf_eigenvals = Hf.eigh()
Hf_eigenvals

array([-17.76640069, -17.74068464, -17.6716626 , ..., 121.11634401,
       168.41796255, 177.23322649])
```

Now, I can apply any shift to these eigenvalues, for example

```python
Hf_eigenvals_m = Hf_eigenvals +1
Hf_eigenvals_m


array([-16.76640069, -16.74068464, -16.6716626 , ..., 122.11634401,
       169.41796255, 178.23322649])
```

I wonder if there is any way to use these modified eigenvalues (Hf_eigenvals_m) to get a modified Hamiltonian (Hf_m).

Thus, I can replace the elements from the original matrix (Hf) by the modified matrix (Hf_m).

I appreciate any help with this.

José Gadelha

**Comment by gadass** [comment]
Other related questions,

(1) Do you know where I can find the eigenvectors associated with Hf.eigh()? I would like to use them to get the new modified matrix.
(2) There is a proper way to get only a 2D matrix from Hf, without the overlap elements? 


José Gadelha

**Comment by zerothi** [comment]
I am on vacation now, so I will have to wait with a more elaborate answer.

1) Use `Hf.eigenstate()`, this yields an Eigenstate object which contains both the eigenvectors *and* the eigenvalues. Note that these eigenvectors are defined in the non-orthogonal basis.
2) `Hf.Hk(k)` will return the Hamiltonian at a k-point (`Hf.Sk(k)` will return the overlap matrix at `k` as well).

**Comment by gadass** [comment]
Dear @zerothi,

thanks for your help. 

I still have a little problem to get back the original elements of the full Hamiltonian, but please, don' t worry with this right now, =D. Have a nice vacation!

Cheers,

José Gadelha

**Comment by zerothi** [comment]
Hi,

If you want to re-generate the Hamiltonian using modified eigenstates, simply use this equality:
```python
H = S V e V^(-1)
```
In `sisl`, this can be done using:
```python
es = H.eigenstate(...)
# ... modify states here
new_H = es.Sk().dot((es.state.T * es.c.reshape(1, -1)).dot(np.linalg.inv(es.state.T)))
```
You can check that `new_H == H` if you don't change the states :)

**Comment by gadass** [comment]
I get it @zerothi,

I am now able to shift the molecular eigenvalues from my two-probe system, =D. 

Thank you very much for your help, all my questions were answered.

Cheers! 

José Gadelha
