### ISSUE TITLE
orbital moment

### ISSUE THREAD

**Issue by oroszl** [zerothi/sisl#136]
Just as sisl calculates spin moments it would be nice to have site resolved orbital moments as well. 
For some use cases, the matrix element matrices of some operators, like the angular momentum operators needed for calculating orbital moments, would be useful for prototyping purposes.

**Comment by zerothi** [comment]
I guess this is the same as `spin_moment` but instead of doing: $<psi|S|psi>$ we do $<psi^T|S|psi>$ and return the matrix instead?

**Comment by oroszl** [comment]
I think it is a bit more involved. In principle this would be an orbital resolved quantity.

**Comment by oroszl** [comment]
In recent versions of SIESTA after the scf run you can request the spin moments and orbital moments associated with all orbital degrees of freedom. 
I am not sure how this is implemented now in SIESTA but in a simple tight-binding picture it would involve calculating the Brillouin-zone average of expectation values like $<psi|P_o L_i P_o|psi>$
where P_o projects to a given orbital and L_i is the i-th component of the angular momentum operator. 
I guess for nonorthogonal systems care needs to be taken to include the overlap matrix.

**Comment by zerothi** [comment]
I think I know what to do, essentially spin_moment == \sum_o orbital_moment.

**Comment by oroszl** [comment]
I am not entirely sure, I think if you have spin-orbit coupling than this is not the case.

**Comment by zerothi** [comment]
Ok, I see. Siesta does it via the density matrix. I can create a `spin_orbital_moment` which is `spin_moment` but orbitally resolved. Not exactly what you want, but for now this is easy. :)

**Comment by zerothi** [comment]
Having looked at the siesta source it seems that there are *several* conventions. Generally I think I need to change routines to `angular_momentum` and have a keyword specifying whether one wants `S`, `L` or `J=S+L` components. In that way there is no ambiguity. But I don't know how to calculate `L` from the eigenstates (Siesta uses DM), so I need to investigate a bit more. However, I am no expert in SO, so any help would be appreciated. :)
