### ISSUE TITLE
Merge different Sparse matrices with associated geometries

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#139]
**Describe the feature**
We want to be able to *merge* different sparse matrices since this would allow one to:

1. create complicated Hamiltonians available for transport calculations
2. create initial DM files my stitching together different DM's

**Comment by jonaslb** [comment]
This might have come indirectly from here? Because I mentioned this to Mads recently. 
In a situation where I wanted to run the same calculation except for a few added ghost atoms, I wanted to reuse the previous DM (and TSHS). I didn't actually check whether it improved convergence speed of siesta, but it didn't crash either, so I guess it works. I can just paste the code I used here (changed variables etc for clarity):

```python
# Load old data, make objects for new data
dm0 = si.get_sile("old/RUN.fdf").read_density_matrix()
tshs0 = si.get_sile("old/RUN.fdf").read_hamiltonian()
dm1 = si.DensityMatrix(si.get_sile("new/RUN.fdf").read_geometry(), orthogonal=False)
tshs1 = si.Hamiltonian(dm1.geom, orthogonal=False)

# Figure out where I inserted the ghost atoms (done separately).
# These are the only atoms that are in the new geometry and not in the old one.
interesting = np.load("some_interesting_atoms_idx.npy")
firstghost = np.max(interesting) + 1
ghosts = np.arange(firstghost, firstghost + len(interesting))
# dm1_uc is the location/atom idx of old geometry in the new geometry (only unit cell)
dm1_uc = np.delete(np.arange(len(dm1.geom)), ghosts)
# dm1_sc is the same as above, but includes all the atoms in the supercells
dm1_sc = dm1.geom.auc2sc(dm1_uc)
# dm0_{sc,uc} are just indices in the old geometry (arange)
dm0_uc = np.arange(len(dm0.geom))
dm0_sc = dm0.geom.auc2sc(dm0_uc)
# Insert elements from old matrix in new matrix, making sure to use the indices above
for uci0, uci1 in zip(dm0_uc, dm1_uc):
    dm1[uci1, dm1_sc] = dm0[uci0, dm0_sc]
    tshs1[uci1, dm1_sc] = tshs0[uci0, dm0_sc]
# Write
dm1.write("new/siesta.DM")
dm1.write("new/siesta.TSDE")
tshs1.write("new/siesta.TSHS")

```

**Comment by zerothi** [comment]
This is partly done by adding `add` which lets one merge two sparse matrices but it will not create any couplings between them.

**Comment by zerothi** [comment]
Now we have `add`, `append/prepend` and `replace` which should do everything.
