### ISSUE TITLE
Using H.sub(<one-tuple of array of int>) gives unexpected results rather than error

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#144]
Sometimes, to figure out how to perform a sub on a hamiltonian, we do something like `atm_idx = (H.atom.Z==6).nonzero()[0]` (or `np.where`) and then parse it to `H.sub(atm_idx)`. A common, or at least easy-to-make mistake is to forget the `[0]` at the end. 

The issue is that when using such a "wrong" index, ie. a one-tuple containing the array of indices, the `H.sub` returns without error or warning but contains wrong results (the geometry seems to be correct). 

I don't know if there's an intended behaviour for passing tuples of indices rather than the indices directly (it is at least not directly mentioned in the documentation). But I think the most appropriate thing here is to raise an error if the indices given to `sub` isn't an iterable of integers.

@mbrandbyge

**Comment by zerothi** [comment]
Good point. 

I have now added a small check for multi-dimensional index. If so, it will raise a `ValueError`.
```python
ValueError: Indexing geometries with a multi-dimensional array is incorrect.
```

Thanks!!!

**Comment by zerothi** [comment]
Changed message to:
```
Indexing geometries with a multi-dimensional array is not supported, ensure 0D or 1D arrays.
```

**Comment by zerothi** [comment]
Would this work?

**Comment by zerothi** [comment]
For future reference one may use `np.flatnonzero` which is a wrapper for `(np.ravel(a)).nonzero()[0]`

**Comment by jonaslb** [comment]
Yes, I think a ValueError with that message would be great!
