### ISSUE TITLE
Siesta read wfs and wfsx files

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#147]
**Describe the feature**
Title says it all. 

Probably this should only be in fdf since then we can read the Hamiltonian and associate it simultaneously with the gauge.

**Comment by zerothi** [comment]
Given this some thought and files should implement this `read_state` method

**Comment by pfebrer96** [comment]
This would be very nice to have :)

**Comment by zerothi** [comment]
I'll reopen since it is not stable for real use. It is slow and only provides one way of dealing with it.

**Comment by zerothi** [comment]
> What do I have to do to test changes in fortran sources? Reinstall sisl again?

Yes, it is fastest locally, and fortran codes are quite fast to compile, so I don't think it should be a problem? A little tedious, but ok...

**Comment by zerothi** [comment]
I believe @pfebrer has done everything here :)
I'll close this.
