### ISSUE TITLE
Implement __repr__ for common classes

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#148]
When using python interactively, I often type the object name to get the string representation rather than use `print()`. The difference is that the first uses `obj.__repr__` while `print` uses `obj.__str__`. When printing a list, the items in the list are also represented by the `__repr__` rather than `__str__`. 

`__repr__` is currently unimplemented for most sisl objects. So when typing eg. `list(H.atom)` you get the unhelpful output `[<sisl.atom.Atom at 0x7f73efed5b00>, ...]`.

Currently `__str__` on common sisl objects give a whole 'tree' of information, which is pretty nice, but not always what you want. I propose that `__repr__` gives the non-recursive version of the same information. So while eg. `str(atom)` would list all the atomic orbitals of that atom, `repr(atom)` could just tell you how many there are. 

Eg. desired output of `list(H.atom)` could be `[<sisl.Atom: C, Z: 6, mass(au): 12.01000, maxR: 2.57730, no: 13>, ...]`.

([link to relevant python docs](https://docs.python.org/3/reference/datamodel.html#object.__repr__))

**Comment by zerothi** [comment]
That is a good idea!

**Comment by zerothi** [comment]
Since this is mostly helpful for `lists` I would suspect we could do something like:

```python
def __repr__(self):
        """ repr of object """
        import re
        return re.sub(r"\n\s*", " ", str(self))
```
to have everything 1 liners.

What do you think about this?

**Comment by jonaslb** [comment]
It would still recursively call string on subcomponents, eg. hamiltonian calls geometry calls atoms calls orbitals. For printing eg. a list this is definitely too much information for each item. I think it should remain a kind of short summary without going into detail, so repr would just be a short format string in each class really.

I will just throw together a quick PR for this to show what I mean.

**Comment by zerothi** [comment]
I'll close this since it is accepted and partially done, we will add more incrementally, thanks Jonas!
