### ISSUE TITLE
MonkhorstPack time reversal symmetry too 'careful'? Some points not reduced

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#160]
`MonkhorstPack` with `trs=True` does not always reduce the k-points fully as can be seen in the example below.

**Reproducable code**
```python
In [1]: import sisl as si, numpy as np; np.set_printoptions(precision=3)

In [2]: list(si.MonkhorstPack(si.SuperCell(3.), [3, 3, 1], trs=False).iter(ret_weight=True))
Out[2]: 
[(array([-0.333, -0.333,  0.   ]), 0.1111111111111111),
 (array([-0.333,  0.   ,  0.   ]), 0.1111111111111111),
 (array([-0.333,  0.333,  0.   ]), 0.1111111111111111),
 (array([ 0.   , -0.333,  0.   ]), 0.1111111111111111),
 (array([0., 0., 0.]), 0.1111111111111111),
 (array([0.   , 0.333, 0.   ]), 0.1111111111111111),
 (array([ 0.333, -0.333,  0.   ]), 0.1111111111111111),
 (array([0.333, 0.   , 0.   ]), 0.1111111111111111),
 (array([0.333, 0.333, 0.   ]), 0.1111111111111111)]

In [3]: list(si.MonkhorstPack(si.SuperCell(3.), [3, 3, 1], trs=True).iter(ret_weight=True))
Out[3]: 
[(array([ 0.   , -0.333,  0.   ]), 0.1111111111111111),
 (array([0., 0., 0.]), 0.1111111111111111),
 (array([0.   , 0.333, 0.   ]), 0.1111111111111111),
 (array([ 0.333, -0.333,  0.   ]), 0.2222222222222222),
 (array([0.333, 0.   , 0.   ]), 0.2222222222222222),
 (array([0.333, 0.333, 0.   ]), 0.2222222222222222)]
```

The k-points `(0, -1/3, 0)` and `(0, 1/3, 0)` should be related by trs but they are not reduced to a single k-point (although oddly it *does* find eg. `(1/3,0,0)`&`(-1/3,0,0)`).

**Comment by zerothi** [comment]
Yes, I know it is too careful. Currently it only looks for duplicates along one direction. I should probably have a look at it, but usually there are relatively few extra points.

**Comment by jonaslb** [comment]
So although this is not super important (as you say it is relatively few points), I find it somehow a bit bothersome that I can't just ask sisl for a full trs reduced bz. It would be simple enough to do it by generating the full mp grid and then

```python
k = bz.k
weights = bz.weight

ik1, ik2 = np.where(np.linalg.norm(k[None,...]+k[:,None,:], axis=2)<1e-20)
rel = ik1 < ik2
ik1 = ik1[rel]
ik2 = ik2[rel]
k = np.delete(k, ik2, axis=0)
weights = np.delete(weights, ik2)
kidx, count = np.unique(ik1, return_counts=True)
weights[kidx] *= count + 1

trs_bz = si.BrillouinZone(bz.parent, k, weights)
```

However there is the 'outer sum' (maybe undesired/unnecessary?) and doing this in `MonkhostPack.__init__` would also require messing with the `.asgrid` function, I think. Perhaps it could be added as a `.with_trs` function on the general `BrillouinZone` object instead?

**Comment by zerothi** [comment]
Yeah, I am mostly worried about the outer sum, it has to be done before constructing the full BZ.
We can however, reduce this to two direction k-points (since one part of the BZ is the easy part).

I don't think it should be added to the `BrillouinZone`, I'll try and come up with a good one. :)
Thanks for the snippet! It seems quite generic!
