### ISSUE TITLE
spgeom.repeat on particular tshs gives wrong results / crashes, at least when used twice

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#161]
I ran into a bug with an electrode that I wanted to `.repeat` instead of `.tile`. It resulted in a crash. 

When doing `Helec.repeat(3, 1).repeat(3, 0)`, the first repeat will always work well (as in, not crash), but the second one will *usually*, but *not always*, crash:

```python
In [1]: import sisl as si

In [2]: H=si.get_sile("elec.TSHS").read_hamiltonian()

In [3]: H.repeat(3, 0).repeat(3, 1)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-645fb0da8346> in <module>()
----> 1 H.repeat(3, 0).repeat(3, 1)

/home/jolub/git/sisl/sisl/sparse_geometry.py in repeat(self, reps, axis)
   1922 
   1923         # Now we should fill the data
-> 1924         isc = geom.o2isc(col)
   1925         # resulting orbital in the new geometry (without wrapping
   1926         # for correct supercell, that will happen below)

/home/jolub/git/sisl/sisl/geometry.py in o2isc(self, io)
   3089         """
   3090         idx = _a.asarrayi(io) // self.no
-> 3091         return self.sc.sc_off[idx, :]
   3092 
   3093     def o2sc(self, o):

IndexError: index -7976227 is out of bounds for axis 0 with size 225
```

The index which is said to be out of bounds (and clearly is) is always a new number. I guess it doesn't crash if this number happens to be in bounds. The tshs can be gotten [here](https://send.firefox.com/download/ba86c7c976883d64/#If2SSRiqCVbpFBsNBHHMcw) (time- and download limited link).

Tested on current master.

**Comment by jonaslb** [comment]
I had a small example with graphene but I deleted it because I think it had to do with sparse eigenvalue finding rather than any indication of a sisl bug. The crash for a particular tshs is still there and Ill try again to find a new, simple example.

**Comment by jonaslb** [comment]
The issue is that `indices` supplied for the csr of the `.repeat`ed hamiltonian (in this case) contains 42000 uninitialized elements. I guess that the loop that starts on line 1955 of sparse_geometry.py is supposed to set all the elements to some values, but that doesn't happen in this case.

If sanity is asserted for the mentioned loop as below, the error moves up to the first usage of `.repeat`. Unfortunately I haven't figured this loop out yet.

```python
# Create repetitions
        allindidx = []
        for _ in range(reps):

            # Update atomic offset
            OA += AO
            # Update the offset
            O += 1
            # Correct supercell information
            isc[:, axis] = O // reps

            # Create the indices for the repetition
            idx = array_arange(indptr[array_arange(OA, n=AO)], n=ncol)
            allindidx.append(idx)
            indices[idx] = JO + oA * (O % reps) + sc_index(isc) * no_n
        fullidx = np.arange(len(indices))
        alliidx = np.concatenate(allindidx)
        assert len(np.setdiff1d(fullidx, alliidx)) == 0
```

**Comment by zerothi** [comment]
> I had a small example with graphene but I deleted it because I think it had to do with sparse eigenvalue finding rather than any indication of a sisl bug. The crash for a particular tshs is still there and Ill try again to find a new, simple example.

Yes, one cannot find *all* eigenvalues using sparse eigenvalue solvers. I'll have a look at the other problem.

**Comment by zerothi** [comment]
I think I have narrowed down the problem, now I just need to solve it ;)

**Comment by zerothi** [comment]
@jonaslb could you check? I have added two tests which now works. So I *hope* it should be done! :)

Otherwise, please re-open this bug!

**Comment by jonaslb** [comment]
I just tested quickly: Before fix, the previously inserted assertion failed when using repeat on 95/128 small tshs'es i had lying around. Afterwards it happens on 0. So it looks like great work :)

**Comment by zerothi** [comment]
@jonaslb Great!
