### ISSUE TITLE
Transfer orbital to subgrid of a whole system's grid

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#164]
I'm not sure if this is already possible, but I can't seem to find out how to do it.

**My problem is:**

Given an orbital centered in an atom of the geometry, I want to do the following integral: `< orb | V |  orb >`, where V is the total potential. 

**What I have:**
- The real space grid of the total potential.
- A `sisl.SphericalOrbital` object with the information of the orbital. 

**Slow but working approach:**

One approach to do the integral is to iterate over each value of the V grid and, given the indices of that value, calculate the value of the wavefunction for that point in space.

**What I would like to do:**

I would like to have a grid containing the wavefunction with points that correspond exactly to the real space coordinates of the potential grid. 

In that way I could just multiply the two numpy arrays and then sum over all the axes, which is extremely fast.

I know how to generate a grid with the same spacing and the same size (and take only the relevant subgrid of the potential) , but **I don't know how to ensure that the points of the grid in real space are the same** in both cases.

I would be very grateful if you could clarify how can this be done (if there is a better way to calculate this integral I would also like to know).

Thank you very much!

**Comment by zerothi** [comment]
I guess something like this would work:
```python
import sisl as si
V_grid = <your TotalPotential which also contains the geometry>
V = V_grid.grid.ravel()
orb_grid = V_grid.copy()
for ia in V_grid.geometry:
    geomia = V_grid.geometry.sub(ia)
    state = np.empty(geomia.no)
    orb_grid.set_geometry(geomia)
    for io, orb in enumerate(geomia.atoms[0]):
        state.fill(0.)
        state[io] = 1. # your fake state coefficients
        si.electron.wavefunction(state, orb_grid)
        orb_grid.grid *= V_grid.grid
        bra_ket = orb_grid.grid.ravel().dot(V)
```

It will probably be a bit faster if the geometry *only* contains the single orbital, but you can check that.
Also, please do some tests to ensure everything is calculated correctly. The wavefunction algorithm is tested, but not extensively!

**Comment by zerothi** [comment]
As for the best way to generate the integrals, currently there isn't, since sisl does not implement matrix element calculations like Siesta does.

**Comment by zerothi** [comment]
Please see the updated script. I forgot to zero the `orb_grid`.

**Comment by pfebrer96** [comment]
Thank you very much Nick!

I forgot to mention that my orbital is not a valence orbital but a core orbital that I take from an AE calculation with atom.

I've tried something similar to what you proposed:

```python
#I read the potential from the .VT file and set its geometry
Vt = sisl.get_sile(VTfile).read_grid()
Vt.set_geometry(geom)

#I define the Oxygen 1s orbital using the radial part from an AE calculation
orb = sisl.SphericalOrbital(0, radialPart.T)

#Define the new geometry with only the atom that I care about and the 1s orbital
atOrb = orb.toAtomicOrbital()
newGeom = sisl.Geometry(Vt.geom[iAtom], atom = sisl.Atom(8,atOrb), sc = Vt.geom.sc)

#Create the orbital grid and set its geometry (with only the relevant orbital)
orb_grid = Vt.copy()
orb_grid.fill(0.)
orb_grid.set_geometry(newGeom)

#Project the orbital in the grid
sisl.physics.electron.wavefunction(np.array([1]), orb_grid) 
```

However,  `orb_grid.grid.sum()` returns 0.0, even though `orb.toGrid().grid.sum()` returns a non-zero value. Can you tell what I am doing wrong here?

Thanks!

**Comment by zerothi** [comment]
I need something to test with ;) I can't see what you are doing exactly. Could you create a tar or something?

**Comment by pfebrer96** [comment]
Sure, here it is:

https://www.dropbox.com/s/lkzc6fowi9jggph/CoreLevelTest.tar.xz?dl=0

**Comment by pfebrer96** [comment]
There's something missing, let me build it again

**Comment by pfebrer96** [comment]
Now, here should be everything needed to reproduce this:

https://www.dropbox.com/s/6qf297eenlwi4q9/CoreLevelTest.tar.xz?dl=0

**Comment by zerothi** [comment]
It is because there is some inconsistencies in sisl when atoms are not in the primary unit-cell. I have to really look into this.

This should fix your calculations, right after you have read in the geometry, then correct the coordinates:
```python
geom.xyz[:, :] = (geom.fxyz % 1.).dot(geom.cell)
```

**Comment by zerothi** [comment]
For this:
```python
print((orb_grid.grid * Vt.grid).ravel().dot(orb_grid.grid.ravel()) * orb_grid.dvolume)
```
I get something like `-1.2587099948140552`

**Comment by pfebrer96** [comment]
Yes! Niceee, thank you :)
