### ISSUE TITLE
Pauli matrices in sisl

### ISSUE THREAD

**Issue by bfocassio** [zerothi/sisl#165]
How one should write the pauli matrices in sisl, including SOC ?

I'm aware that the spin convention is currently set to:

[Re(upup) Re(dndn) Re(updn) Im(updn) Im(upup) Im(dndn) Re(dnup) Im(dnup)]

So I could write:

```python
sx = [0,0,1,0,0,0,1,0]
sy = [0,0,0,-1,0,0,0,1]
sz = [1,-1,0,0,0,0,0,0]
```
Is that correct?

I'm interested in this so I can change the Hamiltonian terms to include a small perturbation like an exchange magnetic field like dH = B . sigma .

**Comment by zerothi** [comment]
Yes, this looks correct.

I have just added in bf6554493 variables `SX`, `SY` and `SZ` to the Hamiltonians

I.e.
```python
H = sisl.Hamiltonian(..., spin='SOC')
print(H.SX)
[0,0,1,0,0,0,1,0]
```

Thanks for the question!

**Comment by zerothi** [comment]
Ups, let me know if this works for you.

**Comment by bfocassio** [comment]
Thank you, it works
