### ISSUE TITLE
Hamiltonian and auxiliary supercell convention

### ISSUE THREAD

**Issue by bfocassio** [zerothi/sisl#168]
What's the auxiliary supercell convention used by sisl and how one can change it?

Suppose I have 400 (no) orbitals on the principal cell and 1 x 1 x 3 as the auxiliary supercell.

Columns from 0 to 399 corresponds to the original cell, from 400 to 799 to the left auxiliary cell and from 800 to 1199 to the right auxiliary cell. Is that right?

How can I reassign those matrix elements?

For example something like:

```python
new_H = old_H.copy()
new_H[:,no:2*no] = old_H[:,2*no:3*no]
new_H[:,2*no:3*no] = old_H[:,no:2*no]
```

**Comment by zerothi** [comment]
Hi,

Why do you wan't to change the convention?
It is *pretty* hardcoded in the code.

If you want to know which supercell index related to which offset you can do:
```python
H.sc_index([0, 0, 0]) * H.no # offset for [0, 0, 0]
H.sc_index([0, 0, -1]) * H.no # offset for [0, 0, -1]
H.sc_index([0, 0, 1]) * H.no # offset for [0, 0, 1]
```
Alternatively one can find the supercell value for a given offset, for instance this will *always* return true:
```python
H.sc_index(H.sc_off[i, :]) == i
```

I would highly recommend you to *not* change the internal lookup tables and stick with sisl's order. But perhaps you could elucidate me why you want to change it?

Say if you want to test for symmetry, use `H.transpose` instead (which correctly transposes values in the supercell structure).

**Comment by bfocassio** [comment]
I'm using sisl to write siesta's Hamiltonian to input into an external code which seems to use a different convention. From what I'm getting, the code uses -1 0 1 while sisl uses 0 -1 1. Just for curiosity which is the convention used by siesta ?

Besides the Hamiltonian, I also need to write the indices of the non zeros rows and cols (`H.nonzero()`). I figured that it may be better to just reorder the result of:

```python
row, col = H.nonzero()
```

**Comment by zerothi** [comment]
Ok.

If you want this I would highly recommend you to add the output mechanism to sisl directly (i.e. create a PR) Then it will be publicly available and easier to debug ;)
I would welcome such a tool!

If you simply want to change columns to others it isn't too difficult.
```python
from sisl.utils.ranges import array_arange
row, col = H.nonzero()

sc_out = H.geometry.sc.copy()
sc_out.sc_off = [
 [0, 0, -1],
 [0, 0, 0],
 [0, 0, 1]]
index_table = sc_out.sc_index(H.geometry.sc.sc_off)
conversion_table = array_arange(index_table * H.no, (index_table + 1) * H.no)

out_col = conversion_table[col]
```
I *think* this should work (untested!). I think the order of operations should also work ;)

**Comment by bfocassio** [comment]
Thank you for your answer. Using your code I was able to print de column elements in the way I needed. In the future work more on this tool.

**Comment by zerothi** [comment]
Great :)
I'll close this issue then. Feel free to contribute your code to sisl ;)
