### ISSUE TITLE
A full on example on how to build a transport system, calculate all the transport properties by learning the exact parameters.

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#173]
**Describe what you want to accomblish with TS+TBT+sisl**

**Comment by zerothi** [comment]
Hi please follow the tutorial [here](https://www.github.com/zerothi/ts-tbt-sisl-tutorial).

There are slides present (check under releases) and I would highly suggest you to carefully go through them.

Please note that the examples provided in the tutorial cannot be used as real calculations, nor can the pseudo-potentials.
