### ISSUE TITLE
read_scf xarray or pandas

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#175]
> By the way, do you think it makes sense to have the possibility of returning an xarray DataArray from the read_scf method so that it is explicit what each value means?

I've been looking into this and it should be an `xarray.Dataset` instead of an `xarray.DataArray`, because there is more than 1 dependent variable. In fact, there are at least 6:  `["Eharris","E_KS", "FreeEng", "dDmax", "Ef", "dHmax"]`. In theory, there might be 2 independent variables if all MD steps and all iscf are requested ( `["MDstep", "iscf"]` ), but otherwise there is only one. In the case there is 1, I think it is much more convenient to use a `pandas.DataFrame`. Even in the case with 2 independent variables, "iscf" could really be made dependent so that you can have a reguar `pandas.DataFrame`. Since different MDsteps have different numbers of iscf you end up with a very empty `xarray.Dataset` anyway, so I don't know what's the difference in memory.

All in all, I know that `pandas` would be an extra dependency, but I don't see much advantage with `xarray` unless the data is in a grid (in that situation there are no empty slots).

I'm just writing this to keep this thought here for further possible discussion :)

_Originally posted by @pfebrer96 in https://github.com/zerothi/sisl/pull/174#issuecomment-599699524_

**Comment by zerothi** [comment]
There are routines which return `xarray.DataArray` (see `pdosSileSiesta`).
If you do this, I would advice doing something similar. Currently `xarray` is added as an optional dependency, one can do:
```bash
pip3 install --user sisl[analysis]
```
which also adds the xarray dependency when installing. However, it may easily be installed subsequently and then used.

In this way we don't *force* the dependency, but allow users to choose. Mainly because pandas/xarray are *big* packages.

**Comment by zerothi** [comment]
I have thought about this and we should use dataset if both all iscf and imd are requested, otherwise we should return a dataarray.

**Comment by pfebrer96** [comment]
I don't understand how this datarray would look. For what I understand (which may be wrong), datarray is like a Series (column) in pandas, with the difference that it has more than one index, because it depends on more than one variable and that makes it multidimensional. Therefore, each property should be a datarray (Series) and if you have 6 properties you should have a dataset (Dataframe) "made of" 6 datarray (with 6 columns).

The only difference I see is in the number of independent variables. And in this case there might be either 1 (unidimensional dataarrays, a pandas Series would be the same) or 2 depending on the input arguments.

Could you point me where I am wrong? Thanks.

**Comment by pfebrer96** [comment]
For example, in the case of PDOS, it is a dataarray because it's only one property (PDOS) that depends on multiple variables (E, n, l, m...).

**Comment by zerothi** [comment]
You are absolutely correct... Sorry for the confusion ;)

**Comment by pfebrer96** [comment]
I implemented it in this commit:
https://github.com/pfebrer96/sisl/commit/3e6a5da70404ebaccd1c238361f7d7ab694e6595

But I did it in the same branch that you already merged, so now I don't know how to do it to create a pull request. Sorry, I'm still a bit stupid regarding the github stuff haha

Can't wait to use this for a plot :)

**Comment by zerothi** [comment]
You should basically do the same as I recommended you to do previously:

```bash
git diff HEAD^.. > new.patch
git checkout master
git pull
git checkout -b read_scf_pandas
patch -p1 < new.patch
git commit ...
git push
```
Please remember to clean up your local branches and remote branches once they are merged, it makes life easier for you (and me). :)

**Comment by pfebrer96** [comment]
Yes, sorry. Since I started working on it before you merged it I didn't know what to do. The PR is created now: https://github.com/zerothi/sisl/pull/177

**Comment by zerothi** [comment]
Hmm, now I am in doubt of whether it is feasible to do with Dataset, or whether we should actually use a Dataframe.

The nice thing about Dataframe is that one can easily do multi-indexing, say MultiIndex([md, scf]) while this is not as clear in xarray.

Also, the good thing about using Pandas is that its storage model is better utilized. xarray stores a dense matrix which means that the size of the data will be proportional to the larges max(iscf) * max(imd) which *could* potentially blow up.

Additionally if using Pandas one could merge different files and have filenames as another multi-index, and in this way do complicated stuff...

The sad thing about the DataFrame is that it does not contain any attributes related to the information... :(

**Comment by pfebrer96** [comment]
> xarray stores a dense matrix which means that the size of the data will be proportional to the larges max(iscf) * max(imd) which could potentially blow up.

Yes, this was my point here:

> Since different MDsteps have different numbers of iscf you end up with a very empty xarray.Dataset anyway, so I don't know what's the difference in memory.

> but I don't see much advantage with xarray unless the data is in a grid (in that situation there are no empty slots).

However, querying multidimensional data is much easier with `xarray` I think, which in my opinion is a thing to take into account, because there is no point in having data stored very efficiently if you can not access it easily. Although one could always use the `to_xarray` method in pandas to convert the DataFrame to a Dataset if they want to.

> The sad thing about the DataFrame is that it does not contain any attributes related to the information... :(

Yes, that is unfortunate. They would need to be passed separately. Or passed as attributes of the dataframe with a warning that they will not persist through operations

**Comment by zerothi** [comment]
> However, querying multidimensional data is much easier with `xarray` I think, which in my opinion is a thing to take into account, because there is no point in having data stored very efficiently if you can not access it easily. Although one could always use the `to_xarray` method in pandas to convert the DataFrame to a Dataset if they want to.

I don't find it particularly difficult, see [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced-indexing-with-hierarchical-index).

I think we should go for pandas in this case...

**Comment by pfebrer96** [comment]
Ok, I will change it then. I should also keep pandas as an optional dependency, right (import it only if the DataFrame is requested)?

By the way, I've noticed that the `query()` method (which I have never used before) works for multi indexed dataframes as well. It seems more effective and simple to me than what they recommend in the docs that you passed. Just leaving an example here to keep it written somewhere for future readers:

```python
import pandas as pd
import numpy as np

# Random dataframe
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
ser = pd.Series(np.random.randn(8), index=index)
df = pd.DataFrame(ser)

# Query it using query()
desired = ["bar", "baz"]
df.query('first in @desired ')
```

**Comment by zerothi** [comment]
> Ok, I will change it then. I should also keep pandas as an optional dependency, right (import it only if the DataFrame is requested)?

Yeah, correct. :)
 
> By the way, I've noticed that the `query()` method (which I have never used before) works for multi indexed dataframes as well. It seems more effective and simple to me than what they recommend in the docs that you passed. Just leaving an example here to keep it written somewhere for future readers:

Ok :)

**Comment by zerothi** [comment]
And thanks! :)

**Comment by zerothi** [comment]
I believe this is already in the code, please re-open if needed.

**Comment by pfebrer96** [comment]
Yes, this is already in!
