### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by sofiasanz** [zerothi/sisl#176]
The description of `norm2` in https://sisl.readthedocs.io/en/latest/_modules/sisl/physics/state.html#State.norm2 does not correspond to the latest version of this method in the source code, where the overlap matrix is taken into account to obtain the norm of the state.

**Comment by zerothi** [comment]
In fact, the `State` object does not take into account the overlap matrix, this is only the `ElectronState` object which does that. :)
So I think it is correct, no?

**Comment by sofiasanz** [comment]
Ooops yes you're right! We can close this then :)
