### ISSUE TITLE
Grid interpolation failing for 1D and 2D grids

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#178]
**Describe the bug**
When you have a grid with shape (1,) in one axis, the interpolation fails. It returns a grid full of `nan`.

This situation of having a "non 3D" grid seems stupid, but I think it's not. It happens for example when you average one of the directions to plot the grid in the other two or you take a cross section of the full grid.

In these cases, ideally one would like to interpolate after averaging, since it is a waste of time to interpolate the full 3D grid and then average (and maybe it is not even possible due to memory issues).

I tried to see how to fix it, but for you it will probably much faster to do it, since are already familiar with how the interpolator works.

As a workaround right now I am just duplicating the grid in the averaged dimension so that I can have shape == 2 and the method runs without problems

**Reproducable code**
```python
grid = sisl.Grid(0.1, sc=10)
# Average the Z axis
grid = grid.average(2)
# Try to refine the grid 
grid = grid.interp((grid.shape[0]*2, grid.shape[1]*2, 1))
```
After running this code, you get a `true_divide` warning and `grid.grid` is full of `nan`.

**Comment by pfebrer96** [comment]
By the way, regarding this issue: have you thought of storing the grid as an `xarray.DataArray` instead of a `numpy.ndarray` and let them handle interpolation? I supose the reason to not do it like this is to not enforce the `xarray` dependency, but it really would add a lot of functionality to the grid without having to do anything.

If not, `Grid` could have a `toxarray()` method (which would be very easy to build).

**Comment by zerothi** [comment]
> By the way, regarding this issue: have you thought of storing the grid as an `xarray.DataArray` instead of a `numpy.ndarray` and let them handle interpolation? I supose the reason to not do it like this is to not enforce the `xarray` dependency, but it really would add a lot of functionality to the grid without having to do anything.
> 
> If not, `Grid` could have a `toxarray()` method (which would be very easy to build).

After you questioned the `read_scf` I did think about it. But currently I don't think having this extra dependency would be meaningful. Also, one problem is that the dimensions in xarray are forcefully 1D arrays. However, in this case (for skewed cells) the dimensions need a matrix `(len, 3)` to store the divisions along the lattice vector. So there are things that could not be represented easily. :(

**Comment by zerothi** [comment]
However, the `to_xarray` is something I have thought about, but again, the above limitation may be counter intuitive for end-users thus giving unwanted sideeffects.

**Comment by pfebrer96** [comment]
> However, in this case (for skewed cells) the dimensions need a matrix (len, 3) to store the divisions along the lattice vector.

I don't think I fully understand the problem . Is it a problem to have a skewed cell if the coordinates of the grid are fractional (not Ang)?

By the way, `xarray` allows coordinates that are not dimensions. And these coordinates can depend on multiple dimensions. I'm not sure how it works because I have not used it, but this might help.

**Comment by zerothi** [comment]
Because I can't get this to work:

```python
import numpy as np
import xarray as xr
rand = np.random.rand

a = xr.DataArray(rand(4, 5, 6),
             coords=[("x", rand(4)),
                     ("y", rand(5)),
                     ("z", rand(6))])
print(a)

a = xr.DataArray(rand(4, 5, 6),
                 coords={"al": np.arange(4),
                         "bl": np.arange(5),
                         "cl": np.arange(6),
                         "xyz": 3,
                         "a": (("al", "xyz"), rand(4, 3)),
                         "b": (("bl", "xyz"), rand(5, 3)),
                         "c": (("cl", "xyz"), rand(6, 3))},
                 dims=["al", "bl", "cl"])
print(a)
```
I would like the 2nd option.
A grid-direction is defined by the lattice vector (which has 3 components, x, y, z).

**Comment by pfebrer96** [comment]
Is there something wrong with doing this:

```python
import numpy as np
import xarray as xr

lattice_vecs = np.array([
    [10,4,1],
    [1,6,8],
    [1,2,4]
], dtype=float)

ndivs = (4,5,6)

# Define all the fractional values that a point in the grid can have
# Do this for each lattice vector
fAs = np.linspace(0, 1, ndivs[0])
fBs = np.linspace(0, 1, ndivs[1])
fCs = np.linspace(0, 1, ndivs[2])

# Get the grid of values for each component
fAs_grid, fBs_grid, fCs_grid = np.meshgrid(fAs, fBs, fCs)

# From those grids, calculate the grids for the real space coordinates.
x, y, z = np.dot(lattice_vecs, [fAs_grid.flatten(), fBs_grid.flatten(), fCs_grid.flatten()])

# Build an array whose logical coordinates will be fractional
# But its physical coordinates will be x, y, z
arr = xr.DataArray(rand(4, 5, 6),
                 coords={"fA": fAs,
                         "fB": fBs,
                         "fC": fCs,
                         "x": (("fA", "fB", 'fC'), x.reshape(ndivs)),
                         "y": (("fA", "fB", 'fC'), y.reshape(ndivs)),
                         "z": (("fA", "fB", 'fC'), z.reshape(ndivs))},
                 dims=["fA", "fB", "fC"],
                 attrs={
                     'a': lattice_vecs[0],
                     'b': lattice_vecs[1],
                     'c': lattice_vecs[2]
                 }
)

print(arr)
```
Then one could go like:
```python
# Get every point of the grid with an x greater than 2 and y smaller than 5
arr.where((arr.x > 2) & (arr.y < 5))
# Or get the minimum grid that fulfills this condition
arr.where((arr.x > 2) & (arr.y < 5), drop=True)
# The values that are "leftovers" due to the swewedness of the cell
# can be set to whatever you want instead of NaN, (good for integrating for example)
arr.where((arr.x > 2) & (arr.y < 5), drop=True).fillna(0)
```
Otherwise you could build a less intuitive representation of the cell by making "x", "y" and "z" the logical coordinates. The array representation would be impossible to understand (shape would be (uniqueXs, uniqueYs, uniqueZs) ), but one could query the dataarray very easily based on the real space coordinates. It doesn't seem worth it though.

**Comment by zerothi** [comment]
No your coordinates `x, y, z` take up as much memory as the data values. This is not smart. I have far too often had problems with `Grid` due to sizes of it. So that won't work... :(

**Comment by zerothi** [comment]
I however, like the idea of it being a fractional index. That could work since all information is retained.

**Comment by pfebrer96** [comment]
> No your coordinates x, y, z take up as much memory as the data values. This is not smart. I have far too often had problems with Grid due to sizes of it. So that won't work... :(

Yeah I thought so too. It actually takes 4 times more memory I guess because I'm generating 3 extra grids. 

How about generating the real coordinates grids on the fly, like:

```python

import numpy as np
import xarray as xr
from types import MethodType
rand = np.random.rand

lattice_vecs = np.array([
    [10,4,1],
    [1,6,8],
    [1,2,4]
], dtype=float)

ndivs = (4,5,6)

# Define all the fractional values that a point in the grid can have
# Do this for each lattice vector
fAs = np.linspace(0, 1, ndivs[0])
fBs = np.linspace(0, 1, ndivs[1])
fCs = np.linspace(0, 1, ndivs[2])
    
def get_fractional_grids(arr):
    return np.meshgrid(arr["fA"], arr["fB"], arr["fC"])

def get_coord_grid(arr, ax):
    return np.dot([arr.a[ax], arr.b[ax], arr.c[ax]], [grid.flatten() for grid in get_fractional_grids(arr)]).reshape(arr.shape)

class xArrayGrid(xr.DataArray):
    
    __slots__ = ()
    
    @property
    def x(self):
        return get_coord_grid(self,0)

    @property
    def y(self):
        return get_coord_grid(self,1)

    @property
    def z(self):
        return get_coord_grid(self,2)

# Build an array whose logical coordinates will be fractional
# But its physical coordinates will be x, y, z
arr = xArrayGrid(rand(*ndivs),
                 coords={"fA": fAs,
                         "fB": fBs,
                         "fC": fCs,
                    },
                 dims=["fA", "fB", "fC"],
                 attrs={
                     'a': lattice_vecs[0],
                     'b': lattice_vecs[1],
                     'c': lattice_vecs[2],
                 }
)
```

We would get exactly the same functionality without storing it in the object (4 times less memory), but still a very big object will be generated each time we want to filter. It's not enough right? :)

**Comment by pfebrer96** [comment]
And I guess this real coordinate grids could safely be `float32`, right? (I'm not sure on how precision exactly works)

**Comment by zerothi** [comment]
No, you generally don't want to generate such big arrays for these small purposes, handy as they are... :(
