### ISSUE TITLE
BrillouinZone.asdataarray

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#182]
For example, let's say I got the bands values from BandStructure.eigh() but I want them as a dataarray. I would have to rewrite all the code, assuming that I know how to build a DataArray properly, or copy/paste it in case I knew where the code that I need is located (unlikely to happen with users).

_Originally posted by @pfebrer96 in https://github.com/zerothi/sisl/pull/179#issuecomment-605144003_

I'll see to it and create the necessary things. Thanks

**Comment by pfebrer96** [comment]
I'm using this and works great :100: . Nice work!
