### ISSUE TITLE
H.dHk yields NoneType Error

### ISSUE THREAD

**Issue by bfocassio** [zerothi/sisl#183]
dHk is giving me a NoneType error for Hamiltonians read from a siesta calculation.

This example works:

```
graphene = geom.graphene()
H = Hamiltonian(graphene)
H.construct([(0.1, 1.44), (0, -2.7)])
H.dHk(k=(0,0,0))
```

and I get:

```
(<2x2 sparse matrix of type '<class 'numpy.complex128'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 <2x2 sparse matrix of type '<class 'numpy.complex128'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 <2x2 sparse matrix of type '<class 'numpy.complex128'>'
 	with 4 stored elements in Compressed Sparse Row format>)
```

as expected

The following **does not** work:

```
siesta_sile = sisl.get_sile('siesta.fdf')
siesta_geom = siesta_sile.read_geometry()
siesta_H = siesta_sile.read_hamiltonian(geometry=siesta_geom)
siesta_H.dHk(k=(0,0,0))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-60-1a4a088c24e8> in <module>
      2 siesta_geom = siesta_sile.read_geometry()
      3 siesta_H = siesta_sile.read_hamiltonian(geometry=siesta_geom)
----> 4 siesta_H.dHk(k=(0,0,0))

TypeError: 'NoneType' object is not callable

```

The odd part is that both, Hk and ddHk, work. The same is valid for the overlap matrix.

Please, what am I missing ??

**Version details**
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
0.9.8
13a327bd8e27d689f119bafdf38519bab7f6e0f6

**Comment by zerothi** [comment]
That is indeed wierd, could your print `siesta_H` before calling `dHk`? and give me the output?

**Comment by bfocassio** [comment]
I can even compute the band structure, DOS and all.

The output is:

Hamiltonian{non-zero: 3644, orthogonal: False,
 Spin{spin-orbit, kind=f},
 Geometry{na: 4, no: 28,
  Atoms{species: 2,
   Atom{Bi, Z: 83, mass(au): 208.98000, maxR: 3.14160,
    AtomicOrbital{6sZ1, q0: 2.0, SphericalOrbital{l: 0, R: 2.7725, q0: 2.0}},
    AtomicOrbital{6pyZ1, q0: 1.0, SphericalOrbital{l: 1, R: 3.1416, q0: 3.0}},
    AtomicOrbital{6pzZ1, q0: 1.0, SphericalOrbital{l: 1, R: 3.1416, q0: 3.0}},
    AtomicOrbital{6pxZ1, q0: 1.0, SphericalOrbital{l: 1, R: 3.1416, q0: 3.0}},
    AtomicOrbital{6dxyZ1, q0: 0.0, SphericalOrbital{l: 2, R: 2.2699, q0: 0.0}},
    AtomicOrbital{6dyzZ1, q0: 0.0, SphericalOrbital{l: 2, R: 2.2699, q0: 0.0}},
    AtomicOrbital{6dz2Z1, q0: 0.0, SphericalOrbital{l: 2, R: 2.2699, q0: 0.0}},
    AtomicOrbital{6dxzZ1, q0: 0.0, SphericalOrbital{l: 2, R: 2.2699, q0: 0.0}},
    AtomicOrbital{6dx2-y2Z1, q0: 0.0, SphericalOrbital{l: 2, R: 2.2699, q0: 0.0}}
   }: 2,
   Atom{H, Z: 1, mass(au): 1.01000, maxR: 2.68610,
    AtomicOrbital{1sZ1, q0: 1.0, SphericalOrbital{l: 0, R: 2.6198, q0: 1.0}},
    AtomicOrbital{1sZ2, q0: 0.0, SphericalOrbital{l: 0, R: 0.9392, q0: 0.0}},
    AtomicOrbital{2pyZ1, q0: 0.0, SphericalOrbital{l: 1, R: 2.6861, q0: 0.0}},
    AtomicOrbital{2pzZ1, q0: 0.0, SphericalOrbital{l: 1, R: 2.6861, q0: 0.0}},
    AtomicOrbital{2pxZ1, q0: 0.0, SphericalOrbital{l: 1, R: 2.6861, q0: 0.0}}
   }: 2,
  },
  maxR: 3.14160,
  SuperCell{nsc: [3 5 1],
   A=[5.350, 0.000, 0.000],
   B=[-2.675, 4.633, 0.000],
   C=[0.000, 0.000, 15.000],
  }
 }
}

**Comment by zerothi** [comment]
Actually it is because I had never implemented it for SOC nor NC.

So the fact that you could call `ddHk` is a leftover and should not work.

I'll fix this ASAP. But adding the dHk/ddHk implementation takes some more time...
Now calling dHk should return `NotImplemented`

Thanks for finding this. :)

Sorry...
