### ISSUE TITLE
Geometry.sort

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#191]
I understand, but I still think it could be convenient to have some general methods for reordering geometries, such as
- [x] ascending/descending along lattice vectors
- [x] along axes
- [ ] species
- [ ] group labeling
- [x] combinations (e.g. first species, then axes), this is particularly easy since Python >=3.6 uses ordered dicts for `**kwargs`, so `sort` should change interface to `**kwargs`
- [x] one of the above on a subset of atoms

These should be added to `Geometry.sort`

_Originally posted by @tfrederiksen in https://github.com/zerothi/sisl/pull/190#issuecomment-605926535_

**Comment by zerothi** [comment]
@tfrederiksen for group labelling, do you mean the `geometry['name']` thingy? Or by *tags* for atoms?

**Comment by tfrederiksen** [comment]
> @tfrederiksen for group labelling, do you mean the `geometry['name']` thingy? Or by _tags_ for atoms?

I had the first thingy in mind, but perhaps both possibilities are reasonable?

As a thought example, what would be a convenient way for the user to reorder a geometry into (i) first a molecule sorted according to ascending atomic numbers, then (ii) the substrate atoms ordered according to lattice vectors (but not atomic numbers).

By the way, another useful feature could be to also translate atoms by lattice vectors to ensure they are in the primitive cell (before/after sorting). I know this could be rather easily done by the user querying `Geometry.fxyz`, but some simple functionality could be cool to have.

**Comment by zerothi** [comment]
> By the way, another useful feature could be to also translate atoms by lattice vectors to ensure they are in the primitive cell (before/after sorting). I know this could be rather easily done by the user querying `Geometry.fxyz`, but some simple functionality could be cool to have.

Yes, this would be ideal. I don't think this functionality should go in `sort`.

**Comment by tfrederiksen** [comment]
You are right, a `move_inside_cell`-type function is different from `sort` as it would not changing the atom ordering in the geometry. But the result could be different if called before or after a `sort`.

**Comment by zerothi** [comment]
I'll close this as it is tracked in #197
