### ISSUE TITLE
States shape and outer product

### ISSUE THREAD

**Issue by bfocassio** [zerothi/sisl#193]
I'm trying to undestand the shapes of the eigenstates of a Hamiltonian. I may be missing something very basic.

1.
For example, I have a Hamiltonian H whose shape is (2800,25200,9) , i.e., 2800 orbitals on the principal cell interacting with 25200 other orbitals from the auxiliary cell and each matrix element has 9 components, i.e., 8 from NC/SOC elements and the last is the overlap, is that right ?

Then one can obtain the eigenstates using something like:

`states = H.eigenstate(k=(0,0,0))`

with shape (5600,5600). I don't understand why I get this shape. Could you elaborate on that ?

2.
Then I'm training to get the outer product of the occupied states, which I'm calling P, to compute something like: P * s_z * P

I can compute P by simply doing:

`P = states.outer(occupied_states_index)`

P itself has a shape (5600,5600), how should I write s_z  ? to perform the multiplication above.

**Version details**
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
0.9.8
13a327bd8e27d689f119bafdf38519bab7f6e0f6

**Comment by zerothi** [comment]
1. The size of `eigenstate` is defined by the number of orbitals in your system. In your case 2800. But you also use SOC. Which means each orbital has a spin-box of size 2x2. This doubles the total size and your final eigenstate spectrum is then 2800 * 2.

2. You mean you want to do `<psi | psi >` for all `psi IN O`  where `O` is the occupied space? Or? I don't fully follow what you want to achieve?
If you want to only perform an action for a subset of the states, then you should do something like this:

        eigenstate = H.eigenstate()
        occ = eigenstate.occupation()
        occupied = (occ > 0.5).nonzero()[0]
        eig_occupied = eigenstate.sub(occupied)
        P = eig_occupied.outer()

    Is this what you want?

**Comment by bfocassio** [comment]
Ok, that's exactly what I was trying to achieve. Thank you
