### ISSUE TITLE
Changing boundary conditions of a periodic model

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#200]
Also, is there some way to open the boundary conditions (BC) of a periodic model (similar to the cut_piece of pythTB)?

See last request by #198

**Comment by zerothi** [comment]
@bfocassio

This should be trivially accomplished using this:
```python
graphene = sisl.geom.graphene()
H = sisl.Hamiltonian(graphene)
H.construct([(0.1, 1.44), (0, -2.7)])
H10a = H.tile(10, 0)
H10a20b = H10a.tile(20, 1)
# Remove PBC along 1st lattice vector
H10a20b.set_nsc(a=1)
```
I think this is what you mean?

**Comment by bfocassio** [comment]
Yes, it is, thank you very much
