### ISSUE TITLE
fdfSile.read_grid not working

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#208]
I think in some recent update something was changed in how the paths are managed and now the `read_grid` method does not work because it is trying to sum the directory path (which is a `PosixPath` object) with the name (which is a string). Passing the name as a Path does not work either because at some point the `lower()` method is applied on the name.

**Code snippet that reproduces the problem:**
```python
import sisl
fdf_sile = sisl.get_sile("Some fdf file")

fdf_sile.read_grid("TotalPotential")
```

**Comment by zerothi** [comment]
Probably this is related to the update to py 3,lots of file handling was changed but not I guess not everything is tested....
