### ISSUE TITLE
Writing a matrix for state.expectation()

### ISSUE THREAD

**Issue by bfocassio** [zerothi/sisl#209]
Nick, could you give us an example of how to write a matrix M in correct basis for computing using the state.expectation(M) and other stuff?

For example, if one want to compute the spin moment, how should one write s_z, s_x and s_y in the eigenstates basis ? (I do know that sisl already has a method for computing the spin moment, but this should be a simple example)

My first try with s_z was to do something like:

|+> += < state | +> * | state > and |-> += < state | -> * | state >

for each eigenstate and them s_z would be like:

sz = (+1) * |+><+| + (-1) * |-><-|

that is,

```
plus = np.zeros((eigenstate.shape[1],1),dtype=eigenstate.dtype)
minus = np.zeros((eigenstate.shape[1],1),dtype=eigenstate.dtype)

for i in range(len(eigenstate)):
    plus += np.dot(eigenstate.state[i].conj().reshape(-1,2),[1.,0.]).sum() * eigenstate.state[i].reshape(-1,1)
    minus += np.dot(eigenstate.state[i].conj().reshape(-1,2),[0.,1.]).sum() * eigenstate.state[i].reshape(-1,1)

sz = np.outer(plus.conj().ravel() * 1.,plus.ravel())
sz += np.outer(minus.conj().ravel() * -1.,minus.ravel())
```

But this product <state|+> confuses me because of the different shapes of |state> and |+>

**Comment by zerothi** [comment]
Thanks for the question, sorry for the late reply.

Calculating the expectation value requires you to create the correct input matrix.
For the Pauli-Z matrix you need all diagonals to be `[[1, 0], [0, -1]]`.  
It will look something like this:
```python
from scipy.linalg import block_diag
H = Hamiltonian(...)
SZ = block_diag(*([H.spin.Z] * H.no))
# check out how SZ looks to get an idea
H.eigenstate().expectation(SZ)
```
And this should give the same as `H.eigenstate().spin_moment()[:, 2]` :)

I hope this clarifies how to use `expectation`?

Note the above will only work for non-collinear and spin-orbit calculations.

**Comment by bfocassio** [comment]
That's exactly what I was looking for.

Thanks.
