### ISSUE TITLE
Supervisable objects

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#213]
This might sound stupid at first. But I think it would be a very nice thing to have as a tool to be used.

Why?
----
I didn't really understand how Nick was able to make things like

```python 
BrillouinZone.asaverage().method(...)
```

 work. Today I needed a similar thing for the visualization module and I took the time to read through all the code and I finally understood it. I really enjoyed understanding how does he get the desired functionality :). 

However, there are two things I'd like to discuss here:

- **It would be cool to have this functionality in general**, so that we (in this case, I) don't need to build it each time we need it.
- It is confusing that when you try to **retrieve an attribute** from the brillouinzone object **you get the object itself** instead of the attribute. For example:
```python
import sisl

geom = sisl.Geometry([[0,0,0]])
H = sisl.Hamiltonian(geom)
bz = sisl.BandStructure(H, [[0,0,0], [0,0,1]], 2)
print(bz.H)
```
prints the band structure, not the Hamiltonian. This really pissed me off because I didn't understand anything. Now I understand why it happens, but still I believe it can be confusing.

**Note:** I know that `bz.H` is not a target of this functionality, so this specific problem could be solved by checking that `bz.H` is not callable in `BrillouinZone.__getattr__()`, but still I would like to get the actual method when I ask for `bz.eigenstate`, for example.

Therefore
-----
I'd like to propose the following:

Instead of returning the object (brillouin zone), when a method is requested, return a "`SupervisedMethod`", which is basically an object that **looks exactly like the method, but runs anything else**.

```python
class SupervisedMethod:
    
    def __init__(self, method, really_executing):
        
        self.method = method
        self.really_executing = really_executing
        
    def __call__(self):

        return self.really_executing()
    
    # Everything below is just to make it look like we "really have the method".
    def __getattribute__(self, attr):
        
        real_getattr = object.__getattribute__
        
        if attr not in ["method", "really_executing", "__call__", "__init__"]:
            return real_getattr(self.method, attr)
        else:
            return real_getattr(self, attr)
    
    def __repr__(self):
        return self.method.__repr__()
```

**But what is this `self.really_executing` thing?**. It could be anything, but for our use case is what the class decides that needs to be done. This is the base `Supervisable` class (automatically supervises all method calls):

```python
class Supervisable:
    
    def __init__(self, obj=None):
        # It will not have any effect when the object is supervisable by class inheritance,
        # But it will allow us to make arbitrary objects supervisable
        self.obj = obj or self
    
    def __getattribute__(self, attr):
        
        real_getattr = object.__getattribute__
        
        obj = real_getattr(self, "obj")
        val = real_getattr(obj, attr) if attr != "obj" else obj
        
        # We will only supervise methods (but not the double underscore ones)
        if attr[0:2] == "__":
            return val
        elif callable(val):
            # If the desired attribute is a method, we return a supervised method
            # that will actually run whatever the __supervise__ method wants
            # Note that this will be different depending on the current state of the object
            # THAT'S THE MAIN POINT OF THIS IMPLEMENTATION
            return SupervisedMethod(val, real_getattr(self, "__supervise__")(val))
        else:
            return val
    
    def __supervise__(self, method):
        # Returns the actual function that the supervised method will run
        return method
    
    def _remove_supervision(self):
        # Only works if the object has been made supervisable.
        # (Not if it is supervisable because of class inheritance)
        return self.obj
```

Then, there are two ways to use this:
### Using inheritance
```python
class A(Supervisable):
    
    def do_something(self):
        print("DONE")

a = A()
a.do_something
```
Note that `a.do_something` looks exactly as the user would expect, but it's actually a `SupervisedMethod`. If you run it now, you will not see anything unexpected, because the default supervision is to simply run the method. But, you can change that whenever you want:

Having a "supervisor function" like:
```python
def withlog(self, method):
    def logged_method(*args, **kwargs):
        print(f"Running {method.__name__} with args {args} and kwargs {kwargs}")
        return method(*args, **kwargs)
    return logged_method
```
You could log all method calls by doing:
```python
from types import MethodType
setattr(a, "__supervise__", MethodType(withlog, a))

# To check it works
a.do_something()
```
### Making an arbitrary object supervisable

This is the most relevant way of doing it for the case of the brillouin zone. On `set_parent`, we could **make the parent supervisable**. Methods like `asaverage()` would alter `parent.__supervise__` to make the parent methods do what is needed. Note that this has the advantage that if you store, for example, `bz.asaverage().eigenstate`, the method will forever have the "asaverage" behavior, because it will not refer to the brillouinzone object when it wants to run as it does now. Actually I believe that right now if you were to store this and then use other methods like `bz.eigh()` you wouldn't even be running `eigenstate` by the time you called the stored method (I haven't tried, but that's what I understood by reading the code).

This is how it would work:
```python
class B:
    
    def do_something(self):
        print("DONE")
b = B()
b.do_something() # Is not supervised

# Make b supervisable
b = Supervisable(b)
setattr(b, "__supervise__", MethodType(withlog, b))
b.do_something() # Now it is being supervised
```

Let me know what do you think of this concept! Even if it is not implemented in this specific way, I would like to somehow have a general way to implement the behavior if you think it's worth it, as I stated at the beggining.

Cheers!

**Comment by zerothi** [comment]
Thanks, this is not a bad idea. I need to spend some time on figuring out the implications of this ;)
For instance if this supervision could be extended in the way I want the functionality of `BrillouinZone`.

A quick question though, couldn't you do with a decorator instead of `SupervisedMethod`? I.e. use `functools.wraps` and then return a decorated function? I am a bit worried the `__getattribute__` would be quite heavy if you call this method 10000 times?
Generally I want to keep the performance, or even get it work faster. I spent quite some time on figuring out how to retain good performance while retaining the flexibility of the `BZ.as*()` functions. In particular the way I wrap additional keywords was quite tricky since those handlers would have to be called on every execution. 

(you put me on work overload ;), thanks for that :1st_place_medal: )

**Comment by pfebrer96** [comment]
> A quick question though, couldn't you do with a decorator instead of SupervisedMethod?

Yes definitely, I just wanted to use `SupervisedMethod` to "replicate" the method so that things like `print(method)` or `help(method)` give the output that the user expects (i.e. helpful info about the method). But maybe it is unnecessary. Or does `functools.wraps` do this exact thing?

> Generally I want to keep the performance, or even get it work faster.

Out of curiosity, I implemented a "Supervising brillouin zone" to compare it with the actual implementation. This is what I got by testing it in a system with 100 atoms:

### Supervised method

bz.asaverage()
283 ns ± 1.21 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

bz.eigh
2.11 µs ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

call
825 ms ± 13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### Wrapper

bz.asaverage()
280 ns ± 1.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

bz.eigh
1.9 µs ± 6.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

call
838 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### Actual

bz.asaverage()
304 ns ± 1.42 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

bz.eigh
410 ns ± 2.44 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

call
855 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

So, it seems obvious that **retrieving the method is much slower** in the general supervised approach. However, there are some things that I would like to point out:

- The actual call is much more time consuming. Even for the most simple hamiltonian (1 H atom) and only 2 points of the brillouin zone, it takes about 120 µs in my laptop. That is 50 times more than the object retrieval.
- The comparison is not totally fair really, because there are some things hidden in the actual implementation's call process. The last queried attribute is retrieved (`self._bz_get_func()`), the wrapping function needs to be obtained (`getattr(self, '_bz_call')`). This takes about the same time as `bz.eigh`. So the difference it's less than it seems.

I guess my point is: **Retrieving and running the method 1 milion times will be 1s slower**. I don't know if anyone will be bothered by that. It is even less significant if you take into account that sisl aims for calculations of big sistems. So, by the time you can run 1 milion big systems in a reasonable time, I think this won't be a problem. For example, **my laptop would take about 10 days to run the 100 atoms system 1 milion times**. I won't get angry if it takes one more second. In exchange for that second during your crazy simulation experiment, you get a less confusing way of interacting with the methods of the brillouin zone object.

PS: I don't know if this happened to anyone else, but when I started using sisl  I was a bit confused by:

```python
bz.asaverage()
```

because I thought it was actually modifying the brillouin zone in some way. Is there any reason you chose it over:

```python
bz.eigh(asaverage=True)
# or
bz.asaverage = True
# or
bz.return_method = "average"
# or
bz.set_return_method("average")
```

Thanks!

**Comment by zerothi** [comment]
Could you perhaps do a pull request so I can check it out?

**Comment by zerothi** [comment]
> > A quick question though, couldn't you do with a decorator instead of SupervisedMethod?
> 
> Yes definitely, I just wanted to use `SupervisedMethod` to "replicate" the method so that things like `print(method)` or `help(method)` give the output that the user expects (i.e. helpful info about the method). But maybe it is unnecessary. Or does `functools.wraps` do this exact thing?

Yes, this is exactly what `functools.wraps` does ;)


> PS: I don't know if this happened to anyone else, but when I started using sisl I was a bit confused by:
> 
> ```python
> bz.asaverage()
> ```
> 
> because I thought it was actually modifying the brillouin zone in some way. Is there any reason you chose it over:
> 
> ```python
> bz.eigh(asaverage=True)
> # or
> bz.asaverage = True
> # or
> bz.return_method = "average"
> # or
> bz.set_return_method("average")
> ```

Hmm, I don't particularly like any of these. ;)

Generally I was also against _patching_ the subsequent methods by allowing `wrap`, `eta` etc. as keyword arguments to methods that never did this prior. Effectively it becomes a mess...
I think your supervised method would allow a more general approach (good) and probably also leverage the need to patch arguments (this needs some testing ;))

This is really a dispatch functionality, so I guess this would be `bz.dispatcher(method)` where the `Supervisable` implements the `dispatcher` method. Actually I think the class should be called a `Dispatcher` which has a clearer intent ;)

**Comment by pfebrer96** [comment]
> This is really a dispatch functionality, so I guess this would be bz.dispatcher(method) where the Supervisable implements the dispatcher method. Actually I think the class should be called a Dispatcher which has a clearer intent ;)

Didn't see this, oops. Well, you can change it to whatever you want. But yes that's true, even in my implementation `__supervise__` should be called `__dispatch__` . When you proposed `bz.dispatcher(method)` a thousand different possibilities came to my mind, so I'm not sure I know how do you want the workflow to be exactly :)

**Comment by pfebrer96** [comment]
One thing I do see though, is that `Dispatcher` would be the class that is "supervising", let's say. For example in this case (`BrillouinZone`) is the dispatcher, who dispatches methods from another class (`Hamiltonian`).

With `Supervisable`, or `Dispatchable`, it was the other way around. Some class allows their methods to be dispatched or supervised. The only thing I miss about the `Dispatcher` approach is that `Supervisable` allows the class to supervise itself/dispatch its own methods. I would like to have this functionality, so if you want to go with `Dispatcher` can you keep it in mind? Although maybe it is as simple as creating a dispatcher and then binding the object to the dispatcher.

**Comment by zerothi** [comment]
> ... create different dispatchers to have different functionalities (`Logger`, `Debugger`, `Timer`, or more experimental ones like `EventDispatcher` #196, `Saturator` so that you don't need to worry about saturating after each geometry modification, `GroupManager` #167 ... hahaha I'm just thinking out loud, but would be fun to explore and let users build their own custom dispatchers).

Exactly my point, ;) I really want to use it for other things as well, ;)

**Comment by jonaslb** [comment]
So I didn't go through all your discussions, but if you are changing this detail about brillouinzones anyway, I just want to point out my own personal gripe with them: `bz.asaverage() is bz.assum()` (and likewise with the other 'as'-methods). 

I think these methods should return new objects that wrap the bz rather than modify it in-place. This might also make the code clearer with the actual k-point collection and generation being separate from the 'calculator' part.

**Comment by zerothi** [comment]
@jonaslb agreed, this would be solved using something like this!

**Comment by pfebrer96** [comment]
Just to make my mind clear about it: are you thinking of something like this:

```python

class Dispatcher:
      ....
class AsAverageDispatcher(Dispatcher):
      ....

class BrillouinZone:
      ....
      def asaverage(self):
              return AsAverageDispatcher(iter_over={"k": self.k}, ...)

```

or what is the workflow that you have in mind?

**Comment by jonaslb** [comment]
Something like that, yes :)

**Comment by zerothi** [comment]
I'll close this as #215 superseeds it.
Thanks for the initial implementation!
