### ISSUE TITLE
Infinite loop in H.fermi_level

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#222]
In my ignorance, I had a `Hamiltonian` and I wanted to calculate its fermi level. I thought, well that's easy, just `H.fermi_level()`. But then my laptop started to heat up and hyperventilate. And I was like, man, this must be an expensive calculation.

However, it was just that the `_Ef` function was running infinitely because `min_Ef` and `max_Ef` were the same. This happened because `q` (which I initially thought was the net charge) needs to be set to the number of electrons in the system. Since I was not providing a q, it was taken from my geometry q0 attribute, which was set to 0.

I have two questions:
- If `q` is the number of electrons, does it make sense to check beforehand if the user is asking for something impossible? And specially if it's 0, assume that is the sum of all atoms Z?
- Wouldn't it be more useful that `q` was the net charge? So that the user does not need to know how many electrons are there in their system.

**edit**: I realised that what I was proposing does not make sense because you are not taking into consideration all electrons necessarily, sorry. Maybe the check that I proposed in the next comment is useful?

**Comment by pfebrer96** [comment]
Now that I found out what to pass to `q`, I encountered another situation that results in an infinite loop. In my case, the default qtolerance is impossible to reach because of `float` precision limits. It gets to a point where `Ef = (min_Ef + max_Ef) * 0.5` sets the same value in each iteration (`Ef = max_Ef`). I know I can change the tolerance, but all in all, do you think is worth to check if the loop is just stuck infinitely to break it so that this doesn't happen to other users?

**Comment by zerothi** [comment]
I have now added a check for `q==0`.

> Now that I found out what to pass to `q`, I encountered another situation that results in an infinite loop. In my case, the default qtolerance is impossible to reach because of `float` precision limits. It gets to a point where `Ef = (min_Ef + max_Ef) * 0.5` sets the same value in each iteration (`Ef = max_Ef`). I know I can change the tolerance, but all in all, do you think is worth to check if the loop is just stuck infinitely to break it so that this doesn't happen to other users?

Hmm.. How could this be? Are you having more than 1e6 electrons?

I have now changed `while True` to `while min_Ef < max_Ef` which still has problems for small differences. But I guess it would be a bit better.

**Comment by zerothi** [comment]
@pfebrer96 could you close this if it is fixed? Thanks!

**Comment by pfebrer96** [comment]
> Hmm.. How could this be? Are you having more than 1e6 electrons?

No, I have just 172 electrons. Does the precision that you need on the fermi level to get below `q_tol` only depend on the number of electrons? If i go below q_tol=1e-7 I get an infinite loop for the reason that I mentioned.

Here is the pickled hamiltonian if you want to check it yourself:
[infiniteLoopHamiltonian.zip](https://github.com/zerothi/sisl/files/4649937/infiniteLoopHamiltonian.zip)

> could you close this if it is fixed? Thanks!
Just two things, if you don't mind:
- Would it make sense that q accepted a dict stating the charge of each atom (and maybe an extra_q key or something like that)?

```python
H.fermi_level(q={"N": 5, "C":4, "H": 1, "extra_q": 1})

# And q is calculated like
np.sum([q[H.geom.atom[at].tag] for at in H.geom]) + q["extra_q"]

# Or maybe
H.fermi_level(q=1, q0={"N": 5, "C":4, "H": 1})

# And q is calculated like
if q0 is not None:
    q += np.sum([q0[H.geom.atom[at].tag] for at in H.geom])
```

> I have now added a check for q==0

- Is it worth it also to check for `q > len(eig)`?

**Comment by zerothi** [comment]
> > Hmm.. How could this be? Are you having more than 1e6 electrons?
> 
> No, I have just 172 electrons. Does the precision that you need on the fermi level to get below `q_tol` only depend on the number of electrons? If i go below q_tol=1e-7 I get an infinite loop for the reason that I mentioned.

How many k-points are you using?

> Here is the pickled hamiltonian if you want to check it yourself:
> [infiniteLoopHamiltonian.zip](https://github.com/zerothi/sisl/files/4649937/infiniteLoopHamiltonian.zip)
> 
> > could you close this if it is fixed? Thanks!
> 
> Just two things, if you don't mind:
> 
> * Would it make sense that q accepted a dict stating the charge of each atom (and maybe an extra_q key or something like that)?
> 
> ```python
> H.fermi_level(q={"N": 5, "C":4, "H": 1, "extra_q": 1})
> 
> # And q is calculated like
> np.sum([q[H.geom.atom[at].tag] for at in H.geom]) + q["extra_q"]
> 
> # Or maybe
> H.fermi_level(q=1, q0={"N": 5, "C":4, "H": 1})
> 
> # And q is calculated like
> if q0 is not None:
>     q += np.sum([q0[H.geom.atom[at].tag] for at in H.geom])
> ```

I don't think this makes sense, it seems complicated and not necessary. You should change the atoms with a charge to control this. Or just pass the correct `q` :)
```python
N = si.Atom(7, q0=5)
C = si.Atom(6, q0=4)
H = si.Atom(1, q0=1)
# or
Z = geometry.atoms.Z
q = (Z == 7).sum() * 5 + (Z == 6).sum() * 4 + (Z == 1).sum()
```
and then use these in the geometry. Note you can easily change some of the atoms in the geometry.

> > I have now added a check for q==0
> 
> * Is it worth it also to check for `q > len(eig)`?

Yeah, good idea.

**Comment by pfebrer96** [comment]
> I don't think this makes sense, it seems complicated and not necessary. You should change the atoms with a charge to control this.

Ah ok, I didn't know you could do that :+1: 

> How many k-points are you using?

The default, which is just the Gamma point, right?

**Comment by zerothi** [comment]
Ok, I see now why. I have added a new commit which fixes it ;)

Thanks!
