### ISSUE TITLE
How to get the COOP curves

### ISSUE THREAD

**Issue by zhuolingjiang** [zerothi/sisl#223]
I want to extract the COOP curves from the siesta.TBT.nc.
 I try to use the command sdata to achieve this goal.  
sdata   siesta.TBT.nc  --atom 46 --atom_coop Left --out  coop.dat
But it failed. Could you tell me how to do?

**Comment by zerothi** [comment]
The COOP values are sparse matrices, so you would want to checkout the COOP between different orbitals/atoms.

See the documentation why these are always sparse matrices: http://zerothi.github.io/sisl/docs/latest/api-generated/sisl.io.tbtrans.tbtncSileTBtrans.html#sisl.io.tbtrans.tbtncSileTBtrans.orbital_COOP

**Comment by zerothi** [comment]
I.e. if you want to analyse COOP data, you should create a script
```python
import sisl as si

tbt = si.get_sile('siesta.TBT.nc')
COOP = tbt.atom_ACOOP("Left", E=0.1)
```
Then you have a sparse matrix.

**Comment by zhuolingjiang** [comment]
Thank you very much!
I will check that and hope to get useful data from the sparse matrix.

**Comment by zerothi** [comment]
Ok, I'll close this for now. If you have further questions, please don't hesitate to ask!
