### ISSUE TITLE
Expanding density matrix file form unit cell to super cell

### ISSUE THREAD

**Issue by yuvamb** [zerothi/sisl#232]
**Describe the feature**
I am running a calculation SIESTA but somehow it's not converging as it's a very big system consisting of 720 atoms.
I am planning if I could use the DM file form the converged unit cell which has 20 atoms, for my supercell.
Is there a way to expand my DM? Can sisl perform this?

**Comment by jonaslb** [comment]
You could do it like this:

```python
# Load the density matrix
dm = si.get_sile("my_unit_density_matrix.DM").read_density_matrix()
# Tile the density matrix 3 times along a, then along b and then 4 times along c
# Of course I don't know how your system is set up. But this is one way.
dm_tiled = dm.tile(3, 0).tile(3, 1).tile(4, 2)
# Write the new DM
dm_tiled.write("my_super_density_matrix.DM")
```

Note that the ordering of your atoms may be different -- of course it needs to match the actual structure you're using. To change it, you can either reorder the tiling operations, use repeat instead, or use `dm.sub` to reorder your atoms however you need. These operations are all very fast in sisl.

**Comment by zerothi** [comment]
@yuvamb what @jonaslb suggested is the correct way, did it work?

I'll close this now, if you still have problems, please post/re-open again! :)
