### ISSUE TITLE
Read the  data in  the *.LDOS file  using SISL.

### ISSUE THREAD

**Issue by lindasheila** [zerothi/sisl#240]
**Describe the issue**
3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
0.10.0
ed02b72d44a47c475a253874e51683ed6a6cc169

Dear SISL users,

the title says it all!

Thank you in advance,
Linda

**Comment by zerothi** [comment]
The ldos file is supported? What did you try? And are you sure you are using 0.10.0?

**Comment by lindasheila** [comment]
Dear Nick,
Sorry I meant how  to read the  data  in file.LDOS using SISL?
Thank you!Linda

    Le lundi 13 juillet 2020 à 11:13:57 UTC+2, Nick R. Papior <notifications@github.com> a écrit :  
 
 


The ldos file is supported? What did you try? And are you sure you are using 0.10.0?

**Comment by zerothi** [comment]
You should do like any other file

```python 
get_sile('siesta.LDOS').read_grid()
```

**Comment by lindasheila** [comment]
Dear Nick,
Thank you for your answer!But my question is more about how to read the data in the file (Eigenvalues(if there are), LDOS, position).
Thank you!Linda
    Le lundi 13 juillet 2020 à 18:30:56 UTC+2, Nick R. Papior <notifications@github.com> a écrit :  
 
 


You should do like any other file
get_sile('siesta.LDOS').read_grid()

**Comment by zerothi** [comment]
The ldos file only contains the DOS on the real space grid. And he real space grid may easily be interpreted using the Grid class defined in sisl.

**Comment by zerothi** [comment]
I'll close this since there hasn't been any activity for a fortnight.
