### ISSUE TITLE
Avoid importing categories for simple use cases

### ISSUE THREAD

**Issue by pfebrer96** [zerothi/sisl#241]
I was thinking that:

```python
import sisl

geom = sisl.geom.graphene()
geom.sub(Z=6)
```

would be a great API, instead of:

```python
import sisl
from sisl.geom.category import AtomZ

geom = sisl.geom.graphene()
geom.sub(AtomZ(6))
```

However, I understand that this would add a bit more complexity to `_sanitize_atoms` and specially the functions that accept the `atoms` argument, as they would have to accept kwargs.

Another way of passing this would be as a dict (that `_sanitize_atoms` would parse because it is aware of which category is represented by each keyword, and the value would be just what goes into `__init__`, so it can be a range for example):

```python
import sisl

geom = sisl.geom.graphene()
geom.sub({"Z": 6})
```

This is a bit uglier, but it only needs modification of `_sanitize_atoms` and therefore would be automatically applied in all methods that accept `atoms`, and it may still be useful. Maybe you have already thought about this, I just want to know your opinion.

**Comment by pfebrer96** [comment]
I noticed that this is already implemented in `AtomCategory.kw`, so `_sanitize_atoms` would only need to pass the dictionary to this static method, right?

**Comment by zerothi** [comment]
Good idea. I have now added the possibility of passing `{"Z":6}` to `atoms` arguments that are redirected to `_sanitize_atoms`. I think this is the best approach.

Thanks!
