### ISSUE TITLE
QUESTION ABOUT SGRID IN SISL

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#245]
**Describe the feature**
Hello 
In the sgrid manual we can find the difference between 2 grids. My question is that also applicable for multiple grids which is suitable to analyze how the actual charge distribution between 2D materials by subtracting the 2D DELTARHO file with the individual layers.  My question:  Is the following command correct:

sgrid DeltaRho.grid.nc --geometry zeroPG.XV --diff P.grid.nc --geometry zeroP.XV --diff G.grid.nc --geometry zeroG.XV diff.cube

where i intend to find the deltarho difference between the 2D phosphorene/Graphene unitcell and each sheet separately each after a siesta run having their own XV file.
IS THAT CORRECT?
THANK YOU AND LOOKING FORWARD TO YOUR REPLY!

**Comment by zerothi** [comment]
Did you try? :)

E.g. if you do:
```
sgrid A.grid.nc --diff A.grid.nc --diff A.grid.nc --out t.cube
```
you would get the negative of `A.grid.nc`.
I have just tried and it works.

I'll close this. :)
Thanks.

**Comment by el-abed** [comment]
It worked and sorry for the spam :(
I do apologise because I was not sure if it would be read in the closed issue.
I got the following info. Should I worry about it?
**info:0: SislInfo: gridncSileSiesta.read_grid cannot determine the units of the grid. The units may not be in sisl units.**

**Comment by zerothi** [comment]
> It worked and sorry for the spam :(
> I do apologise because I was not sure if it would be read in the closed issue.
> I got the following info. Should I worry about it?
> **info:0: SislInfo: gridncSileSiesta.read_grid cannot determine the units of the grid. The units may not be in sisl units.**

Yeah this is a problem since it does not know the units. Instead you should rename the files as `P.DeltaRho.grid.nc` which then works. Alternatively keep the `DeltaRho.grid.nc` files in separate folders and do `--diff <>/DeltaRho.grid.nc` for each of them.

**Comment by el-abed** [comment]
Just to confirm the first suggestion worked by using this:
 sgrid PG.DeltaRho.grid.nc --geometry zeroPG.XV --diff P.DeltaRho.grid.nc --diff G.DeltaRho.grid.nc diffn.cube

Really appreciate your time and thoughts within such short notice! Thank you :)

**Comment by zerothi** [comment]
Ok, great.

**Comment by el-abed** [comment]
Just quick comment, both results did not show any slight changes. But as always one would rather have no errors :)
Again thank you Nick really appreciate your time and help!
