### ISSUE TITLE
How to properly utilise sisl to extract information from potential

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#259]
Good day all,
I was wondering in the sisl manual it focuses on extracting the information from `RHO.grid.nc` files to produce cube files in the following format:
```bash
sgrid PG.DeltaRho.grid.nc --geometry zeroPG.XV --diff P.DeltaRho.grid.nc --diff G.DeltaRho.grid.nc diffn.cube
```

My questions are as follow:
1-  Is there a similar format for `Electrostatic.grid.nc`, `TotalPotential.grid.nc`, and `TotalCharge.grid.nc` files?
2- If i am interested only in one direction such as z-axis, how command should I use?
3- What available output formats can be done and how?

Thank you and looking forward to your reply.
EL-abed

**Comment by zerothi** [comment]
Hi,

1. The `sgrid` command works for *any* grid files, the command is exactly the same.
2. Currently, I haven't interfaced the grid to write out tables for 1D data (e.g. if you average/sum over x, y directions). This is in the works.
3. As of now, only `xsf` and `cube` files are supported. The file-format is determined from the file-suffix
```bash
sgrid Rho.grid.nc rho.cube # write a cube file
sgrid Rho.grid.nc rho.xsf # write a xsf file
```

**Comment by zerothi** [comment]
Regarding 2., I have now added the possibility of writing the 1D data to a data file. It should work with the latest commit of sisl.

**Comment by el-abed** [comment]
Really looking forward Nick. May I ask when is the expected release?

**Comment by zerothi** [comment]
> Really looking forward Nick. May I ask when is the expected release?

You can just download this repository and install it like the regular sisl version :) That would be the easiest.

You could follow these instructions: http://zerothi.github.io/sisl/docs/latest/installation.html#development-version to install the development version :)

**Comment by el-abed** [comment]
Oh ! I did not know that, i thought sisl like siesta we have to wait the later versions. Thank you very much!

**Comment by zerothi** [comment]
@el-abed could you confirm whether it is working now? If it does, please close this issue (otherwise I'll close in a week or so).

**Comment by el-abed** [comment]
Hello nick,
I finally downloaded using the following command
pip3 install -v --no-binary :all: --user git+https://github.com/zerothi/sisl.git

But it seems there are multiple folders: pip-5y0u06ab-build  pip-si96evx4-build pip-build-i3a5hujh

1- May I ask what is the difference between them?
2- Also how can I make sure I have the latest update including the 1D data file siutation?
3- Speaking of 1 D data file, what is the command to extract for example the potential vs z ? 

Thank you Nick and looking forward to your reply.
EL-abed

**Comment by zerothi** [comment]
1. The pip command should install in a folder, I guess these folders are just temporary folders. I have no clue what these folders are. But I don't think they are useful.
2. If you just did the above, then you are pretty sure it works, otherwise you'll just see an error.
3. You have to do `sgrid Rho.grid.nc --average 0 --average 1 --out rho_z.dat`, to average the density on the x, y plane.

**Comment by el-abed** [comment]
The installation is successful where the aforementioned folders have sisl.
Concerning 3 when you say average on x,y plane it is equivalent of density as a function of z right?

**Comment by zerothi** [comment]
3. Yes.

**Comment by el-abed** [comment]
Beautiful. Thank you very much Nick :) 
Really appreciate the quick replies. Do you mind if I just keep it open just to do some tests? Hopefully by tomorrow i should be able to make sure everything is set.

**Comment by zerothi** [comment]
sure :)

**Comment by el-abed** [comment]
I can confirm after a long day fixing the installation that the command in the latest sisl version:

sgrid Rho.grid.nc --average 0 --average 1 --out rho_z.dat

IS WORKING
THANK YOU VERY MUCH NICK! I WILL CLOSE IT NOW

**Comment by el-abed** [comment]
Sorry to bother again Nick. I was wondering what can we extract from the elements files ion.nc ?
Just curious becayse  in the latest siesta manual i saw only that basis, KB projector, and other information is read. So other information like what? PDOS? DOS? Potential? Thank you and looking forward to your reply

**Comment by zerothi** [comment]
Please do not re-open an old question with new questions....
