### ISSUE TITLE
Using a wrong `isc` parameter in `Geometry.close_sc` should raise an informative error

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#269]
I thought the code below should have worked, but it raised a `ValueError` that I didn't understand at first.
After much confusion I realized that `isc` has to be a 3-vector of indices, it isn't just the index of the supercell.
The docs do say that `isc` is array-like, but I thought this was to enable using multiple supercells.
So I think the docs should be more explicit, but also the error should probably be more informative?

**Reproducable code**
```python
si.geom.graphene().close_sc(0, isc=0, R=1.6)
```

The traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-783c04b6248e> in <module>
----> 1 si.geom.graphene().close_sc(0, isc=0, R=1.6)

~/git/sisl/sisl/geometry.py in close_sc(self, xyz_ia, isc, R, atoms, atoms_xyz, ret_xyz, ret_rij)
   2874         # Get atomic coordinate in principal cell
   2875         if atoms_xyz is None:
-> 2876             dxa = self.axyz(atoms) + foff.reshape(1, 3)
   2877         else:
   2878             # For extremely large systems re-using the

ValueError: cannot reshape array of size 9 into shape (1,3)
```

**Version details**
sisl master

**Comment by zerothi** [comment]
As for the error, that is a `numpy` error, so I can't change that.

What about this:
```python
"""
 isc : (3,), optional
            The super-cell which the coordinates are checked in. I.e. ``isc=[0, 0, 0]`` is the
            primary cell.
"""
```

**Comment by jonaslb** [comment]
That looks good :)

We could change the error by checking the shape of the passed `isc`, but maybe it'll be less relevant with this doc.

**Comment by zerothi** [comment]
> That looks good :)
Great!

> We could change the error by checking the shape of the passed `isc`, but maybe it'll be less relevant with this doc.
Yeah, I am partially against this to not clutter code with too many checks, but perhaps it may be needed later on... I'll adapt and commit.

**Comment by zerothi** [comment]
Let me note that the code will still error out due to other incompatibilities.
