### ISSUE TITLE
Atom tag and mass private attributes now?

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#276]
I have been changing atoms' tags regularly by using `atom.tag`. Of course I can use `atom._tag` instead, but the underscore, meaning private attribute, kind of says "dont do this". Instead I now have to manually create a new atom with all the kwargs manually, and then use `atoms.replace`? I think that is rather impractical, especially considering that there isn't really a reason to keep the tag private.

At least I understand the mass a little bit -- for DynamicalMatrix, changing atom mass will cause inconsistency with how it is scaled -- but I think that is a bit of a corner case. It should be more important not to make it too impractical if one *does* want to change the mass, imo.

**Comment by zerothi** [comment]
Yeah, it is to ensure that consistency is achieved.
To change atom tags, you could do:
```python
new = old.copy(tag="newtag")
```
(I think)

**Comment by jonaslb** [comment]
I mean, the inconsistency on DynMat is still there even if one uses public attributes and methods (atoms.replace), I think? And it's not at all there with `tag`?

**Comment by zerothi** [comment]
Yes, but it is easier to change things from internal methods (overriding `replace`) than allowing these kinds of things.

When things are changed directly, it is hard to track, we should encourage the use of the API to do this for people to allow _us_ to control the flow.

**Comment by zerothi** [comment]
I'll close this for now since I think changes to internal structures are better handled through API calls.
