### ISSUE TITLE
Using a2o with supercell atom indices modifies the input

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#280]
**Describe the bug**
`a2o` currently modifies its input if it is a supercell atom. I don't think this should happen?

**Reproducable code**
```python
>>> H.na
1060
>>> my_atoms = np.array([1060])
>>> H.a2o(my_atoms)
array([8388])
>>> my_atoms
array([0])
```

**Version details**
sisl master

**Comment by zerothi** [comment]
True, I'll fix this asap!
