### ISSUE TITLE
Creating automated wheels for sisl

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#281]
I think it would be very nice to publish precompiled wheels for sisl to reduce the installation time, the external dependencies (compilers and python-dev) and the amount of failed installations.

As a begginner with python, it was very strange to me that I could `pip install numpy` in seconds and without any extra dependecy in the system but `pip install sisl` would take ages and might fail if I didn't have everything perfectly setup. Now I understand that it's not magic, it's just that someone has precompiled it for me.

In my opinion, this would drag more users into sisl, as one of the excuses for not trying/using it is that it's hard to install.

If you agree, I would like to tackle this by following https://numpy.org/doc/stable/dev/releasing.html and creating a repo like https://github.com/MacPython/numpy-wheels.

**Comment by pfebrer** [comment]
Ok, after building the repo (https://github.com/pfebrer/sisl-wheels) and checking that it works I saw that you already have it implemented in conda :facepalm:. Is there a way to use what you build in `sisl-feedstock` to pypi?

**Comment by zerothi** [comment]
I completely agree that this would be nice.

When I started sisl, I tested this by creating wheels on my local machine. However, they were always rejected on the pip frame, so I just abandoned it for later times ;)

Thanks for taking this up! :)

As for conda. From what I have experienced throughout the conda-scheme, then I don't think that is a good way to create wheels, the conda scheme has its own build-mechanisms and I think what you are doing is the correct way of doing it. :)

Your sisl-wheels would be very nice, however, could you also create a thorough README.md for how to actually do it ;)

Do the numpy page recommend the infrastructure _in-code_ or in a separate branch?

**Comment by pfebrer** [comment]
> Do the numpy page recommend the infrastructure in-code or in a separate branch?

Numpy, scipy, pandas, matplotlib, etc they all use [multibuild](https://github.com/matthew-brett/multibuild/tree/ec386efaa9e6840b552d845dfc4d597f6b97a2b7), which recommends to set up a new repo (called *-wheels) that contains at least two submodules: the multibuild repo and your package.

Following their README, it is quite straightforward to set it up for linux and mac (tested the produced wheels in my laptop and my macbook and they both work). 

I've also gotten it to compile on windows, but there is the problem of `.dll` files not loading (same as https://github.com/zerothi/sisl/issues/244 I think) so it needs a bit of extra work. Scipy solves that with a `_distributor_init.py` file. They hold a dummy one in the scipy repo that is imported on `__init__.py`, and when they build for windows they replace it with https://github.com/MacPython/scipy-wheels/blob/master/_distributor_init.py.

I will add the README in `sisl-wheels`. If you could try to install from one of the wheels in the release there and see if it works that would be great :)

**Comment by zerothi** [comment]
> I will add the README in `sisl-wheels`. If you could try to install from one of the wheels in the release there and see if it works for you that would be great :)

Thanks for this! I will try this out.

**Comment by zerothi** [comment]
> Thanks for this! I will try this out.

Great, finally made this work!!!

Ok, so I suggest you transfer this project to my account, then I'll add you as maintainer.

I can't find a numpy-wheels repo, so how do they transfer the release files to the tagged release?

**Comment by pfebrer** [comment]
> Ok, so I suggest you transfer this project to my account, then I'll add you as maintainer.

Done!

> I can't find a numpy-wheels repo, so how do they transfer the release files to the tagged release?

https://github.com/MacPython/numpy-wheels :) They store the wheels in some anaconda storage though instead of the github releases.

> Great, finally made this work!!!

Great! The windows wheels don't work though, but I think still there's lots of users that can benefit from the linux and macOS wheels. We can try to fix this at some point.

**Comment by zerothi** [comment]
Ah, ok, a separate project.... :(

Since you transferred you are automatically contributor, and I think you have access, no?

**Comment by pfebrer** [comment]
I'm not sure, we will see when (if) I try to push something :) 

> Ah, ok, a separate project.... :(

Yes, apparently that project builds wheels for lots of python packages: numpy, scipy, pandas, netcdf, cython, matplotlib...

**Comment by zerothi** [comment]
I will work on this once I have adopted PEP 621.

**Comment by zerothi** [comment]
This is now fixed! Thanks @pfebrer
