### ISSUE TITLE
spgeom.eigsh with nonorthogonal basis

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#283]
When trying to use `spgeom.eigsh` with a non-orthogonal basis set, sisl will throw an error claiming this is unsupported.

However, [scipy *does* seem to support this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) (the `M` parameter), so I suppose it could be enabled in sisl as well.

Further, perhaps allowing the use of scipy's "shift-invert" parameters could be useful for finding eigenstates near the fermi energy (ie `sigma=0, which='SM'`). 

I haven't really tested it but I noticed it just now :)

**Comment by zerothi** [comment]
This is now fixed.

By the way, any `kwargs` not used in my `eigsh` are automatically passed to the `eigsh` method, so all options are available.
