### ISSUE TITLE
io.vasp OUTCAR: job_completed only updated if cpu_time() is called

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#287]
**property `job_completed` not updated in an intuitive way**
When reading a VASP OUTCAR the property `job_completed` is only updated if `cpu_time()` is first called. I guess this is not very intuitive from the user perspective. Calling `read_energy()` or `accuracy_reached()` has no effect.

**Reproducable code**
```python
>>> import sisl
>>> f = sisl.get_sile('OUTCAR')
>>> a = f.read_energy()
>>> b = f.accuracy_reached()
>>> print(f.job_completed)
False
>>> c = f.cpu_time()
>>> print(f.job_completed)
True
```

**Version details**
Run the below code and add to bug-report:
```python
>>> import sys
>>> print(sys.version)
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
>>> import sisl
>>> print(sisl.__version__)
0.10.0+228
>>> print(sisl.__git_revision__)
5276de5cac9ac065071fcc3370ae8c9133eb7a4c
```

**Comment by zerothi** [comment]
Absolutely true, I'll fix this and the same for siesta...

**Comment by zerothi** [comment]
Thanks, fixed now! Also, note that `out.job_completed` is changed to a function: `out.completed()`. I figure that we may use this for other things in the future, i.e. query SCF completed, or something similar.

**Comment by tfrederiksen** [comment]
Excellent!
