### ISSUE TITLE
Make viz.plotly with fewer dependencies:

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#292]
**Describe the issue**

This discussion was initiated [here](https://github.com/zerothi/sisl/commit/0bc8b72f5c3a8618c8e5c782725183dc43560903#r46192426)

I have a few more ideas that needs thought:

I agree that plotly plotting should be entirely decoupled from the flask environment (GUI).

However, we discussed what to do with the GUI and @pfebrer suggested to make that a separately installed package.

I now thought that perhaps it would make sense to make it loadable from the configuration directory?

Pro's/cons

**GUI as a package**
- :heavy_check_mark: Easy to install
- :heavy_check_mark: Easy dependency management
- :x: cannot have multiple versions (for double checking)
- :x: may be difficult to revert to older versions

**GUI as a configuration**
- :heavy_check_mark: Easy to maintain multiple versions
- :heavy_check_mark: Easy to switch between versions
- :x: A bit more difficult to install
- :heavy_check_mark:/:x: dependency management in between

What do you think @pfebrer about having it as a configuration?

**Comment by zerothi** [comment]
Once the dependencies are removed, lets take a look at the documentation!

**Comment by pfebrer** [comment]
I don't understand what does this mean exactly:

> I now thought that perhaps it would make sense to make it loadable from the configuration directory?

Could you elaborate please :) What is the configuration directory? Is it e.g. `~/.sisl` or is it something inside the `sisl` directory? And what does it mean loading it from there, how would it work?

Thanks!

**Comment by zerothi** [comment]
Remember we had `sisl/_environ` to accommodate environment variables read by sisl?

The idea was that the `SISL_CONFIGDIR` would host the layouts for the viz modules and other template files, if needed. So we could basically have the GUI stuff in a directory there (which is the default place to look for stuff) and then load it using `importlib` or similar?

It was just a thought whether you think this is more apt for a tool than a package?

**Comment by pfebrer** [comment]
Aah ok, so for a release, you would get the current version of the GUI and copy it in the config dir.

This is basically the same as having it inside the package, right? How could dependencies be handled in this case?

I think that there would be no problem with versions if in the `sisl_gui` package I specify the minimum sisl version supported. Or would it?

**Comment by zerothi** [comment]
> Aah ok, so for a release, you would get the current version of the GUI and copy it in the config dir.
Exactly.

> This is basically the same as having it inside the package, right? How could dependencies be handled in this case?
Yes and no. It causes some problems for system-wide installations since we have to install it *with* sisl. But it allows users to override the used GUI by using env-vars (which is nice).
 
> I think that there would be no problem with versions if in the `sisl_gui` package I specify the minimum `sisl` version supported. Or would it?

No, I think this is trivially handled since you have to load sisl at some point :)

**Comment by pfebrer** [comment]
I think it is quite common for extensions of a given python package to be a separate package called `packagename-*`. 

And it will make it simpler I believe. At the end, most problems will be solved with the sentence:

```
Please update sisl and sisl-gui to their latest versions and if it doesn't work let us know.
```

so I don't think there's such a need to be able to have multiple versions installed in the same environment. Don't you think?

**Comment by zerothi** [comment]
Ok, fair enough, lets separate them as two packages then :)

**Comment by zerothi** [comment]
Done
