### ISSUE TITLE
Fdf read geometry fails if no chemical labels block

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#294]
This line:
https://github.com/zerothi/sisl/blob/a5f88da58947cd3694d97cdcff85b11efb306b84/sisl/io/siesta/fdf.py#L1345

raises an error because `SileWarning` is not imported :)

**Comment by zerothi** [comment]
Thanks!

**Comment by pfebrer** [comment]
This kind of things would be detected by a static code analysis, maybe it would be worth it to add it to the testing workflow?

**Comment by zerothi** [comment]
Agreed. I had one at some point, but that was at the beginning when things hadn't settled, which would you recommend?

**Comment by pfebrer** [comment]
No idea, I haven't used any, sorry :sweat_smile:
