### ISSUE TITLE
sisl.viz.plotly building documentation

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#299]
@pfebrer

I still have a hard time building the documentation for plotly part.

I got around the `orca` thingy.

However, the build fails due to this
```bash
Notebook error:
NoSuchKernel in visualization/plotly/basic-tutorials/GUI with Python Demo.ipynb:
No such kernel named sislguiv2
```
So I thought I could install `sisl-gui` and get this working. But no... I can't :)

So have you somehow hardcoded a kernel, and how to make it run?

**Comment by pfebrer** [comment]
That's something I'm changing in https://github.com/zerothi/sisl/pull/291

**Comment by pfebrer** [comment]
Basically the kernel I use in my laptop has that name, but I realized that this would not be the case in the environments where the docs might be built (big surprise).

So now I'm changing the kernel to `Python 3`, which is more standard (but won't work in my laptop, because I don't have `sisl` installed in that kernel).

> So have you somehow hardcoded a kernel, and how to make it run?

Jupyter tries to find the same kernel that you were using when you saved. I don't think there's a (nice) fix for that.

**Comment by pfebrer** [comment]
I'm finishing all the changes to the notebooks, in 10min I'll be done and you can try :+1:

**Comment by zerothi** [comment]
> Basically the kernel I use in my laptop has that name, but I realized that this would not be the case in the environments where the docs might be built (big surprise).

Ok. I had no idea that kernels where hard-coded in files! I am a bit puzzled why this doesn't happen more! But perhaps I am just not around in the real world ;)

**Comment by pfebrer** [comment]
Yes I had never thought about this either. I guess you are kind of safe if you use the default `Python 3` kernel. But also it is only fatal if you are running notebooks automatically. If you are using the GUI it will just prompt you to choose another kernel.

**Comment by pfebrer** [comment]
I already commited all the changes for the notebooks, can you try from the PR? 

I rebased to master just now and I don't have the energy to split the PR, I'm done today :)

**Comment by zerothi** [comment]
I am also done for today, so lets see if I get time during the weekend.

Thanks!

**Comment by zerothi** [comment]
This is now done and pushed.

I still have a problem with your sisl_gui Demo. It opens up a new tab trying to connect to localhost. So I don't know about that.

But check out the new doc's!

**Comment by pfebrer** [comment]
Finally, thanks!! :)

El dg., 7 de febr. 2021, 22:11, Nick Papior <notifications@github.com> va
escriure:
