### ISSUE TITLE
TranSIESTA reading charges from outSile adds one extra atom

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#314]
After the Voronoi charges, transiesta adds a line like:

```
ts-Vha:  0.27918E-01 eV
```

Which is parsable by the `read_charge` method and therefore adds one extra "atom" to the charges read. That's why inside the try/except statement that parses lines I added an `int(atom_idx)`, which I see now that you removed.

I attached the output file.

[siesta.txt](https://github.com/zerothi/sisl/files/6147351/siesta.txt)

**Comment by zerothi** [comment]
Thanks, I didn't understand why you put it there. It should be fixed now, could you try?
