### ISSUE TITLE
bug: sisl.Geometry.new fails

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#315]
**Describe the bug**
`Geometry.new` fails. It was working previously, so it may be something that you have added later.
The tests are passing because you are testing `sisl.geom.graphene().new()` instead of `sisl.Geometry.new()`.

**Reproducable code**
```python
import sisl
sisl.Geometry.new("whatever")
```
```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-7eab71f544f9> in <module>
----> 1 sisl.Geometry.new("whatever")

TypeError: 'ClassDispatcher' object is not callable
```

By the way, I didn't know that you implemented `sisl.Geometry.to.df`, that's great :)

**Comment by zerothi** [comment]
Fixed! Please note I changed the name `to.df` to `to.dataframe` for clarity.

Thanks!
