### ISSUE TITLE
Conversion between spin dimensions

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#319]
**Describe the feature**
Suppose one has constructed (or read from file) a `Hamiltonian` (or `DensityMatrix` etc) with `dim=1` (unpolarized) and want to map it over to a `dim=2` (or higher) object. Is there an easy (high-level) way of doing this?

It could perhaps also be useful if one could go the other way around, obtaining an object with `dim=1` by selecting one of the spin components from a `dim=2` object.

I notice that the function `copy([dtype])` enables the possibility of changing `dtype`. Maybe one could enable here also an option to change `dim`?

**Comment by zerothi** [comment]
Hmm, currently there isn't one.

One can do like this:
```python
H = Hamiltonian(...)
...
csr = [H.tocsr(i) for i in range(H.dim)]
S = None
if not H.orthogonal:
    S = csr.pop()
# Now extend as much as you please
if len(csr) == 1:
    # make it a polarized case
    csr.append(csr[0])

Hpol = H.fromsp(H.geometry, csr, S=S)
```
This is currently the easiest way.

- Going from unpolarized to polarized is trivial, a simple copy
- unpolarized to non-collinear? In that case the off-diagonals should just be 0, I guess.
- from polarized/non-collinear to unpolarized, what to do here? average between the two components, or some way of choosing the fraction of the diagonal spin-box terms?

**Comment by tfrederiksen** [comment]
> Hmm, currently there isn't one.
> 
> One can do like this:
> 
> ```python
> H = Hamiltonian(...)
> ...
> csr = [H.tocsr(i) for i in range(H.dim)]
> S = None
> if not H.orthogonal:
>     S = csr.pop()
> # Now extend as much as you please
> if len(csr) == 1:
>     # make it a polarized case
>     csr.append(csr[0])
> 
> Hpol = H.fromsp(H.geometry, csr, S=S)
> ```
> 
> This is currently the easiest way.

Thanks, this is very instructive. But perhaps still a bit too "low-level" from the user perspective?

>     * Going from unpolarized to polarized is trivial, a simple copy

Not sure even this is completely trivial. Do you mean something like this?
```python
if H.orthogonal:
    Hpol = H.fromsp(H.geometry, [csr, csr])
else:
    Hpol = H.fromsp(H.geometry, [csr, csr], S=H.S)
```

>     * unpolarized to non-collinear? In that case the off-diagonals should just be 0, I guess.

Yes, I agree.

>     * from polarized/non-collinear to unpolarized, what to do here? average between the two components, 
>     or some way of choosing the fraction of the diagonal spin-box terms?

Indeed this is an ambiguous procedure. Going from non-collinear to polarized/unpolarized should simply skip the off-diagonals, I guess. Going to the unpolarized case I think it would be enough in most cases if the user can select the component to keep (defaulting to the first component).

**Comment by tfrederiksen** [comment]
I was thinking if it would make sense to have a simple functionality built into `copy`:
```python
H = Hamiltonian(dim=1, ...)
Hpol = H.copy(dim=2)
Hunpol = Hpol.copy(dim=1) # keep just first component
```

**Comment by zerothi** [comment]
Agreed it is a bit too low level.

I think this is better hosted in a new method... Sadly... But I think copy is too unrelated. I wouldn't assume users to think of copy as a way to change the spin-dimensions.

Perhaps `construct` could be re-used in a meaningful way depending on arguments... Or perhaps an operator would be better... Hmm.. Have to think some more about the best way.

**Comment by tfrederiksen** [comment]
OK. Could it be a new function `Hpol = H.convert(spin='polarized')` etc?

**Comment by zerothi** [comment]
I kind of like the `convert`. However, I would like it a bit more general so users can mix how they wish. For instance when going from polarized to unpolarized you may want a weight of 0.6, 0.4... Or something.

**Comment by tfrederiksen** [comment]
This could be an optional keyword `mixing=0.5`?

Nevertheless, I think the main use cases for this kind of functionality would be:
1. Using existing H/DM as starting point for further manipulations, e.g.,
```python
H = sisl.get_sile(input).read_hamiltonian() # read a spin degenerate calculation
Hpol = H.convert(spin='polarized')
# manipulate some matrix elements by hand, eg, shifting matrix element i differently for up/down components
Hpol[i, i, 0] += U / 2
Hpol[i, i, 1] -= U / 2
Hpol.write(output)
```
2. Prepare H/DM inputs for a combined "surface + adsorbate" system starting from two separate calculations: A nonmagnetic surface (nonpolarized calculation) + a magnetic adsorbate (polarized calculation) => need for polarized combined H/DM, e.g.,
```python
Hsurf = ...
Hads = ...
Hcomb = Hsurf.convert('spin-polarized').add(Hads)
Hcomb.write(output)
```
3. Reusing a converged spin-polarized converged output *that do not show spin-polarization* to prepare inputs for an unpolarized calculation. Here the `mixing` value is irrelevant as both spin channels would be essentially the same.

**Comment by zerothi** [comment]
In terms of Siesta, this is already possible. If you feed an unpolarized DM to siesta, it will simply make it polarized and continue. It will also bump it to non-collinear and SOC for that matter (and downscale as well). So generally it may be advantageous to start small, and go bigger in the end.

However, I agree on all your view. It would ideal if one could do this simpler.

**Comment by tfrederiksen** [comment]
> In terms of Siesta, this is already possible. If you feed an unpolarized DM to siesta, it will simply make it polarized and continue. It will also bump it to non-collinear and SOC for that matter (and downscale as well). So generally it may be advantageous to start small, and go bigger in the end.

OK, then I think it would be quite intuitive if `convert` did the exact same thing as SIESTA (at least as default).

**Comment by tfrederiksen** [comment]
Would you like that I prepare a PR? A new function `convert` would belong to `class SparseCSR` in `sisl/sparse.py`, no?

**Comment by zerothi** [comment]
Hmm... It isn't so clear. Because the defaults depend on the spin configuration. And that is only present in the sisl/physics/sparse class.

If anything, you could make a PR for `convert(scale=`) where `scale` is a list of lists describing the coefficients for each of the current dimensions. The sisl/sparse classes don't know anything about spin (and shouldn't).

**Comment by zerothi** [comment]
So if we start with this, it may be easier to see where we are heading. :)
