### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#321]
**Hello everyone,
When using sisl to extract the electrostatic Potential vs z, is the energy shifted from the Fermi energy?**

**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```
sgrid ElectrostaticPotential.grid.nc --average 0 --average 1 --out potential_z.dat
```

**Comment by zerothi** [comment]
No it is the potential as siesta uses it.
