### ISSUE TITLE
Sisl won't update

### ISSUE THREAD

**Issue by mlorenznano** [zerothi/sisl#322]
**Describe the issue**
Hi everyone

I wanted to do a calculation using Hubbard, therefore I need Version 0.11. of sisl but unfortuantly it simply will not update. I tried to update it via: 
`conda install -c conda-forge sisl=0.11`
`condate update --all`
I also removed sisl and then installed it again without any effect. 

My hunch is that not all requirements are fulfilled for the installion. Trying to update the specific programs will lead to conflicts. These are the current versions of the packages:
libcblas 3.8
libgfortran-ng 7.3
liblapack 3.8.0 
numpy 1.20.2
python 3.7.9
python_abi 3.7
scipy 1.6.2

I know that this is probably not an issue of sisl but nevertheless I would be really happy if someone could help!

**Comment by zerothi** [comment]
What is the error message?

**Comment by leonardedens** [comment]
Hi Nick, this is actually related to issue #76 in the hubbard repo which I recently opened. There, you proposed to update sisl to the newest version. With `conda install -c conda-forge sisl` however, only version 0.10.0 is fetched and installed. When we force the newest version with `conda install -c conda-forge sisl=0.11.0`, the package manager tries for several hours to resolve conflicts, yielding a dependency error for virtually every installed package. We tried with a fresh install of anaconda, but the problem persisted. I have attached a section of the output of the latter command. Thanks!
[conda_sisl11_out.txt](https://github.com/zerothi/sisl/files/6323892/conda_sisl11_out.txt)

**Comment by mlorenznano** [comment]
I fixed the issue. Somehow there wasn't a fotran-compiler downloaded. So `conda install -c conda-forge fortran-compiler` and afterwards installing sisl again fixed the issue. 
However this doesn't resolve issue 76 in the hubbard repo. If I run the open example it still spits out the same error message Leonard talked about.

**Comment by zerothi** [comment]
Yeah, I am working on solving this, but debugging conda is not easy...

**Comment by zerothi** [comment]
@mlorenznano and @leonardedens could you please have another try with conda? I have updated the installation scripts such that it should work again?

**Comment by mlorenznano** [comment]
I will try it in about 2 hours and will keep you updated :)

**Comment by mlorenznano** [comment]
So I removed sisl with `conda remove sisl` and installed it again with `conda install -c conda-forge sisl` and now i have `sisl.0.11.0` installed. So I guess the issue should be fixed.

**Comment by zerothi** [comment]
Great! Thanks for reporting back!
