### ISSUE TITLE
Simulate the Transport of a 1-D Graphene-Like System Subject to an external Field 

### ISSUE THREAD

**Issue by AlessandroLodi** [zerothi/sisl#324]
The idea would be to study the transport of a graphene nanoribbons when a magnetic field of a given strength is applied along the out of plane of the in-plane direction and when it bridges two graphene leads.

**Comment by zerothi** [comment]
Thanks for this!

I believe that this will already be covered in the example TB_07 of the exercises that will be shared. :)

**Comment by AlessandroLodi** [comment]
Hi Nick,

Thanks a lot for the heads-up. I have an additional question.
Would it be possible to simulate a 1-D graphene structure such as
nanoribbons in which the contact with the two semi-infinite leads is not
perfect but kind of titled by an angle (parameter).

*--- oOo ---*

*Alessandro Lodi | Clarendon Scholar | DPhil Student |*

*Trinity College, University of Oxford,*

*+44 (0) 7517 549419 (UK Mobile)*

*+39 334 3282421 (ITA Mobile)*

*--- oOo ---*

**Comment by zerothi** [comment]
Yes, if they are nano-ribbons then yes.  
If they have periodicity transverse to the semi-infinite direction, then it depends on whether you can create that simulation cell with those skewed angles.
