### ISSUE TITLE
First principle study of electrochemistry of batteries using siesta and transiesta

### ISSUE THREAD

**Issue by 7505-sh** [zerothi/sisl#329]
I want to learn how to study the electrochemistry of batteries. Learn to use trans-siesta for studying electrode and electrolyte together.

**Comment by zerothi** [comment]
> In the same context, studying the electrode and electrolyte lead to consider VLDO interaction to investigate the solid-liquid interface. However, I have not found any available pseudopotential which includes this kind of interaction. Since we cannot change the pseudo-potential file, It will be great if the team would explain how to correct the pseudo potential by adding repulsive interaction in the siesta script.

This school will not go into details about pseudo potentials or what they are restricted to. In that case you should apply for the [Siesta school](https://www.cecam.org/workshop-details/5).

**Comment by zerothi** [comment]
We hope this was made clear during the workshop! Otherwise please continue the discussion on discord!
