### ISSUE TITLE
Valley electronic in a topological nano-device 

### ISSUE THREAD

**Issue by adelphys** [zerothi/sisl#331]
**Describe what you want to accomblish with TS+TBT+sisl**
Dear Devloppers,
Good day and I hope my email finds you well. I am interested in valley electronic and would like to know how for instance to calculate this in TS+TBT+sisl, the current flow to see the valley polarization using bump strain which induces inhomogeneous pseudomagnetic fields.

I am expert in kwant package and I am developing a study to create a local current in a topological nano-device (Functionalized graphene, for instance, in order to enhance the spin orbit coupling) to make a local magnetic field in the scattering area by applying a small voltage between the source and  drain. The direction of the magnetic field could be controlled by the valley type of the current. If we use both current we will get zero magnetic field. If we filter one valley we get either positive or negative magnetic field depending on the valey direction +K or (-K). Some of the future application of my result would be creating logical gate, study valley topological hall effect and valley wave guide.

I am able to do the calculation in Kwant and I would like to see if possible with  TS+TBT+sisl since it will be great if use the accurate values of tight binding parameters  extracted from a DFT Hamiltonian.

I do appreciate your time
Regards
Adel BELAYADI
Condensed matter physics, USTHB uninversity, Algeria

**Comment by zerothi** [comment]
Thanks for this.

Would you share the relevant kwant code that enables this. Then we can see if this can be ported to this framework. :)
Thanks!

**Comment by adelphys** [comment]
Dear Papior,
I do thank you for your email.
In my current study I am developing it will be complicated since we need to
include for a given area several types of spin orbit couplings such as
Rashba SOC and pseudo assymetric spin orbit term depending on the global
point group symmetries D-6h , D-3d , D-3h , C-6v , and C-3v that represent,
for example,pristine graphene, graphene miniripple, planar boron nitride,
graphene on a substrate.
However, let us discuss the simplest case of valley filter as discussed in
the paper * PhysRevLett.117.27680.*
Kindly see my kwant code which gives the same results.
If you see this example it will take you so much time and effort so never
mind. We might discuss it later one.
Cheers, Adel

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zerothi** [comment]
Ok.
There is nothing preventing TS-TBT-sisl in doing these calculation. The currently limiting factor is that the matrix element of a state on the spectral matrix isn't currently implemented. But this is definitely on the todo! ;)

Also, I can't see your kwant code since you haven't attached it? I.e. replying by mail will remove attachments.

**Comment by adelphys** [comment]
Dear Papior,
Thank you for your answer. About the code file it state in GitHub "we don t support that file". 
so try to see this link witch allows you to download the code. 

https://drive.google.com/file/d/19mAx5z1FbLpoGIChQNSOxC_8U0kbAKGV/view?usp=sharing

Please let me know if you get it or not. you need to download and the open to see the script and figures
Best
Adel
