### ISSUE TITLE
computing the electrical properties of the system by the multi-scale method in the workshop

### ISSUE THREAD

**Issue by sheidabagherzadeh6232** [zerothi/sisl#332]
**Describe what you want to accomblish with TS+TBT+sisl**

**Comment by zerothi** [comment]
We hope this was made clear during the workshop! Otherwise please continue the discussion on discord!

**Comment by sheidabagherzadeh6232** [comment]
Dear Dr. Nick Papior,
Good time.
Thanks a lot for your useful workshop. It was very useful for me and I
learned a lot.

Thanks a lot.
Best regards,

Sheida
