### ISSUE TITLE
[devs] Change license to MPLv2

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#346]
Hi devs,

@jonaslb @pfebrer @tfrederiksen @sofiasanz 

I have been more involved in some work related to licensing issues and i believe that it is time to update the licence to a more lax version.

I hereby ask you permission to allow changing the licence from LGPLv3 to MPLv2. Generally speaking MPLv2 is a bit more lax since it allows more openness, specifically since it isn't viral in the same way LGPL is.

I hope you agree and will acknowledge this request by commenting in a thread (I will then make a copy of your thread for safe-keeping).

**Comment by pfebrer** [comment]
I obviously agree :)

**Comment by jonaslb** [comment]
What is the problem exactly? The MPL also requires that source code is made available, kind of similarly to the LGPL, I believe. So you don't exactly get rid of what you call "virality".

If you actually want to get rid of this requirement, then I disagree hard.

**Comment by tfrederiksen** [comment]
Hi @zerothi , if you really want to change the license to MPLv2 then I will respect your decision. But personally I would prefer that `sisl` stayed with LGPLv3.

**Comment by zerothi** [comment]
@jonaslb @tfrederiksen thanks for your sentiments. @pfebrer thanks for your concent.

Perhaps I should have given more context and being more explicit ;)

What I would like is to force sisl to always be an open source implementation. However, I would also like sisl to be used, extended and contributed to in a larger extent.

For this I believe MPLv2 is the correct choice.

So basically MPLv2 allows users to use sisl in a secondary work but license their own work under *almost* what-ever license they wish. However, the sisl part of that secondary work *must* and will always uphold at minimum the MPLv2 license. This means that developer X can create a piece of software (Y) with sisl distributed together with it. Y may be licensed by BSD, however, sisl would still be MPLv2.  
X may also license Y under GPLv2 (or later) and then sisl is distributed with 2 licenses GPLv2 and MPLv2, but the full software will then "formally" be under GPLv2.

This is the subtle difference between the two. My main motivation is to allow developers to extend sisl and let them decide their own license while forcing them to release sisl under MPLv2 or any of the compatible license that MPLv2 mentions (these are GPL2.0, LGPL2.1 or AGPL3.0 or any later of these).  
Basically LGPL allows *any* user (even commercial) to link/use this library dynamically such that the user may swap out the library at will. However, they are not allowed to combine the work with their own such that users cannot dynamically swap out this library (i.e. statically linked), that would mean the new combined work has to be released under LGPL as well, and thus force them to disclose their proprietary sources.  
MPL allows one to distribute this source together with the combined work and have different licenses for this and the *other* part of the combined work. However, the sisl part (and any modifications) must still uphold the MPL license.

The MPLv2, to me, is more of a *plugin* LGPL license, whereas LGPL is a *library* license. And I think `sisl` is better suited as a plugin, rather than library.

So no, I don't want to reduce the virality of sisl, it should and will remain open-source and forcing any users/distributors to retain the MPLv2 or any of the compatible licenses (as mentioned above) when doing so. My mentioning of the virality was that I don't think sisl should infect users such that they can't freely choose which license they want for _their_ software. Here I am more concerned about users who want more freedom in terms of MIT, BSD etc. rather than any proprietary works. Any commercial use of sisl is extremely easy, and MPL won't change this for the worse or for the better.

**Comment by jonaslb** [comment]
You can link proprietary stuff to LGPL libraries without being forced to open source, that's what sets it apart from GPL. You can also statically link it, as long as you provide object files for the proprietary part that can be relinked by the user to a different version of the LGPL library. In any case sisl is a python library -- the python code is always just plain readable, and the compiled objects are always dynamic.

The MPL provides *less* openness because the project is only covered on a file-by-file basis. Eg. let's say someone makes an improvement to sisl function `a()` which involves a call to a different function `b()`. This improvement can under MPL effectively be closed source, because `b()` can be in a different file.

But anyway, MPLv2 is actually OK by me. I just think it should be clear that this is a clear downgrade in terms of openness. And the motivations for the relicense appear mudded still, in my opinion.

**Comment by zerothi** [comment]
> You can link proprietary stuff to LGPL libraries without being forced to open source, that's what sets it apart from GPL. You can also statically link it, as long as you provide object files for the proprietary part that can be relinked by the user to a different version of the LGPL library. In any case sisl is a python library -- the python code is always just plain readable, and the compiled objects are always dynamic.

Yes. My point about this is that LGPL and MPL are not different in this respect, in the use case that the library may be used commercially in any case.

> The MPL provides _less_ openness because the project is only covered on a file-by-file basis. Eg. let's say someone makes an improvement to sisl function `a()` which involves a call to a different function `b()`. This improvement can under MPL effectively be closed source, because `b()` can be in a different file.

Yes. That is true. However, in the Python world that would be very easy to circumvent. You'll just at run-time override the function table in python with your edited function and then that's it. The software you distribute is compliant, but at run-time you change it for your end-user (who isn't distributing the binaries/objects). I think this is one of the gray areas that isn't totally clear, and especially since LGPL was properly designed for compiled languages.  
My main motivation is to let users who want to use BSD or looser licenses choose which-ever license they want for something they do. In particular for tool-boxes etc. This is not easily accomplished with LGPL. Since they have to uphold the LGPL license.

I am pro letting users use the software as they please and extend it to their needs, rather than trying to forcefully apply a license for them. For instance, the `R` ecosystem is having some backlashes to this (they are however using GPL).

> But anyway, MPLv2 is actually OK by me. I just think it should be clear that this is a clear downgrade in terms of openness. And the motivations for the relicense appear mudded still, in my opinion.

Thanks. I wouldn't however call this a *clear downgrade* in terms of openness. The source code of sisl would still always be required to be open, while additional files could be under a different license as you say.

**Comment by jonaslb** [comment]
> My main motivation is to let users who want to use BSD or looser licenses choose which-ever license they want for something they do. In particular for tool-boxes etc. This is not easily accomplished with LGPL. Since they have to uphold the LGPL license.

What provisions of the LGPL exactly is the problem in practice, and which is not in MPL? I honestly think this problem is fully imagined.

**Comment by zerothi** [comment]
The problem is that when users submit a PR for a toolbox that gets shipped with sisl, then it is a combined work, and then it must be LGPL, with MPL it is the contributor who decides since it is file-per-file. Since the repo is public, it would still be required to be some open-source license, but they decide.

**Comment by jonaslb** [comment]
Previously we agreed that non-LGPL can link LGPL code (non-copyleft toolboxes can use `import sisl`). You worry that LGPL sisl can't link (import) the non-LGPL toolboxes, perhaps for the single command line entry point?

As long as they use a compatible license, this should be fine. Compatible licenses notably include the modified BSD and Apachev2 (and MPL too). GNU has a list of common licenses and their (in)compatibility [here](https://www.gnu.org/licenses/license-list.html). 

It's true that the above is certainly a restriction. But I don't think that requiring GNU-compatibility is a *problem*. Consider that if you make sisl GNU-incompatible, you push the problem onto sisl's users such as Inelastica (which is LGPL too).

**Comment by sofiasanz** [comment]
Hi Nick, from my side I think is totally your decision. :)

**Comment by zerothi** [comment]
> Previously we agreed that non-LGPL can link LGPL code (non-copyleft toolboxes can use `import sisl`). You worry that LGPL sisl can't link (import) the non-LGPL toolboxes, perhaps for the single command line entry point?

My point is that a contributor may want their toolbox to be MIT or BSD. And using MPL allows contributors to select this themselves, since you can have dual-licensing under MPL. This dual licensing isn't something that is doable with LGPL.  
I did't worry about importing non-LGPL toolboxes since when they submit it it would need to be LGPL.

> As long as they use a compatible license, this should be fine. Compatible licenses notably include the modified BSD and Apachev2 (and MPL too). GNU has a list of common licenses and their (in)compatibility [here](https://www.gnu.org/licenses/license-list.html).
> 
> It's true that the above is certainly a restriction. But I don't think that requiring GNU-compatibility is a _problem_. Consider that if you make sisl GNU-incompatible, you push the problem onto sisl's users such as Inelastica (which is LGPL too).

No, not users, only distributors. You can combine anything on your local machine, GPL and GNU incompatible software, so long as you don't redistribute it you are fine.

I agree that we have to retain GNU compatibility. But contributors may want their toolboxes to be even more lax, and since they contribute it for the public, they should have the power to decide the license.

**Comment by zerothi** [comment]
All in all, what I hear is that everybody has agreed. I will make a pr with the relevant changes.

**Comment by jonaslb** [comment]
Yeah, re-licensing to MPLv2 is fine by me too if it needs to be said again finally.

The discussion has boiled down to whether using MIT/BSD components should be a problem wrt GPL. And I don't think you are correct that it is. But regardless, it's your project, and I would have made my contributions too if it was MPL to start with.

**Comment by zerothi** [comment]
Thanks to you all for the discussion @tfrederiksen @jonaslb @sofiasanz @pfebrer and your consent.

**Comment by zerothi** [comment]
> The discussion has boiled down to whether using MIT/BSD components should be a problem wrt GPL.

The problem is that the toolbox would be distributed together with `sisl` in a combined work, thus forcing the toolbox to inherit the LGPL license. It is _not_ a problem per see. But it may not be what the contributor had in mind since the toolbox _could_ live elsewhere and be under MIT. So once the toolbox lives in the `sisl` code base, it would have inherited the LGPL license.
