### ISSUE TITLE
Computation of matrix elements

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#352]
We are trying to compute some general matrix elements of the form `A_ij = < psi_i | A | psi_j >` for a Hamiltonian object `A` and where `psi_i` and `psi_j` are not necessarily referring to the same `EigenstateElectron` object.

Maybe the sisl function `expectation` could be generalized to allow for an optional `right` state?

For instance to enable something like this:
```python
import sisl
g = sisl.geom.graphene()
H = sisl.Hamiltonian(g)
H.construct([[0.1, 1.5], [0, 2.7]])
s1 = H.eigenstate([2/3, 1/3, 0])
s2 = H.eigenstate([1/3, 2/3, 0])
A = s1.expectation(H.Hk(), right=s2, diag=False)
```
What do you think about this? I am willing to give such an implementation a try.

**Comment by zerothi** [comment]
Sounds like an idea, perhaps we should convert the `inner` function to accept the matrix `A` and then remove `expectation`? They surely are quite similar. Also, I think the `inner` should not have the `align` keyword. What do you think?

**Comment by tfrederiksen** [comment]
You mean something like:
```python
s1.inner(A=H.Hk(), right=s2, diag=False)
```
where the default for the first argument would be the identity matrix (simple inner product)?

I do not really understand the `align` function - what is the purpose?

**Comment by zerothi** [comment]
> ```python
> s1.inner(A=H.Hk(), right=s2, diag=False)
> ```
> 
> where the default for the first argument would be the identity matrix (simple inner product)?

Yes, something like this. But perhaps having `A` argument being on the right, so that it is *more* optional with a matrix.

> I do not really understand the `align` function - what is the purpose?

The `align` option may be used to minimize the phase difference to the lowest value. I implemented these in the functions but have come to dislike them since users can do this themselves. So I plan on removing all `align=` arguments in the `State` classes.  
Users should then prefer:
```python
s1 = ...
s2 = ...
s2 = s2.align(s1)
...
```
instead.

**Comment by zerothi** [comment]
woops, pressed wrong button.
