### ISSUE TITLE
How to do inner products between different k

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#356]
We have `es.state[n, i]` where `n` is a band index and `i` an orbital in the primitive cell. And `H.tocsr()` has indices `[i, J]` with `i` an orbital index in the primitive cell and `J` one in the supercell.

To compute general matrix elements we need `<s1| A |s2> = s1.inner(matrix=A.tocsr(), ket=s2.state_sc)` to compute general matrix elements between the Bloch states `s1, s2`.

What I have in mind is thus that `s2.state_sc` should have indices `[m, J]` such that the general inner product `<s1(n)| A |s2(m)>` takes the form `[n, i] . [i,J] . ([m, J].T)`. (It is a separate discussion if we should transpose the ket internally or not)

_Originally posted by @tfrederiksen in https://github.com/zerothi/sisl/pull/355#discussion_r666131276_

**Comment by zerothi** [comment]
Yes ok, so what you want is to use a non-square matrix as the operator. However, I don't really follow what you then get, since `[i, J] . [m, J].T -> [i, m]` and becomes a square matrix again, and you loose the supercell information? No?  
Note: generally you shouldn't use `tocsr` for this, rather use `H.Hk(format='sc:csr')`, this will ensure to be working for NC and SOC as well.

**Comment by zerothi** [comment]
From @tfrederiksen 

What I want is basically the matrix elements between primitive cell band indices `n, m` but where the operator `A` is given in "real space". I do not want any phases applied to `A`.

As far as I see this is also the correct approach to do the inner product between states at different k-points with non-ortho basis, i.e.,
```
<k1(n) | k2(m)> = k1.state[n, i].S[i, J].((k2.state_sc[m, J]).T)
```

**Comment by zerothi** [comment]
@tfrederiksen could you please provide a mock-up example that gives what you want to calculate

**Comment by zerothi** [comment]
> ```
> <k1(n) | k2(m)> = k1.state[n, i].S[i, J].((k2.state_sc[m, J]).T)
> ```

But I think this is equivalent to `<k1|S(k2)|k2>`, right? `S[i, J] * k2[m, J] == S[i, J] * exp(2j*pi * k2 @ isc(J)) * k2[m, j]` or am I wrong here?

**Comment by tfrederiksen** [comment]
> > ```
> > <k1(n) | k2(m)> = k1.state[n, i].S[i, J].((k2.state_sc[m, J]).T)
> > ```
> 
> But I think this is equivalent to `<k1|S(k2)|k2>`, right? `S[i, J] * k2[m, J] == S[i, J] * exp(2j*pi * k2 @ isc(J)) * k2[m, j]` or am I wrong here?

You are right, they are equivalent...

Here is a little script exploring this for the non-ortho case:
```python
import sisl
import numpy as np

geom = sisl.geom.graphene()

H = sisl.Hamiltonian(geom, orthogonal=False)
H.construct([[0.1, 1.5], [[0, 1], [2.7, 0.3]]])

k = np.array([2/3, 1/3, 0])
es = H.eigenstate(k)
es_ext = np.concatenate([np.exp(2j * np.pi * k.dot(isc)) * es.state for _, isc in H.geom.sc], axis=1)

s = es.inner(es, diag=False)
s_ext = es.state.conj().dot(H.tocsr(-1).dot(es_ext.T))
assert np.allclose(s, s_ext)

ev = np.diag(es.state.conj().dot(H.tocsr().dot(es_ext.T)))
assert np.allclose(ev, es.eig)

k2 = np.array([0, 0, 0])
es2 = H.eigenstate(k2)
es2_ext = np.concatenate([np.exp(2j * np.pi * k2.dot(isc)) * es2.state for _, isc in H.geom.sc], axis=1)

s21 = es2.inner(es, diag=False)
s12_ext = es.state.conj().dot(H.tocsr(-1).dot(es2_ext.T))
assert np.allclose(s21.conj().T, s12_ext)
```

**Comment by tfrederiksen** [comment]
I guess the discussion can now be boiled down to how the general inner product `<nk|mk'> (k!=k')` is correctly computed for non-orthogonal bases. This seems also important for Berry phase calculations (although the separation in k-space is usually very small).

**Comment by zerothi** [comment]
> I guess the discussion can now be boiled down to how the general inner product `<nk|mk'> (k!=k')` is correctly computed for non-orthogonal bases. This seems also important for Berry phase calculations (although the separation in k-space is usually very small).

Yes, we are also dealing with this problem, the Berry phase is related to `<psi|\partial psi>` and is typically calculated using finite differences as you say. Perhaps one could do the Lowdin transformation at `k + dk/2` and for small enough `dk` the basis transformation (Lowdin) would be acceptable and the same approach could be obtained. Alternatively one should try and calculate the *true* `\partial psi` expression, but I think that requires displacements for at least two directions to not find erroneous points (say very close to the bottom of a parabola).

I have never examined how much the basis change with different `k` in the Lowdin transformation.

**Comment by zerothi** [comment]
> > > ```
> > > <k1(n) | k2(m)> = k1.state[n, i].S[i, J].((k2.state_sc[m, J]).T)
> > > ```
> > 
> > 
> > But I think this is equivalent to `<k1|S(k2)|k2>`, right? `S[i, J] * k2[m, J] == S[i, J] * exp(2j*pi * k2 @ isc(J)) * k2[m, j]` or am I wrong here?
> 
> You are right, they are equivalent...
> 
> Here is a little script exploring this for the non-ortho case:
> 
> ```python
> import sisl
> import numpy as np
> 
> geom = sisl.geom.graphene()
> 
> H = sisl.Hamiltonian(geom, orthogonal=False)
> H.construct([[0.1, 1.5], [[0, 1], [2.7, 0.3]]])
> 
> k = np.array([2/3, 1/3, 0])
> es = H.eigenstate(k)
> es_ext = np.concatenate([np.exp(2j * np.pi * k.dot(isc)) * es.state for _, isc in H.geom.sc], axis=1)
> 
> s = es.inner(es, diag=False)
> s_ext = es.state.conj().dot(H.tocsr(-1).dot(es_ext.T))
> assert np.allclose(s, s_ext)
> 
> ev = np.diag(es.state.conj().dot(H.tocsr().dot(es_ext.T)))
> assert np.allclose(ev, es.eig)
> 
> k2 = np.array([0, 0, 0])
> es2 = H.eigenstate(k2)
> es2_ext = np.concatenate([np.exp(2j * np.pi * k2.dot(isc)) * es2.state for _, isc in H.geom.sc], axis=1)
> 
> s21 = es2.inner(es, diag=False) # using S(k2) from es2
> s12_ext = es.state.conj().dot(H.tocsr(-1).dot(es2_ext.T))
> assert np.allclose(s21.conj().T, s12_ext)
> 
> s12 = es.inner(es2, diag=False) # using S(k) from es
> assert not np.allclose(s12, s12_ext)
> ```

A note, you shouldn't use `tocsr`. When you start using NC/SOC what you want is `Hk(format='sc'). I have just fixed so one can use `format='sc'` for gamma-point.

**Comment by zerothi** [comment]
Something like this is discussed here:
https://github.com/Z2PackDev/Z2Pack/issues/79
and https://github.com/Z2PackDev/Z2Pack/pull/94

I am not sure the Lowdin method is ensuring the *same* basis for **S(k)^(-1/2)** vs. **S(k+dk)^(-1/2)**.

**Comment by zerothi** [comment]
My biggest concern about using the Lowdin transformation is that I am not sure that it is mathematically the same basis for all $k$, and then I think it is basically wrong. While z2pack may give reasonable results I haven't found a solid proof of it.

**Comment by zerothi** [comment]
It seems that openmx + z2pack does the lowdin, perhaps we should just add it with a note about it. That would be ok, I assume...

Steps required:
- [ ] add a lowdin transformation to the linalg routines, copy sqrtm from `toolbox/btd/` to linalg to make this easier.
- [ ] implement the lowdin transformation in the berry_phase calculations

**Comment by tfrederiksen** [comment]
Maybe it is worth to understand how SIESTA is computing macroscopic polarization of dielectrics (via the geometric Berry phase) as implemented in the subroutine `KSV_pol`?

**Comment by zerothi** [comment]
> Maybe it is worth to understand how SIESTA is computing macroscopic polarization of dielectrics (via the geometric Berry phase) as implemented in the subroutine `KSV_pol`?

In siesta it is calculated using the matrix elements $phi_i(r-r_i)*dk*r*phi_j(r-r_j) + HC$  to get a phase on the orbital. Then subsequently it is the determinant of some overlap matrix times the wavefunction coefficients (not fully correct, but along these lines).

I would say this path is not feasible in sisl due to the matrix elements not being calculate-able in a fast way.

**Comment by pfebrer** [comment]
You could try implementing the Lowdin transformation in an experimental branch. 

Then I can easily check if it works in practice by calculating the zak phase of my systems. I can also check how fine `dk` needs to be compared to the orthogonal basis case. In the end, this is a very easy thing to test. If the result is 0 or 3.14 it means it works and if not, it doesn't work :)

**Comment by zerothi** [comment]
> You could try implementing the Lowdin transformation in an experimental branch.
> 
> Then I can easily check if it works in practice by calculating the zak phase of my systems. I can also check how fine `dk` needs to be compared to the orthogonal basis case. In the end, this is a very easy thing to test. If the result is 0 or 3.14 it means it works and if not, it doesn't work :)

Lowdin is now a routine call in `linalg.special`

Simply do
```python
from sisl.linalg.special import lowdin

Hk_lowdin = lowdin(Sk, Hk)
```
and use that one...

To convert a wavefunction one should be able to do:
```
from sisl.linalg.special import invsqrth
Si12 = invsqrth(Sk)
es.state[:, :] = (Si12 @ es.state.T).T
```

**Comment by zerothi** [comment]
> You could try implementing the Lowdin transformation in an experimental branch.
> 
> Then I can easily check if it works in practice by calculating the zak phase of my systems. I can also check how fine `dk` needs to be compared to the orthogonal basis case. In the end, this is a very easy thing to test. If the result is 0 or 3.14 it means it works and if not, it doesn't work :)

@pfebrer Could you try now, the latest commit allows this in sisl, *UNTESTED* and will be removed if no positive sign is made ;)

**Comment by pfebrer** [comment]
I'm doing the tests and seeing some strange things, I will get back to you when I am sure I'm doing everything correctly :+1:

**Comment by zerothi** [comment]
I think this is on nearly all parts explored and tested.
The procedure is to convert both states at different `k` to the lowdin basis. Then it follows easily.
