### ISSUE TITLE
Sisl Siesta Barriers

### ISSUE THREAD

**Issue by arsalan-akhtar** [zerothi/sisl#364]
Hey Nick so i finally make peace with issues in Git jajajajajajaj ... 
So i went through ur comments on draft merge one now i'have something like this :

**Example case**

`from toolbox.siesta.barriers import VacancyExchange `
`import sisl`
`host= sisl.get_sile('./MgO-sheet.fdf').read_geometry()`
`A=VacancyExchange(host_structure=host,`
`                 ghost=True,`
`                 interpolation_method='idpp',`
`                 trace_atom_initial_position=2,`
`                 trace_atom_final_position=18,`
`                 number_of_images=17)`
`A.set_initial_relaxed_path("/home/aakhtar/Calculations/2020/siesta/SiestaBarriers/VacancyExchange/new-0/results/")`
`A.set_final_relaxed_path("/home/aakhtar/Calculations/2020/siesta/SiestaBarriers/VacancyExchange/new-8/results/")`
`A.set_initial_relaxed_fdf_name("input.fdf")`
`A.set_final_relaxed_fdf_name("input.fdf")`
`A.set_relaxed(False)`
`A.Generate_Vacancy_Exchange_Images()`
`A.IO.prepare_NEB()`

**Put code here**

i removed the intermediate class (SiestaBarrier) ... now for each barrier type will have its one class to initiate (VacancyExchange,Exchange,Manual,...)
 like this:
class VacancyExchange(SiestaBarriersBase):
    """
    Init Object for VacancyExchange
    INPUTs:
           host_structure = Sisl Stucture Object
           number_of_images = # of images for NEB
           trace_atom_initial_position = initial Atom Position/Index
           trace_atom_final_position = final Atom Position/Index
           interpolation_method = idpp
    """

    def __init__(self,
                 host_structure ,
                 number_of_images  ,
                 trace_atom_initial_position ,
                 trace_atom_final_position ,
                 interpolation_method = 'iddp',
                 ghost = True ,
                 ):

        super().__init__(
                 relaxed = False,
                 host_structure = host_structure ,
                 number_of_images = number_of_images,
                 initial_relaxed_path = None,
                 initial_relaxed_fdf_name = None ,
                 final_relaxed_path = None ,
                 final_relaxed_fdf_name = None,
                 trace_atom_initial_position = trace_atom_initial_position ,
                 trace_atom_final_position = trace_atom_final_position ,
                 atol = 1e-2,
                 rtol = 1e-2,
                )
        self.host_structure = host_structure
        self.number_of_images = number_of_images
        self.interpolation_method = interpolation_method
        self.ghost = ghost

**Comment by zerothi** [comment]
Hi, you should continue the discussion in the previous pr, much simpler, and then I can see what you are doing. Could you do that?

**Comment by arsalan-akhtar** [comment]
sure ...
________________________________
