### ISSUE TITLE
viz and import statements in tests

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#375]
**Describe the issue**
@pfebrer I have a task for you ;)

See [here](https://app.travis-ci.com/github/zerothi/sisl/jobs/536604850).

The tests fails because of imports, now I can't figure out exactly where all the tests are. But could you please put a 
```python
pytest.importorskip("plotly", reason="plotly not available")
```
where necessary so they won't fail?

Thanks!

EDIT: yes, I meant to write `plotly`

**Comment by pfebrer** [comment]
All tests that depend on `skimage` are already marked.

The problem is that if you don't have plotly you will basically not test almost anything. So I would say we either install `plotly` in the CI workflows or I can try to rewrite the tests so that they don't need plotly. It makes complete sense to rewrite the tests without plotly in this new design. I can do it if you can wait 1 day.

**Comment by zerothi** [comment]
> All tests that depend on `skimage` are already marked.
> 
> The problem is that if you don't have plotly you will basically test almost nothing. So I would say we either install `plotly` in the CI workflows or I can try to rewrite the tests so that they don't need plotly. It makes complete sense to rewrite the tests without plotly in this new design. I can do it if you can wait 1 day.

Since plotly isn't required by the user, it shouldn't be required in the tests. This is my point. Exactly the same issue is apparent for `dill` and `pathos`. These are optional dependencies, but since `pytest` imports all test files at test-time, it will fail the entire suite. This means that users can't test on their own. So we better have a CI test doing the same as a minimal user.

I think the tests that require plotly should just be skipped with importerskips, or something similar, whatever you prefer. I'll hold ;)

**Comment by zerothi** [comment]
note I have just `autopep8` the code, so please pull :)

**Comment by pfebrer** [comment]
Ok :+1:  I'm almost done :sweat_smile:
