### ISSUE TITLE
viz.test fails with 3.6

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#377]
**Describe the issue**

@pfebrer the tests almost succeeds. However, when using 3.6 and some matplotlib version seems to fail using the `alpha` keyword:

https://app.travis-ci.com/github/zerothi/sisl/jobs/537306838

I don't know how to fix this.

```python
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
19212
19213self = <matplotlib.collections.PathCollection object at 0x7ff95887a2b0>
19214alpha = array([1., 1., 1., 1., 1., 1., 1., 1.])
19215
19216    def set_alpha(self, alpha):
19217        """
19218        Set the alpha value used for blending - not supported on all backends.
19219    
19220        Parameters
19221        ----------
19222        alpha : float or None
19223        """
19224        if alpha is not None and not isinstance(alpha, Number):
19225>           raise TypeError('alpha must be a float or None')
19226E           TypeError: alpha must be a float or None
19227
19228../builds/sisl-venv/lib/python3.6/site-packages/matplotlib/artist.py:930: TypeError
```
?

**Comment by zerothi** [comment]
Weirdly enough this succeeds using 3.8...?

**Comment by pfebrer** [comment]
I think this might be because the latest matplotlib version supports >= 3.7 only. (starting from matplotlib 3.4.0). If you are installing the latest matplotlib in CI, it is possible that the behavior of the alpha argument was changed in matplotlib 3.4 or later. I will check

**Comment by pfebrer** [comment]
Yep that's it. Checking the logs I see that tests in python 3.8 install `matplotlib 3.4` while the ones on python 3.6 install `matplotlib 3.3`. I have tried both versions of `matplotlib` and indeed `3.3` fails to accept an array of alpha values.

I will solve this by ignoring alpha in that case and issuing a warning.
