### ISSUE TITLE
Check notebooks for errors in CI

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#379]
The tutorial here: 
https://zerothi.github.io/sisl/docs/latest/tutorials/tutorial_siesta_1.html?highlight=eigenstate

fails because it uses the `origo` keyword when initializing the geometry.

Maybe it would be a good idea to not allow errors in the documentation notebooks to find these bugs? :)

**Comment by zerothi** [comment]
Thanks, good idea. I have now fixed it. Should be added to the travis scripts.

**Comment by pfebrer** [comment]
Why not setting these to `False`?

https://github.com/zerothi/sisl/blob/de8883f610a84a362f876f73a0ad42ff164deb8a/docs/conf.py#L108-L113

**Comment by zerothi** [comment]
When doing that, I get this:

```python
ipython-input-3-df4c463be604> in <module>
----> 1 import sisl_gui
      2 
      3 sisl_gui.launch()

/opt/gnu/9.3.0/python/3.8.5/lib/python3.8/site-packages/sisl_gui/__init__.py in <module>
----> 1 from .launch import launch, open_gui
      2 from .server import *
      3 from .server.sync import Connected
      4 
      5 from ._patch import _patch

/opt/gnu/9.3.0/python/3.8.5/lib/python3.8/site-packages/sisl_gui/launch.py in <module>
      5 import webbrowser
      6 
----> 7 from sisl.viz.plotly.plotutils import get_session_classes
      8 
      9 from . import server

```
?

**Comment by zerothi** [comment]
it is the latest sisl_gui, 0.1.2

**Comment by pfebrer** [comment]
Aah ok, you can remove the "sisl/docs/visualization/viz_module/basic-tutorials/GUI with python demo.ipynb" notebook. It is not used in the docs anymore.

**Comment by zerothi** [comment]
> Aah ok, you can remove the "sisl/docs/visualization/viz_module/basic-tutorials/GUI with python demo.ipynb" notebook. It is not used in the docs anymore.

Could you please try and run the documentation, `docs/build_docs.sh`, there are other errors in the notebooks.

**Comment by zerothi** [comment]
what about this: `Building a plot class.ipynb`? It seems this is the only other one importing `sisl.viz.plotly`?

**Comment by pfebrer** [comment]
Hey sorry I just got home. I will check the errors now. 

> what about this: Building a plot class.ipynb? It seems this is the only other one importing sisl.viz.plotly?

This one is outdated and it is not used in the docs. However I want to update it in the future so I prefer to keep it here. Could you execute one cell and save it with the output so that `nbsphinx` doesn't execute the notebook? Or [change its metadata](https://nbsphinx.readthedocs.io/en/sizzle-theme/never-execute.html).

**Comment by pfebrer** [comment]
Are there more errors apart from this one?

**Comment by zerothi** [comment]
No, it seemed it worked now! Thanks!
