### ISSUE TITLE
How to run ex_03.py in sisl/examples ?

### ISSUE THREAD

**Issue by staniba** [zerothi/sisl#39]
Hello Developers,

I would like to know how to run ex_03.py in sisl/examples.

What I did so far are followings:
(1) python ex_03.py
     => obtained {zz.gin, ZZ.fdf}.
(2) gulp < zz.gin >zz.gout
     => seems to be finished normally.
(3) python ex_03.py
     => obtained {ELEC_zz.nc, DEVICE_zz.nc}
(4) tbtrans <ZZ.fdf >ZZ.out
   => could not finish normally.
In the tail of ZZ.out, "Must specify k-points with Monkhorst_Pack".

Thanks much,
satoru

**Comment by zerothi** [comment]
Note that example `03` is a phonon calculation. You should use `phtrans` for this.

Secondly, it seems you are perhaps not using 4.1-b3?
Please state your versions if the above does not apply.

Please

**Comment by staniba** [comment]
Hello Nick,

Thank you for your answering.
Exactly, I was using 4.0.2.
So, firstly, I will install 4.1-b3.

As for phtrans, I was thinking that phtrans and tbtrans are the same executable file.
https://answers.launchpad.net/siesta/+question/576058

So, after installing 4.1-b3, I will find the executable file of phtrans.

satoru

**Comment by zerothi** [comment]
They are "essentially", however, there are some differences regarding the self-energies and how the energy is handled. So there is a reason that there are two different executables.
