### ISSUE TITLE
Inquiry about Fermi Velocity calculation

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#392]
Good afternoon all,

I would like to calculate from the band structures the fermi velocity at the Dirac pt for graphene.

It seems it can be done via sisl: 

http://zerothi.github.io/sisl/docs/latest/api/generated/sisl.physics.electron.velocity.html 

Specifically the command:

sisl.physics.electron.velocity(state, dHk, energy=None, dSk=None, degenerate=None, degenerate_dir=(1, 1, 1), project=False)

I was wondering exactly:
1-  How should i define the state, dHk and energy? I know it at the Fermi energy level but the rest I am not sure why they mean even after reading the definition.
2- Can can I find out from the band structure that the state is degenerate or not?
3- Is there a tutorial (or an example using fdf and so) to see how it is properly used?

Thank you very much and eager to reading all comments.
Cheers,
El-abed

**Comment by zerothi** [comment]
Yes, this can be done. However, to improve the documentation it would be most useful if you could elaborate on how you understand the documentation as it is?

- 1: the documentation should explain what these quantities are. I can see that a link to `Hamiltonian.dHk` isn't there, I will add this in future documentation. Could you please try and re-read and comment while reading so I can improve ;)
- 2 hmm... Before just giving you the answer, ;) What does degenerate meen in the context of eigenstates?
- 3 it is by far easiest to use with the `eigenstate` function: `H.eigenstate().velocity()`

**Comment by el-abed** [comment]
Thank you for the reply. I guess what I am asking is what files or what content should I be filling in the command
sisl.physics.electron.velocity

I think the best way is if I have done a quick siesta band structure calculation was done for graphene and would like to use sisl.physics.electron.velocity
What exactly should in state, eigenstate. hK. I honestly do not know what to put.

So in sgrid for example we use the nc file to extract a cube file

sgrid "Rho.grid.nc{1.,-1.}" -G RUN.fdf diff_up-down.cube

But for  sisl.physics.electron.velocity, I am not sure how to get the states and such.

Hope my inquiry made sense?

**Comment by zerothi** [comment]
There is no command-line interface for this. You have to create a python script and use `sisl` via python.

Please look through the tutorials: https://zerothi.github.io/sisl/docs/latest/tutorials.html

**Comment by el-abed** [comment]
I see. So after running SIESTA i should go through the tutorial to get the parameters needed for 
sisl.physics.electron.velocity
is that correct?

**Comment by zerothi** [comment]
yes

**Comment by zerothi** [comment]
Did we solve the question?

**Comment by el-abed** [comment]
To be honest, i tried to understand but it seems I need to go through it much more deeply. For now, I will close it and then once i give up on it then I will try to be more specific in my question.
