### ISSUE TITLE
Default parallel choice -- to be or to remove

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#394]
As long as `SISL_NPROCS>1` the tests sometimes fails, and quite often with `OMP_NUM_THREADS>1` and threaded libraries it will just simply stall for ever.

We need a more careful test of this to assert whether this is because of `pytest` instantiation (I have a feeling that the combination of `pytest` + `SISL_NPROCS>1` + `OMP_NUM_THREADS>1`

In any case I think it is vital we don't ship out a code that actually does not perform.

@pfebrer you also saw some of this (can't seem to find the thread). I think we need to have a discussion here, otherwise I will simply put the default `SISL_NPROCS == 1` to at least have something.

As it stands I am a bit inclined to try and default to not using multiple processors, but rely on threads for performance through BLAS. In any case many of the demanding things are based on BLAS+LAPACK calls and so adding the pool will only make it worse... :(

**Comment by zerothi** [comment]
The test that runs `run_multiple` takes for-ever on my machine. And so it seems like this is really not worth the hazzle?

Does your even run in this case?

Note, I am running on py3.9 currently.

**Comment by pfebrer** [comment]
> The test that runs run_multiple takes for-ever on my machine. And so it seems like this is really not worth the hazzle?

Could you tell me which test is exactly?

I think running multiple processes can be useful but it needs more careful thought. So the safest, for now, would be to default to 1 processor. Even force it to be one processor if you wish. That way we can keep the code as is and wait until we are willing to give it more thought.

In the case of `sisl.viz` it is used to parallelize the creation of plots for `MultiplePlot`.
In the case of Brillouin zones, I think that if we give it more thought we could optimize it in a way that only arrays are passed between processes and it could be really useful.

So in my opinion, we shouldn't give up on multiprocessing. Just recognize that the current approach is probably not useful and fix it someday. If everything is based on the threading of the underlying BLAS implementation, it probably won't scale to clusters or other complex architectures.

**Comment by zerothi** [comment]
I agree it could be useful, but I can't get it to perform good in any way. It may be that cpuset + multiprocessing is messing up things such that they lie on the same cpu...
I'll find the test exactly.

**Comment by zerothi** [comment]
I think it is this one: `viz/tests/test_plot.py::TestMultiplePlot::test_object_sharing`, would that make sense?

I can make everything run fine with `export SISL_NPROCS_VIZ=1`

**Comment by pfebrer** [comment]
Yes it makes sense. I think I will just ignore SISL_NPROCS_VIZ for now and always run in serial. And drop the `pathos` dependency. Is it fine?

**Comment by pfebrer** [comment]
If it's fine, then you can just write a line after

https://github.com/zerothi/sisl/blob/850570f69725daf488e777a9324ef64fa4742715/sisl/viz/plotutils.py#L607

like

```python
_MAX_NPROCS = 1
```

and remove the pathos dependency from `setup.py`

**Comment by zerothi** [comment]
Ok, I am going to fix this.

**Comment by zerothi** [comment]
I'll just keep the pathos for now since users can then still experiment with it...

**Comment by zerothi** [comment]
For now everything is defaulted to 1 core.
