### ISSUE TITLE
ValueError: hsxSileSiesta xij(orb) -> xyz did not  find same coordinates for different connections

### ISSUE THREAD

**Issue by lindasheila** [zerothi/sisl#398]
**Describe the issue**

**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
import sys
print(sys.version)
import sisl
print(sisl.__version__)
print(sisl.__git_revision__)
```
3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
print(sisl.__version__)
0.12.0+344
a2b8232ba4c52546039690601ff4b1d99cebffba

Dear All,

I run the following command line
import matplotlib.pyplot as plt
import sisl as si
from sisl import *

wfsx = si.get_sile("aGe60Se40_As.fullBZ.WFSX")
print(wfsx)

fdf= get_sile('GeSe.fdf').read_geometry()
H = get_sile("aGe60Se40_As.HSX").read_hamiltonian(geometry=fdf)
#print(H)
Hes = H.eigenstate()
Overlap_Mat=H.Sk  ## to read the overlap matrix
#print(type(Overlap_Mat), H.Sk)
#print(Overlap_Mat([0,0,0]))
rows = Overlap_Mat([0,0,0]).shape[0]
columns = Overlap_Mat([0,0,0]).shape[1]
#print(rows,columns)
#print(Overlap_Mat([0,0,0]),type(Overlap_Mat([0,0,0])))

SK=Overlap_Mat([0,0,0]).toarray()

I have the following error message: 
---> 42 H = get_sile("aGe60Se40_As.HSX").read_hamiltonian(geometry=fdf)
ValueError: hsxSileSiesta xij(orb) -> xyz did not  find same coordinates for different connections.

A couple of weeks ago I ran the same code without any mistake.

Please any suggestion?
Thank you!

**Comment by zerothi** [comment]
So what changed since last when it worked?
Have you updated or rerunned the calculation?

**Comment by lindasheila** [comment]
No No I haven't!

I wanted to make my curve beautiful by changing the ytics:
x=[0,0.4]
plt.yticks(np.arange(min(x), max(x)+1, 0.10)) 

and this happens!
Strangely enough I have re downloaded in a new directory the same data from the cluster and still the same mistake.




    Le mardi 9 novembre 2021 à 14:54:49 UTC+1, Nick Papior ***@***.***> a écrit :  
 
 


So what changed since last when it worked?
Have you updated or rerunned the calculation?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zerothi** [comment]
But sisl is quite deterministic in this case.

 In any case the hsx file format is not complete and therefore I would not recommend to use that file. I would advocate you using the tshs format.

The error happens when sisl cannot figure out the connection between the xij and geometry coordinates.

I am pretty sure that there is no random numbers involved here, so I have to say that you *must* have changed something. I.e. upgrading sisl or something else...

**Comment by zerothi** [comment]
Since no follow has been issued, I'll consider this resolved.
