### ISSUE TITLE
PDOS of a spin-polarized hamiltonian

### ISSUE THREAD

**Issue by Saulsanchez7** [zerothi/sisl#408]
I want to calculate the PDOS of a spin-polarized Hamiltonian following the steps of the tutorial from siesta-graphene that is not spin-polarized. For that I do the following:

fdf = get_sile('bda.fdf')
H = fdf.read_hamiltonian()
E = np.linspace(-3, 3, 1000) 
bz = MonkhorstPack(H, [1, 1, 1])
idx_s = list()
idx_p = list()
idx_d = list()
for i, orb in enumerate(H.geometry.atoms[0]):
    if orb.l == 0 and orb.n==6:                                 # Orbitals 6s
        idx_s.append(i)
    elif orb.l == 1 and orb.n==6:                               # Orbitals 6p
        idx_p.append(i)
    elif orb.l == 2 and orb.n==5:                               # Orbitals 5d
        idx_d.append(i)

# Get all orbitals
all_s = np.add.outer(H.geometry.a2o([0, 1]), idx_s).ravel()
all_p = np.add.outer(H.geometry.a2o([0, 1]), idx_p).ravel()
all_d = np.add.outer(H.geometry.a2o([0, 1]), idx_d).ravel()

def wrap(PDOS):
    pdos_d = PDOS[all_d, :].sum(0)
    pdos_s = PDOS[all_s, :].sum(0)
    pdos_p = PDOS[all_p, :].sum(0)
    
    return np.stack((pdos_d))
pDOS = bz.apply.average.PDOS(E, wrap=wrap)

But I get the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-16-3939b03bcb9d> in <module>
     24 
     25     return np.stack((pdos_d))
---> 26 pDOS = bz.apply.average.PDOS(E, wrap=wrap)

~/.local/lib/python3.6/site-packages/sisl/physics/brillouinzone.py in func(wrap, eta, *args, **kwargs)
   1216             k = bz.k
   1217             w = bz.weight
-> 1218             v = _asoplist(wrap(method(*args, k=k[0], **kwargs), parent=parent, k=k[0], weight=w[0])) * w[0]
   1219             eta.update()
   1220             for i in range(1, len(k)):

~/.local/lib/python3.6/site-packages/sisl/utils/misc.py in dec_func(*args, **kwargs)
    317             for arg in args_:
    318                 del kwargs[arg]
--> 319             return func(*args, **kwargs)
    320 
    321         return dec_func

<ipython-input-16-3939b03bcb9d> in wrap(PDOS)
     19 
     20 def wrap(PDOS):
---> 21     pdos_d = PDOS[all_d, :].sum(0)
     22     pdos_s = PDOS[all_s, :].sum(0)
     23     pdos_p = PDOS[all_p, :].sum(0)

IndexError: index 4 is out of bounds for axis 0 with size 4

Is there any way to solve this problem?

Thank you in advance

**Comment by zerothi** [comment]
As the error says, it can't find index 4 in the array, Note that the graphene example assumes that the first 2 atoms are equivalent. It seems to me that is not the case in your example.

Problem is that the 
```python
for i, orb in enumerate(H.geometry.atoms[0]):
    if orb.l == 0 and orb.n==6: # Orbitals 6s
        idx_s.append(i)
    elif orb.l == 1 and orb.n==6: # Orbitals 6p
        idx_p.append(i)
    elif orb.l == 2 and orb.n==5: # Orbitals 5d
        idx_d.append(i)
```
assumes that atoms `0` and `1` are equivalent as the `np.add.outer` will take the same orbitals on the atoms corresponding to index 0 and 1.
So you should be more careful when creating the `idx_*` variables to extract the correct indices.

**Comment by pfebrer** [comment]
Maybe using the visualization framework can help making this simpler.

You can create a PDOS plot from your hamiltonian like:

```python
pdos_plot = H.plot.pdos(kgrid=[1,1,1], Erange=[-3,3], nE=1000)
```

Then if you just want to plot the PDOS contributions you can follow instructions here to select whatever you want: https://zerothi.github.io/sisl/visualization/viz_module/showcase/PdosPlot.html#PDOS-requests.

But if you want the values, then you can use the (for now private) method (`_get_request_PDOS`), which will give you the values for a specific PDOS request:

```python
pdos_plot._get_request_PDOS({"n": 6, "l": 0})
```

will give you the PDOS contribution for the 6s orbitals (summing both spins).

If you want to do more complex things it's probably better to understand what goes on behind the calls, but if all you want is to get the 6s PDOS, I think it's a simple way to get what you want :)

**Comment by zerothi** [comment]
Did any of our suggestions help?

**Comment by Saulsanchez7** [comment]
Thank you so much for your quick response. This may be a very stupid question as this is my first time using sisl, but if I follow what pfebrer has told me:

from sisl import *
import sisl.viz
fdf = get_sile('bda.fdf')
H = fdf.read_hamiltonian()
pdos_plot = H.plot.pdos(kgrid=[1,1,1], Erange=[-3,3], nE=1000)

I have the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-a50cde50de41> in <module>
----> 1 pdos_plot = H.plot.pdos(kgrid=[1,1,1], Erange=[-3,3], nE=1000)

~/.local/lib/python3.8/site-packages/sisl-0.11.0-py3.8-linux-x86_64.egg/sisl/sparse_geometry.py in __getattr__(self, attr)
    226         be looked up in the hosting geometry.
    227         """
--> 228         return getattr(self.geometry, attr)
    229 
    230     # Make the indicis behave on the contained sparse matrix

AttributeError: 'Geometry' object has no attribute 'plot'

What am I doing wrong?

**Comment by pfebrer** [comment]
Hmm maybe it's something related to the sisl version. The visualization module has been introduced very recently. I see you are using `sisl-0.11.0`. Could you try to install from the github version, like so:
```
python3 -m pip install git+https://github.com/zerothi/sisl.git
```
Let me know if it works then!

By the way, in markdown, you can wrap your code snippets with triple "`" so that it is formatted as code. You can even specify the language: ```python. Then we will be able to read them more easily :)

Something like: 
``python
import sisl

sisl.get_sile()
``
but with three "`" instead of two

**Comment by zerothi** [comment]
Any updates? I will be planning a release soon, this should hopefully solve the problem. @Saulsanchez7 please respond here in case @pfebrer suggestion did not work.
