### ISSUE TITLE
Using black code formatting style

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#413]
**Describe the feature**
I would like to use some kind of code formatter/style tool.

And while I don't agree with all of them on all things, I think it is better to just have consistency above all.

Any suggestions?

I have thought about using `black`, it is a tough formatter, but is really consistent.

**Comment by zerothi** [comment]
@pfebrer any comments? K

**Comment by pfebrer** [comment]
I don't have much experience with code formatters. The only thing I know is that sometimes they can be really annoying trying to format things in ways that don't look nice and you have to add comments in your code just to avoid the formatter for certain lines. 😅

Tomorrow I will look into how `black` works and give an opinion about it 👍

**Comment by zerothi** [comment]
Agreed. However if it formats code nice in 80-90% it might be the trouble worth it.

One good example of where I think it messes things up is the periodic table... You'll see ;)

**Comment by pfebrer** [comment]
> You'll see ;)

Can't wait haha
