### ISSUE TITLE
NotImplementedError: MatplotlibGridBackend does not implement displaying grids in 3D

### ISSUE THREAD

**Issue by icamps** [zerothi/sisl#425]
Hi,

When trying to plot a 3D property (RHO, Wavefunction, etc.), I am getting the following error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/tmp/ipykernel_19369/1433050745.py in <module>
----> 1 plot.update_settings(axes="xyz")

~/.local/lib/python3.9/site-packages/sisl/viz/configurable.py in update_settings(self, *args, **kwargs)
    435             # the available kwargs for the plot class and provide more help to the user
    436             def update_settings(self, *args, **kwargs):
--> 437                 return self._update_settings(*args, **kwargs)
    438 
    439             update_settings.__doc__ = f"Updates the settings of this plot.\n\nDocs for {new_cls.__name__}:\n\n{get_configurable_docstring(new_cls)}"

~/.local/lib/python3.9/site-packages/sisl/viz/configurable.py in _update_settings(self, run_updates, **kwargs)
    556             #Do things after updating the settings
    557             if len(self.settings_history.last_updated) > 0 and run_updates:
--> 558                 self._run_updates(self.settings_history.last_updated)
    559 
    560         return self

~/.local/lib/python3.9/site-packages/sisl/viz/configurable.py in _run_updates(self, for_keys)
    584         # Execute the functions that we need to execute.
    585         for f_name in func_names:
--> 586             getattr(self, f_name)()
    587 
    588         return self

~/.local/lib/python3.9/site-packages/sisl/viz/plotutils.py in apply_to_all_plots(obj, children_sel, *args, **kwargs)
    827         else:
    828 
--> 829             return method(obj, *args, **kwargs)
    830 
    831     return apply_to_all_plots

~/.local/lib/python3.9/site-packages/sisl/viz/configurable.py in func(obj, *args, **kwargs)
    886             def func(obj, *args, **kwargs):
    887                 getattr(obj, method_name)(**kwargs, **extra_kwargs)
--> 888                 return method(obj, *args, **kwargs)
    889 
    890         elif when == 'after':

~/.local/lib/python3.9/site-packages/sisl/viz/plot.py in set_data(self, update_fig, **kwargs)
   1113 
   1114         if update_fig:
-> 1115             self.get_figure()
   1116 
   1117         return self

~/.local/lib/python3.9/site-packages/sisl/viz/configurable.py in f_default_setting_args(self, *args, **kwargs)
    967                     pass
    968 
--> 969         return f(self, *args, **kwargs)
    970 
    971     return f_default_setting_args

~/.local/lib/python3.9/site-packages/sisl/viz/plot.py in get_figure(self, backend, clear_fig, **kwargs)
   1142             self.clear()
   1143 
-> 1144         self.draw(getattr(self, "_for_backend", None))
   1145 
   1146         call_method_if_present(self, '_after_get_figure')

~/.local/lib/python3.9/site-packages/sisl/viz/backends/templates/_plots/grid.py in draw(self, backend_info)
     24         drawing_func = getattr(self, f"draw_{backend_info['ndim']}D")
     25 
---> 26         drawing_func(backend_info)
     27 
     28         if backend_info["geom_plot"] is not None:

~/.local/lib/python3.9/site-packages/sisl/viz/backends/matplotlib/_plots/grid.py in draw_3D(self, backend_info, **kwargs)
     46     def draw_3D(self, backend_info, **kwargs):
     47         # This will basically raise the NotImplementedError
---> 48         super().draw_3D(backend_info, **kwargs)
     49 
     50         # The following code is just here as reference of how this MIGHT

~/.local/lib/python3.9/site-packages/sisl/viz/backends/templates/_plots/grid.py in draw_3D(self, backend_info, **kwargs)
     39     def draw_3D(self, backend_info, **kwargs):
     40         """Should draw all the isosurfaces of the grid in 3D"""
---> 41         raise NotImplementedError(f"{self.__class__.__name__} does not implement displaying grids in 3D")
     42 
     43 GridPlot.backends.register_template(GridBackend)

NotImplementedError: MatplotlibGridBackend does not implement displaying grids in 3D
```
I installed SISL using CONDA.

**Version details**
```
print(sys.version): 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17)  [GCC 9.4.0]
print(sisl.__version__): 0.11.1.dev507+gb0511912
```

**Comment by zerothi** [comment]
@pfebrer what should we do? Add a more descriptive error message for the future? I think that is the only option

@icamps this is because it hasn't been implemented. So basically it behaves as expected, we would advice you to play with the plotly backend, but @pfebrer can be more helpful here.

**Comment by pfebrer** [comment]
As Nick says, this is expected as we haven't implemented it yet :) The 3D plots in sisl are not implemented in matplotlib, only 2D plots are available using matplotlib. 

There's two things we could do here:
- Add an extra sentence to the error like: "You could try one of the other available backends (e.g. plotly or blender)." And maybe add information about how to do so, because there might be cases in which the user is using the matplotlib backend because matplotlib was already installed in the environment where they install sisl. So they might not even know there are other backends available. Is that the case @icamps? If so, just installing plotly will make you use the plotly backend by default.
- Actually implement drawing 3D isosurfaces with matplotlib. I have not done so because I have 0 experience with plotting 3D things in matplotlib and I didn't think it would be worth it given that this can be done with the plotly and blender backends already, as well as other software such as VESTA or XCrysDen. The examples I saw at the time of matplotlib 3D displays didn't convince me aesthetically so I didn't see any reason to implement it :) @icamps would you be interested in it or you were just playing around and got the error?

Also, I'm curious, did 2D displays in matplotlib work as expected or you found some unexpected behavior?

**Comment by icamps** [comment]
Thanks @zerothi and @pfebrer .

I am having serious issues installing/using SISL ;(

I created a CONDA environment just for SISL with Python 3.9:
`conda create -n sisl python=3.9`

Then, installed SISL as:
`pip3 install -U git+https://github.com/zerothi/sisl.git` (using the pip3 for that environment)

In this way, the commands `print(sisl.__version__)` and `bands_plot = sisl.get_sile("BN.bands").plot()`, returned errors. Then, I deactivate the environment and installed SISL out of CONDA. After that, both commands worked as expected.

Even without installing `matplotlib` in my SISL environment, I could plot 2D graphics (bands and RHO), but not the 3D as reported in the first message.

I installed the  `plotly` package as suggested by running the command `conda install -c plotly plotly` inside my SISL environment but when trying to plot the 3D functions, nothing happens. When asking from the backends available using `plot.get_param("backend").options` returned only `matplotlib`.

Then, I deactivate all the CONDA environments and install `plotly` package directly, then everything is working well.

These are the package already installed in my SISL environment:
```
# packages in environment at /home/icamps/anaconda3/envs/sisl:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
plotly                    5.5.0                      py_0    plotly
python                    3.9.9           h543edf9_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                60.5.0           py39hf3d152e_0    conda-forge
sisl                      0.11.1.dev507+gb0511912          pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```
 I am a little confuse about why my SISL CONDA environment is not working properly and using packages from outside it.

@pfebrer , about your question _would you be interested in it or you were just playing around and got the error?_,  I am trying to use only one tool to analyze the SIESTA outputs. I don't have any particular interested in using any specific backend.

Which is the correct way to install SISL that I can use Jupyter notebooks?

**Comment by pfebrer** [comment]
Hmm what you are describing is a bit strange, so I'm going to try to guess what happens. 

Maybe this is a silly question but: are you sure that the jupyter notebook is using your `"sisl"` conda environment? That would be the only reason I can think of this could make sense :sweat_smile:. I.e. if you do

```python
import sys
print(sys.executable)
```

inside the jupyter notebook, does it print the location of your sisl environment python or a different one?

**Comment by icamps** [comment]
@pfebrer , after running `print(sys.executable)` I got:

`/usr/bin/python3`

This is really odd, as I installed the jupyter from my CONDA environment using `conda install -c conda-forge jupyterlab`.

**Comment by pfebrer** [comment]
Ok, then we have found the problem :) You have two options:
- Install `jupyter` in every environment that you want to use and then call `jupyter notebook` always from inside the environment. You say you have done it this way but I don't see `jupyter` in the packages list :sweat_smile: 
- You can also only have one jupyter installation and inform the jupyter installation that you have different environments. See https://anbasile.github.io/posts/2017-06-25-jupyter-venv/.

Note that this isn't at all related to `sisl`, so if you have been using jupyter like that you might have been using an unwanted python :)

**Comment by icamps** [comment]
Thanks @pfebrer . I will go through this issue to search what is happening because I install `jupyter` in each of my environments ;(.

**Comment by zerothi** [comment]
Great you found a solution!
