### ISSUE TITLE
Translate to unit cell - precision

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#448]
Don't you think we could insert an optional offset to this method?
```python
def translate2uc(..., offset=None):
    if isinstance(offset, float):
        d = np.ones(3) * offset
    elif isinstance(offset, list):
        d = np.array(offset)
    else:
        d = np.zeros(3)
    g = g.move(d)
    # do the existing stuff in this function
    g = g.move(-d)
    return g
```
I used this kind of shifts in two places in the geometries.

_Originally posted by @tfrederiksen in https://github.com/zerothi/sisl/issues/444#issuecomment-1059142958_

**Comment by zerothi** [comment]
I think we should first create a few more test cases to see if there are better routes, I have thought about:
- small shifts (as you have proposed!)
- using round with a "number of significant digits"
- instead of using fractional cells, then use a normalized fractional cell such that all numerics are done on the same scale

To solve this I would rather collect the set of difficult problems before trying to attack it without realizing what the root cause is.

**Comment by zerothi** [comment]
@tfrederiksen I have just tried to recreate some of the problems using simple fcc things, but I can't seem to find where this becomes a problem?

I tried inserting this (in `_finish_slab`, just before the actual move):
```python
    print('diff', g.translate2uc().fxyz - g.move(d).translate2uc().move(-d).fxyz)
```
and the difference of many of the fcc_slabs are maximally 4e-16?  
So what exactly is the problem?

**Comment by tfrederiksen** [comment]
I have not looked at this systematically. But when the atom coordinates are supposed to be *exactly* on the surface of the cell, this may not happen in practice because we have numbers like `alat ** 0.5` etc with rounding errors.

My simple-minded idea is just to shift slightly all atoms so that it is not ambiguous in which cell they are in. It is just cosmetic to make sure it is not random on which side of the cell the atoms appear (preferably always the sides closest to the origin).

**Comment by zerothi** [comment]
But by translating you are also *translating* the problem, no? if users like to have atoms close to the *other* side of the unit-cell, then the problem would occur for them?

**Comment by tfrederiksen** [comment]
Here is an example:
```python
g = sisl.geom.fcc_slab(4.08, 79, 111, layers=10, orthogonal=False) * (4, 4, 1)
g.plot(axes='xy')
```
![newplot](https://user-images.githubusercontent.com/11407069/156840069-892d898d-5f4b-4b31-994b-bc12f5ed06f5.png)
However, it does not look as "nice" (at least to me) if I do:
```python
g.translate2uc().plot(axes='xy')
```
![newplot-1](https://user-images.githubusercontent.com/11407069/156840188-c84c5960-b256-49d9-a9ec-856cc9fe82fb.png)

**Comment by zerothi** [comment]
I.e. I would still consider an atom on the *right* side of the unit-cell as being inside the unit-cell. 

Otherwise we should have an `atol=(lat_a, lat_b, lat_c)` which will be used something like this:
```python
from sisl import Geometry
import numpy as np

g = Geometry([[0, 0, 0], [1, 1, 0]], sc=[1, 1.1, 2.])
def translate2uc(geom, border_tol=(0, 0, 0)):
    btol = np.zeros([3])
    btol[:] = border_tol
    fxyz = geom.fxyz % 1
    xyz = fxyz @ geom.cell

    # with border-control
    flxyz = fxyz * geom.sc.length
    for axis, atol in enumerate(border_tol):
        if atol < 0:
            # we will move closest on the *left* side to the right
            flxyz[flxyz[:, axis] < -atol, axis] = 1.
        else:
            # we will move closest on the *right* side to the left
            flxyz[1 - flxyz[:, axis] < atol, axis] = 0.
    flxyz /= geom.sc.length
    print(xyz  - flxyz @ geom.cell)
translate2uc(g)
translate2uc(g, [-1e5, 1e5, 0])
translate2uc(g, [1e5, -1e5, 0])
```
This

**Comment by zerothi** [comment]
> Here is an example:
> 
> ```python
> g = sisl.geom.fcc_slab(4.08, 79, 111, layers=10, orthogonal=False) * (4, 4, 1)
> g.plot(axes='xy')
> ```
> 
> ![newplot](https://user-images.githubusercontent.com/11407069/156840069-892d898d-5f4b-4b31-994b-bc12f5ed06f5.png) However, it does not look as "nice" (at least to me) if I do:
> 
> ```python
> g.translate2uc().plot(axes='xy')
> ```
> 
> ![newplot-1](https://user-images.githubusercontent.com/11407069/156840188-c84c5960-b256-49d9-a9ec-856cc9fe82fb.png)

But they are still *in* the unit-cell? So I don't think the algorithm is wrong, it is just not what you expected? It is just very hard to figure out what is a numerical error (generally 1e-6

**Comment by tfrederiksen** [comment]
Yes, the algorithm is not *wrong*, I just don't like that it is more or less "random" on which side an atom falls.

Here is a particularly "ugly" cell
```python
g = sisl.geom.fcc_slab(4.08, 79, 111, layers=10, orthogonal=False) * (4, 10, 1)
g.translate2uc().plot(axes='xy')
```
![newplot-2](https://user-images.githubusercontent.com/11407069/156841131-78e9fc69-c321-4fb5-923a-8389ea288fd7.png)

**Comment by zerothi** [comment]
I would really try to refrain from using these tolerances, because you'll end up truncating positional data (depending on the tolerance levels.
And this is not the way to go since you are effectively shifting relative positions which the routines says nothing about. Therefore documenting such a feature in `translate2uc` would be cumbersome and it wouldn't be consistent. 
In fact, the move can be achieved with:
```python
geom.move(1e-5).translate2uc().move(-1e-5)
```
there is no need for the array.

**Comment by zerothi** [comment]
> ```python
> g = sisl.geom.fcc_slab(4.08, 79, 111, layers=10, orthogonal=False) * (4, 10, 1)
> g.translate2uc().plot(axes='xy')

agreed, but then do:
```python
g = fcc_slab(4.08, 79, 111, layers=10, orthogonal=False)
cell = g.sc.cell
dx = 1e-5
g = fcc_slab(4.08, 79, 111, layers=10, orthogonal=False) * (4, 10, 1)
gg = g.move(dx).translate2uc().move(-dx)
gg.plot(axes='xy').show()
print(gg.fxyz.min(), gg.fxyz.max())

gg = g.move(cell[0]-dx).move(dx).translate2uc().move(-dx)
print(gg.fxyz.min(), gg.fxyz.max())
gg.plot(axes='xy').show()
```
where both will be ugly. So it depends on the closeness of the border. And then incorporating it into the algorithms seems *random* in some sense. While the argument could help, it wouldn't be too much shorter than `move(.).translate2uc().move(.)` compared to `translate2uc(border_tol=(....))`, I wouldn't have the faintest idea from the method call what `border_tol` means... :(

Also, the above will print:
```
-2.8045478780612145e-16 0.9666666666666669
-4.002434220233952e-07 0.9999996337518494
```
meaning that there are negative numbers and they are *not* in the unit-cell... That would be somewhat counter intuitive, no? Or?

**Comment by tfrederiksen** [comment]
> ```python
> geom.move(1e-5).translate2uc().move(-1e-5)
> ```
> there is no need for the array.

OK, I'm happy with this solution. I just thought that it would more or less always be doing this "trick", since the first atom in the geometry is typically placed at the origin. This implies the possibility of having other atoms on the cell surface (and thus random side assignment).

**Comment by tfrederiksen** [comment]
> Also, the above will print:
> 
> ```
> -2.8045478780612145e-16 0.9666666666666669
> -4.002434220233952e-07 0.9999996337518494
> ```
> 
> meaning that there are negative numbers and they are _not_ in the unit-cell... That would be somewhat counter intuitive, no? Or?

Why do we actually sometimes get negative numbers in `translate2uc` in the first place from
```python
fxyz[:, axes] = fxyz[:, axes] % 1
```
? Shouldn't it always map to `[0, 1[`?

**Comment by zerothi** [comment]
> OK, I'm happy with this solution. I just thought that it would more or less always be doing this "trick", since the first atom in the geometry is typically placed at the origin. This implies the possibility of having other atoms on the cell surface (and thus random side assignment).

I agree that it might be a nice thing, but on the other hand the interface would *have* to be `translate2uc(border_tol=(0, 0, 0))` because this is the only way that we ensure that the coordinates are *in* the unit-cell. `0<=fxyz <=1`. So people would have to call it with appropriate arguments... Hmm. I really don't know what to do because I agree with the ugliness, but I don't like having a method which does something different than what it says it does... :weary: 

I have now extended the documentation a bit more? But would you like another argument to the method that allows this? I would just really advocate this defaulting to *not* do these things, and then it might be longer to type in the other thing?

**Comment by zerothi** [comment]
> > Also, the above will print:
> > ```
> > -2.8045478780612145e-16 0.9666666666666669
> > -4.002434220233952e-07 0.9999996337518494
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > meaning that there are negative numbers and they are _not_ in the unit-cell... That would be somewhat counter intuitive, no? Or?
> 
> Why do we actually sometimes get negative numbers in `translate2uc` in the first place from
> 
> ```python
> fxyz[:, axes] = fxyz[:, axes] % 1
> ```
> 
> ? Shouldn't it always map to `[0, 1[`?

It shouldn't, I have also just deleted the line where this was done. The numpy docs are pretty clear, `% 1` will always return with the same sign as the divisor. So I think it shouldn't happen, I just tried a few numbers, but nothing turned negative.

**Comment by tfrederiksen** [comment]
OK, let's simply stick with `geom.move(1e-5).translate2uc().move(-1e-5)`.

**Comment by zerothi** [comment]
And probably even `1e-9` would be ok with less impact on the final coordinates

**Comment by tfrederiksen** [comment]
Good! Will you implement this in `geom/basic.py` and `geom/surfaces.py`?

**Comment by zerothi** [comment]
> Good! Will you implement this in `geom/basic.py` and `geom/surfaces.py`?

Done! Used 1e-8, I think this should suffice for all cases!

**Comment by zerothi** [comment]
Thanks for the discussion!

**Comment by tfrederiksen** [comment]
Thanks to you too!

PS The trick is also used in `geom/basic.py`. Also, if `1e-8` is the default, maybe you want to update the example in `translate2uc` correspondingly?

**Comment by zerothi** [comment]
Done!

**Comment by zerothi** [comment]
Thanks for noticing!
