### ISSUE TITLE
Wrong `type` instance in `if` statement in `WideBandSE` class?

### ISSUE THREAD

**Issue by sofiasanz** [zerothi/sisl#469]
I am using the `WideBandSE` class, by passing a `sisl.Geometry` object and an `eta` (float) value.
I noticed that in this class, there is the following `if` statement:

```python
    def __init__(self, spgeom, eta):
        if isinstance(spgeom, _SparseGeometry):
            self._N = len(spgeom)
        else:
            self._N = spgeom
        self.eta = eta
```
Where the variable `self._N` should be the length of the geometry.  However, apparently the first `if` statement is `False`, since when I printed the variable `self._N` it returned the original `sisl.Geometry` object, i.e. doing `self._N = spgeom`, shouldn't it return the length of the geometry instead when `type(spgeom)=sisl.Geometry`?

**Version details**
```python
>>> print(sys.version)
3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0]
>>> print(sisl.__version__)
0.12.3.dev26+g2d976d3c

```

**Comment by zerothi** [comment]
The documentation specifies that self-energies should be passed a SparseGeometry (Hamiltonian or something like that). So I would rather not allow this. Simply because no other self-energy will allow one to do this (it makes no sense).

If you want this, then do:
```python
wse = WideBandSE(geom.no, eta)
```
instead.

**Comment by sofiasanz** [comment]
That make sense, I misunderstood it. Thanks!
