### ISSUE TITLE
`sisl.get_sile()` unable to read CHGCAR files with "unconventional" naming schemes

### ISSUE THREAD

**Issue by JeS24** [zerothi/sisl#473]
**Describe the bug**

I have a few CHGCAR files, that are named in the following fashion: `[Materials Project ID]_[Material]CHGCAR`. Some examples are:
```
mp-13982_Cd2Cu4Ge2S8CHGCAR
mp-20832_ZnIn2Te4CHGCAR
mp-23291_Pb4Cl8CHGCAR
mp-3614_KTaO3CHGCAR
```
Trying to read such files using `sisl.get_sile()` results in a `NotImplementedError`:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<path/to/proj/dir>/data.ipynb Cell 2' in <cell line: 2>()
      1 path = './data/chgcar/mp-23703_LiHCHGCAR'
----> 2 grid = sisl.get_sile(path)

File <path/to/venv>/lib/python3.9/site-packages/sisl/io/sile.py:294, in get_sile(file, *args, **kwargs)
    275 """ Retrieve an object from the global lookup table via filename and the extension
    276 
    277 Internally this is roughly equivalent to ``get_sile_class(...)()``.
   (...)
    291    function returns a random one.
    292 """
    293 cls = kwargs.pop('cls', None)
--> 294 sile = get_sile_class(file, *args, cls=cls, **kwargs)
    295 return sile(Path(str_spec(str(file))[0]), *args, **kwargs)

File <path/to/venv>/lib/python3.9/site-packages/sisl/io/sile.py:270, in get_sile_class(filename, *args, **kwargs)
    267     return clss
    269 except Exception as e:
--> 270     raise e

File <path/to/venv>/lib/python3.9/site-packages/sisl/io/sile.py:265, in get_sile_class(filename, *args, **kwargs)
    262             return clss
    264     if clss is None:
--> 265         raise NotImplementedError("Sile for file '{}' could not be found, "
    266                                   "possibly the file has not been implemented.".format(filename))
    267     return clss
    269 except Exception as e:

NotImplementedError: Sile for file './data/chgcar/mp-23703_LiHCHGCAR' could not be found, possibly the file has not been implemented.
```
However, if I rename the file to just `CHGCAR` or something like `[Name].CHGCAR`, then `get_sile()` works without issues. Renaming to `chgcar` or other case variations do not work, because `chgSileVASP`, that is applicable to this case, has a `_sile_rule` as follows:
```
chgSileVASP{case=True, suffix=CHGCAR, gzip=True,
  carSileVASP,
  chgSileVASP,
  SileVASP,
  Sile
}
```
Since `case == True`, `CHGCAR` must be uppercase in the filename.

Now, I can preprocess the filenames to include `CHGCAR` as a file extension, but the ideal expected behaviour here would be that `get_sile()` is able to identify the CHGCAR file and dispatch to the correct class as long as the string "CHGCAR" (in whichever case) is present in the file-name. And, any errors with the data format should be handled (or raised) by subsequent respective methods, if the need arises.

**Version details**
Run the below code and add to bug-report:
```python
import sys
print(sys.version)
import sisl
print(sisl.__version__)
```
Output:
```
3.9.9 (main, Dec 24 2021, 03:17:25) 
[GCC 11.2.0]
0.12.2
```

**Comment by zerothi** [comment]
Yeah, I don't know now whether it is a good idea to change the rules globally. They are after all more mandated by the respective codes rather than post-processing tools. To my knowledge VASP doesn't use any other file name than CHGCAR.

Two ways around it
1. As @pfebrer suggests, which forces a direct name of the sile
2. To not have a specific name, one could do:
```python
cls = None
if "CHGCAR" in filename:
    cls = sisl.io.get_sile_class("CHGCAR")
sile = sisl.io.get_sile(filename, cls=cls)
```
then you could basically have your own pre-rules that define the class. It all depends on what you want?

I think your suggestion about `chgcar` being in the filename would be a bit dangerous.

Probably what should be done is to make the sile-rules more flexible so users can change them in their currently running scripts. That would mean users can temporarily change rules for their own naming convention.
which should be a bit easier.

Would the above suggestions work?

**Comment by JeS24** [comment]
@pfebrer's suggestion is good. I have incorporated it into my code. Thanks.

> Probably what should be done is to make the sile-rules more flexible so users can change them in their currently running scripts. That would mean users can temporarily change rules for their own naming convention.

Also, this would be nice.
