### ISSUE TITLE
Possible bug in RealSpaceSI.real_space_coupling

### ISSUE THREAD

**Issue by AleksBL** [zerothi/sisl#475]
Hi,
Im getting some wierd couplings out of this class when the semi-infinite direction is in +A for example. I've patched it liked this:
```
SRSSE = RealSpaceSI(SE, Hsurf, 
                            ax_integrate, 
                            unfold = supercell,
                            dk = dk)
        if sisl_patch_1:
            from siesta_python.sisl_patches import Alt_real_space_coupling
            SRSSE.real_space_coupling = Alt_real_space_coupling.__get__(SRSSE, RealSpaceSI)
            SRSSE.initialize()
```
with 
```

def Alt_real_space_coupling(self, ret_indices=False):
    r""" Real-space coupling surafec where the outside fold into the surface real-space unit cell

    The resulting parent object only contains the inner-cell couplings for the elements that couple
    out of the real-space matrix.

    Parameters
    ----------
    ret_indices : bool, optional
       if true, also return the atomic indices (corresponding to `real_space_parent`) that encompass the coupling matrix

    Returns
    -------
    parent : object
        parent object only retaining the elements of the atoms that couple out of the primary unit cell
    atom_index : numpy.ndarray
        indices for the atoms that couple out of the geometry, only if `ret_indices` is true
    """
    k_ax = self._k_axes
    unfold   = self._unfold
    PC_semi = self.semi.spgeom1.copy()
    PC = self.surface.copy()
    for ax in range(3):
        PC      = PC.tile(self._unfold[ax], ax)
        PC_semi = PC_semi.tile(self._unfold[ax], ax)
    
    atom_idx = []
    for i in range(PC.na):
        if (np.linalg.norm(PC.xyz[i] - PC_semi.xyz, axis = 1)<0.001).any():
            atom_idx+=[i]
    atom_idx = np.array(atom_idx)
    no = PC.no
    assert (PC.nsc>1).sum() ==1
    assert (PC.nsc[PC.nsc>1]==3).all()
    
    Vkax1    = PC._csr.tocsr(0)[:,no:2*no].toarray()
    Vkax2    = PC._csr.tocsr(0)[:,2*no:3*no].toarray()
    idx1     = PC.o2a(np.unique(np.where(Vkax1!=0.)[0]))
    idx2     = PC.o2a(np.unique(np.where(Vkax2!=0.)[0]))
    U        = np.union1d
    atom_idx = U(atom_idx,U(idx1, idx2))
    
    PC = PC.sub(atom_idx)
    # Remove all out-of-cell couplings such that we only have inner-cell couplings.
    PC.set_nsc((1,1,1))
    
    if ret_indices:
        return PC, atom_idx
    return PC
```

With the other real_space_coupling:
(Purple buffer, light blue electrode atoms, dark blue and red Device atoms)
![image](https://user-images.githubusercontent.com/75378674/179217151-977a160c-3b50-4f21-a12f-16da3aa8324a.png)
With vanilla real_space_coupling
(Buffer atoms not defined here)
![image](https://user-images.githubusercontent.com/75378674/179217684-e7069ca9-e0b4-4519-b641-7625c925d1ca.png)

Do you know why this bug comes about?

**Comment by zerothi** [comment]
Hi, thanks!

Do you have a small example script for everything?that would be very helpful!

**Comment by zerothi** [comment]
The idea is that there are no coordinate checks in the routines that does the heavy lifting.
This is because the semi-infinite system can be pasted onto the surface regardless of their individual coordinates, as long as their relative coordinates are the same (this check is performed at initialization).

I also need to think about the k-point handling here, you are not using that one, I have to think whether that is correct or not...

**Comment by AleksBL** [comment]
[bug_reproduce.zip](https://github.com/zerothi/sisl/files/9127896/bug_reproduce.zip)

**Comment by zerothi** [comment]
Could you have a look, I am pretty sure it is fixed now, a stupid mistake by me, thanks for finding it!

**Comment by AleksBL** [comment]
It seems to be fixed :)

**Comment by zerothi** [comment]
Great! Thanks for the report!
