### ISSUE TITLE
Energy in Bond currents using SISL

### ISSUE THREAD

**Issue by harshiiiiiii** [zerothi/sisl#477]
Whenever I try to extract bond currents from .nc file, A energy is required to fill in "bond_current(elec, E, kavg=True, isc=None, only='out', orbitals=None, uc=False)"  I don't understand what this Energy means? Please help me resolve it. 
Additional information about the system - The system has a 0.65 eV band gap. When plotting transmission, the first peak on the right side of transmission lies at E = 0.075 eV and the second peak at E = 0.405 eV.
Thanks in advance

**Comment by zerothi** [comment]
Bond currents is an energy resolved quantity, just like the transmission and the density of states. The energies corresponds to the same in all cases.

**Comment by zerothi** [comment]
Bond currents is a bad customary wording, a better name would be bond transmission as they reflect the transmission at the given energy.

I'll close this as resolved in a week if I don't hear from you :)

**Comment by anshugaur** [comment]
Dear Nick,
I have a follow-up query:
As per sisl documentation, we can convert "bond currents" or "bond transmission" to vector currents. I assume that these would also be energy resolved. Do we also integrate these over the bias window to get actual vector currents that would sum up to give the total current at any applied bias?
Also, when performing the integration over the bias window, do we consider zero-bias transmission or transmission at the applied bias? (transmission at applied bias shows a positive shift in energy (by half the value of applied bias).

Thanks and regards,
Anshu

**Comment by zerothi** [comment]
> Dear Nick, I have a follow-up query: As per sisl documentation, we can convert "bond currents" or "bond transmission" to vector currents. I assume that these would also be energy resolved. Do we also integrate these over the bias window to get actual vector currents that would sum up to give the total current at any applied bias? Also, when performing the integration over the bias window, do we consider zero-bias transmission or transmission at the applied bias? (transmission at applied bias shows a positive shift in energy (by half the value of applied bias).

I don't follow your question in the last part? What is your line of thought?
Also, note I will change to follow #478
