### ISSUE TITLE
Rename bond current to transmission

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#478]
Should we rename `bond_current` to `bond_transmission` and let `bond_current` be the bias window integrated quantity?

**Comment by tfrederiksen** [comment]
Such a change sounds sensible to me.

**Comment by anshugaur** [comment]
Dear Nick,
 1.  Does sisl (ver. 0.12.2) calculate bond_current (bias window integrated quantity)? 
 2.  In sisl, do the extracted properties (orbital_current, bond_current, atom_current, and vector_current) have any dependence on the applied bias?
 3. The transmission (vs. energy) plots calculated from TBT at different biases (V) are shifted in energy by +V/2. (image attached). While comparing energy-resolved quantities (from sisl) at different applied biases, should we compare these values at the same energy or energies corresponding to the same transmission at applied bias?
 4.  Is it meaningful to compare these properties at a non-zero bias (point 3)?

We have a large multi-component system and we are interested to check which atoms (bonds_current, vector_current) contribute towards the current pathway leading to total current at non-zero bias.  The system contains ionic bonds and we see large bond_current (or bond_transmission) between atoms to different ionicity. However, our hypothesis is that at an applied bias (larger than the band gap), the current should be primarily through single atoms (or orbitals, of the same ionicity) which form the edge of the conduction band.

Thanks,
Anshu
![Transmission](https://user-images.githubusercontent.com/39057814/181221768-adb1b50e-2ebf-4a99-936d-236c1a68f3e6.png)

**Comment by zerothi** [comment]
1. No it is not an integrated quantity.
2. Why would they not be dependent on bias? And why would they be dependent on the bias? After that line of thought, what would you think is the right answer?
3. I don't understand what you mean? My response in the prior thread makes it clear that the transmission and bond transmissions are related.
4. Sure, why not? But you have to be more careful at what you compare. Interpreting this is your responsibility as the researcher.

**Comment by zerothi** [comment]
This was fixed in #479
