### ISSUE TITLE
Can PHtrans be used for simulation of Interfacial Phonon Transport

### ISSUE THREAD

**Issue by davy12344** [zerothi/sisl#485]
Dear developer:

I am studying how to use sisl and PHtrans. 
I an intended to use Green function to calculate the phonon transport at Si/Ge surface, such as  this paper "DOI: 10.1115/1.2709656". However, up to now, I didnot find any example about calculate the surface related phonon transport with  sisl and PHtrans. I am not sure whether sisl and PHtrans can do that? If it can do, should I construct three part regions: Si region, Si and Ge device region(including surface), Ge region and then calculate the FC of these region ?

Looking forward to your reply.
Thanks
Yongheng Li

**Comment by zerothi** [comment]
PHtrans is an elastic phonon transport tool.

All it requires is the dynamical matrices that couples the Si/Ge surface to the respective pristine regions. If you can extract this dynamical matrix, then PHtrans can be used to calculate the transport.

Please do note that dynamical matrices are generally rather long-ranging. Your recipe looks correct, one Si region (1st electrode), one Ge region (2nd electrode) and a full device with both electrodes *and* the connecting region. Probably you need to converge the length between the surface and the respective electrodes.

**Comment by zerothi** [comment]
I will close this as it is not really a sisl issue, rather a phtrans question. :)
