### ISSUE TITLE
Sign of the y-component of spin moments may be wrong

### ISSUE THREAD

**Issue by juijan** [zerothi/sisl#486]
Hey Nick,

is it possible that the y-component of the spin moments is incorrectly calculated?

It looks to me like we should add a minus, because:

$$\eqalign{
\mathbf{S}_i^y 
   &= Re( \langle \psi_i | \boldsymbol\sigma_y \mathbf S | \psi_i \rangle ) \\
   &= Re( \left(\matrix{\langle \psi_i^{\uparrow} | \cr \langle \psi_i^{\downarrow}| } \right)
             \left(\matrix{ 0 & -i \mathbf S \cr i \mathbf S & 0} \right)
             \left(\matrix{| \psi_i^{\uparrow}\rangle \cr | \psi_i^{\downarrow}\rangle } \right)\\
   &= Re(- i \langle \psi_i^{\uparrow} |  S | \psi_i^{\downarrow} \rangle + i \langle \psi_i^{\downarrow} |  S | \psi_i^{\uparrow} \rangle ) \\
   &= Im(  \langle \psi_i^{\uparrow} |  S | \psi_i^{\downarrow} \rangle - \langle \psi_i^{\downarrow} |  S | \psi_i^{\uparrow} \rangle) \\
   &= D2.imag - D1.imag
}$$

https://github.com/zerothi/sisl/blob/3f11290ec7dd11e87c4b04f6eca24e568b11ed4d/sisl/physics/electron.py#L410-L417
https://github.com/zerothi/sisl/blob/3f11290ec7dd11e87c4b04f6eca24e568b11ed4d/sisl/physics/electron.py#L427-L432

**Comment by zerothi** [comment]
Did you check with siesta? Thanks!

**Comment by juijan** [comment]
I did, and now I have yet another suggestion.

If I understand it correctly I believe this is implemented in the [spin_texture](https://gitlab.com/siesta-project/siesta/-/blob/master/Util/COOP/spin_texture.f90) utility:

$$\eqalign{
\mathbf{S}_i^y= - Im(\langle \psi_i^{\uparrow} |  S | \psi_i^{\downarrow} \rangle +  \langle \psi_i^{\downarrow} |  S | \psi_i^{\uparrow}\rangle) = - D2.imag - D1.iamg
}$$

**Comment by zerothi** [comment]
Your equation in the initial question looks correct, i believe that the single minus sign in spin texture is due to siestas convention on the off-diagonal imaginary part in the spin box. But I have to double check, now we are at it.

**Comment by juijan** [comment]
A colleague shared spin texture calculated with the spin-texture utility and the TSHS files for few-layer Bi<sub>2</sub>Se<sub>3</sub>.
When I use the current version of `sisl`, I can not reproduce the spin-texture, with the additional minus I get the same result, which match what we can find the the literature.

1. Literature (Zhang, Jia, et al. Physical Review B 94.1 (2016): 014435)
![SpinTexture_Zhang-PRB-2016](https://user-images.githubusercontent.com/39985259/191729158-15a984ba-a5d1-47b8-8ce4-096ad1b6e769.png)

3. SIESTA spin_texture utlility
![fig-spin-texture-b235](https://user-images.githubusercontent.com/39985259/191728844-5d562fb3-9d6e-47b2-85b1-6975479736d3.png)
![fig-spin-texture-b236](https://user-images.githubusercontent.com/39985259/191728848-b7e39ee9-edaa-4de4-8d7e-8651d99ecdb0.png)

4. sisl-pre-fix
![test2](https://user-images.githubusercontent.com/39985259/191728605-1fecdee9-dc93-4720-9ac1-c233206582e6.svg)

5. sisl-with-fix
![test](https://user-images.githubusercontent.com/39985259/191728617-1b3da7ef-2886-4a51-8dcf-9f7d3ac62e66.svg)
