### ISSUE TITLE
Reorder honeycomb lattice vectors?

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#488]
I used `sisl.geom.graphene` to write a simple POSCAR file of graphene. However, VASP complains about this POSCAR (and quits!) because the lattice vectors do not form a right-handed system:
```
ERROR: the triple product of the basis vectors 
 is negative exchange two basis vectors
```
Therefore, what do you think about permanently interchanging the first two lattice vectors of `honeycomb` in sisl? Perhaps other codes will also make this complaint?

**Comment by zerothi** [comment]
Sounds like a good idea. What about the other, fcc, diamond etc. Perhaps we should have a check for all geom creation classes that checks the positive triple product, that would be easier

**Comment by tfrederiksen** [comment]
I actually checked most geometries and only `honeycomb` seems problematic (well, and `graphene`/`bilayer` by extension):
```python
import sisl
import numpy as np

sg = sisl.geom

def positive_vol(geom):
    cell = geom.cell
    vol = np.dot(cell[0, :], np.cross(cell[1, :], cell[2, :]))
    return vol > 0

d = 3.2
a = 'C'
g = [sg.sc(d, a),
     sg.bcc(d, a), sg.fcc(d, a), sg.hcp(d, a), sg.rocksalt(d, a),
     sg.diamond(),
     sg.honeycomb(d, 'C'), sg.graphene(), sg.bilayer(), # these three are left-handed
     sg.nanoribbon(7, d, a), sg.agnr(7), sg.zgnr(7),
     sg.nanotube(d),
     sg.fcc_slab(d, a, miller=100), sg.fcc_slab(d, a, miller=110), sg.fcc_slab(d, a, miller=111),
     sg.bcc_slab(d, a, miller=100), sg.bcc_slab(d, a, miller=110), sg.bcc_slab(d, a, miller=111),
     ]

for gi in g:
    print(positive_vol(gi))
```

**Comment by tfrederiksen** [comment]
> Sounds like a good idea. What about the other, fcc, diamond etc. Perhaps we should have a check for all geom creation classes that checks the positive triple product, that would be easier

I noticed that the supercell function `volume` returns the absolute value of the triple product, hence ignoring handed-ness. One could also simply keep the sign here.

**Comment by zerothi** [comment]
> I noticed that the supercell function `volume` returns the absolute value of the triple product, hence ignoring handed-ness. One could also simply keep the sign here.

I think that is a bad idea, users may be indifferent about this choice. Users should be able to do what they want here I think. But I think keeping a strict order in the geometry creation classes would be great.

Fingers crossed that this won't mess up things downstream... ;)

However, doing this messes up the `bilayer` construction? At least the test for bilayer fails if this is done?
I can't figure out where we should change the cells...

**Comment by tfrederiksen** [comment]
> However, doing this messes up the `bilayer` construction? At least the test for bilayer fails if t
his is done?
> I can't figure out where we should change the cells...

I played a bit around and believe the problem lies here:
https://github.com/zerothi/sisl/blob/a14a79df3d9a7dec24b5cbcac7dcec6136bb6162/sisl/geom/bilayer.py#L79-L81
With interchanged lattice vectors, `n` should be the smaller integer of the two.

Additionally, to recover the same overall orientation of the bilayer as before, the final rotation should now be in the opposite direction here:
https://github.com/zerothi/sisl/blob/a14a79df3d9a7dec24b5cbcac7dcec6136bb6162/sisl/geom/bilayer.py#L156

For me these changes seem to work. Note that the precise coordinates of atoms in the cell are not the same as before
 (the structure appears rotated by 180 deg), but the new construction is valid and, importantly, now right-handed.

**Comment by zerothi** [comment]
I think it is there now, sorry for not testing this more on my end... I am still very briefly on the computer... :(

**Comment by tfrederiksen** [comment]
Looks good to me.
