### ISSUE TITLE
Inconsistent electronic spectrum with the SIESTA output

### ISSUE THREAD

**Issue by oroszl** [zerothi/sisl#490]
**Describe the bug**

**Reproducable code**
```python
import sisl
fdf=sisl.get_sile("PATH_TO_FDF")
ham=fdf.read_hamiltonian()
w=ham.eigh()+fdf.read_fermi_level().data[0]
```
The contents of the array `w` are quite different form the contents of the `.EIG` file. The difference is not a systematic shift, i.e. it is not just about shifting the spectrum with EF, and it is in the order of 0.1eV!! 
You can fid the full scf calculation at this [link](https://www.dropbox.com/s/14aabnvvxffon47/Cr_trimer_relaxed.zip?dl=0).

**Version details**

Two wildly different version/environment produce the same issue. 

3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:28:35) [GCC 9.4.0]
0.0.0.dev+eacb8351ff416ad9f7f93732777c3d7931c5f711

3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
0.10.0

**Comment by zerothi** [comment]
Thanks for reporting this.

I have just tried with my Siesta version (currently latest on master) and the latest sisl version. I have no problems comparing the eigenvalues...

I also tried your linked files with the latest sisl version, and there it failed. So my assumption would be that your Siesta version is having some problems.

Also, the version of siesta you are using is more than 1.5 years old. I would heavily suggest you update it.
1) use 4.1.5
2) use the latest development version, lots of things has improved/fixed :)

**Comment by oroszl** [comment]
Thanks @zerothi it seems that running the fdf with 4.1.5 resolved the issue of different energies in sisl and from siesta output.
However, it seems that certain sisl versions have problems with reading the hamiltonian now. 
I could read in the hamiltonian from 0.10.0 but not with 0.12.0. It did not give an error, but seem to go into an infinite loop. 
I will upload my new files once I am back in front of a computer.

**Comment by zerothi** [comment]
Did you check the changelogs of sisl? Probably that is discussed there.  
I must admit I see no point in using 0.10.0, it is old and sisl is quickly evolving due to user requests and updates in siesta. So I would not be surprised! :)

**Comment by oroszl** [comment]
I think we can close this issue, but I will open a new one for the read issue.
