### ISSUE TITLE
Bond orders from `DensityMatrix`

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#507]
**Describe the feature**
The Mulliken and Löwdin bond orders (BO), between pairs of atoms A and B, are defined through the off-diagonal populations derived from the density matrix. According to the ORCA manual one defines:
$$BO^M_{A B} = \cancel{2 \sum_{\mu \in A} \sum_{\nu \in B} \rho_{\mu\nu} S_{\mu\nu}}$$
$$BO^L_{A B} = \sum_{\mu \in A} \sum_{\nu \in B} (\rho^L_{\mu\nu})^2 $$

**Comment by zerothi** [comment]
What about nc/soc... Does a bond order with a spin configuration make sense or is it just the density sum?

**Comment by tfrederiksen** [comment]
> What about nc/soc... Does a bond order with a spin configuration make sense or is it just the density sum?

The ground-state density matrix is defined as $\rho = | \psi \rangle\langle \psi | = \sum_n | \phi_n  \rangle n_F(E_n) \langle \phi_n |$ in terms of all single-particle states $\phi_n$ with energies $E_n$. This should hold also in nc/soc descriptions, no?

**Comment by tfrederiksen** [comment]
I don't know, but if you can write the density matrix as a simple sum over spin components I guess one can define also the spin-resolved populations/bond orders.

**Comment by zerothi** [comment]
The equations above, it means that orthogonal basis sets always has a bond-order of 0? No?

**Comment by tfrederiksen** [comment]
> The equations above, it means that orthogonal basis sets always has a bond-order of 0? No?

No, the bond order is certainly not generally zero in orthogonal bases. But I see your point about the overlap matrix appearing in the first expression. Will have to check.

**Comment by tfrederiksen** [comment]
I think the corresct expression should be
$$BO^M_{A B} = 2 \sum_{\mu \in A} \sum_{\nu \in B} \sum_i\rho_{\mu i} S_{i\nu}$$

**Comment by tfrederiksen** [comment]
Foun this https://www.sciencedirect.com/topics/chemistry/bond-order, with an excerpt from https://www.sciencedirect.com/science/article/abs/pii/S0898883818300473

**Comment by zerothi** [comment]
> I think the correct expression should be BOABM=2∑μ∈A∑ν∈B[ρS]μν

Yes, ok this makes more sense.

**Comment by zerothi** [comment]
https://pubs.acs.org/doi/full/10.1021/acs.jctc.2c00334 could be useful as well

**Comment by zerothi** [comment]
Another one, this one seems to be existing as well:

    K.B. Wiberg,
    Application of the Pople-Santry=Segal CNDO Method to the Cyclopropylcarbinyl and Cyclobutyl Cation and to Bicyclobutane,
    Tetrahedron, Vol. 24, pp. 1083-1096, 1966.

https://docs.eyesopen.com/toolkits/python/quacpactk/bondordertheory.html

**Comment by zerothi** [comment]
> Do you think it makes sense also to compute these bond orders between orbitals? I'm thinking about it to have some idea of the hybridization that is taking place or to have more insight into the directionality of a bond between two atoms.

Between orbitals, wouldn't that just be the mulliken overlap population? One could do atom and single orbital, but orbital - orbital wouldn't make sense... No?

**Comment by pfebrer** [comment]
> Between orbitals, wouldn't that just be the mulliken overlap population?

Maybe, I didn't know this existed :)

**Comment by zerothi** [comment]
I have understood it as though bond-orders are *only* charge aware. Hence, the calculation works the same for polarized as for NC/SOC. One should sum the density (and neglect any spin).

With #672 implementing the option of retrieving the spin-resolved bond-order, I don't think it really makes any sense. This is currently mainly available for end-users to access the alpha/beta channels bond-orders. Perhaps this should be revised later, but for now I'll just have it there...
