### ISSUE TITLE
Group common data in Siles into a property

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#509]
**Describe the feature**

In #500 and in the tbtncSileTBtrans we added the properties `no` and `na` etc. I think these should be removed since they are not sile specific but should be queried in some other way.

Some ideas:
- some property that returns a dictionary or namedtuple
    - this property could be named `info`
    - `settings` (so other things could also be added, like options etc.)
    - ?

The main reason is that the complexity and handling of many properties that are more geometry specific, or setting specific seems to bloat the classes.

Comments?

**Comment by tfrederiksen** [comment]
How do you imagine that one should access the `no`/`na` quantities within a sile? With calls to `self.info["no"]`? And how/where should the dictionary be created?

**Comment by tfrederiksen** [comment]
OK, I see. So a generic `PropertyDict` to all siles where quantities/settings/info should be registered?

**Comment by zerothi** [comment]
That would be my idea, it reduces the amount of methods, and the documentation for that entry should just be sufficient :)
