### ISSUE TITLE
NetCDF: Start+count exceeds dimension bound

### ISSUE THREAD

**Issue by Kulka21** [zerothi/sisl#525]
I get the following error:
Running for dH = [M_1.dH.nc](http://m_1.dh.nc/)
Error occured in NCDF:
NetCDF: Start+count exceeds dimension bound
Status number: -57
ncdf: Stopped due to error in NetCDF file
Do you have any idea where it may come from?

**Comment by zerothi** [comment]
How was the file created? I would try and delete the file, then recreate it and see if it works.

**Comment by Kulka21** [comment]
Didn't help

**Comment by Kulka21** [comment]
I think that the problem is with creating the dH.nc files for non-zero magnetic field. The files that I am generating are very small (around 20KB, while for zero magnetic field is around 2MB). What do you think?

**Comment by zerothi** [comment]
I don't know, how are you creating them, if I can't reproduce it may be very difficult to help.

**Comment by zerothi** [comment]
you are creating the `dH` file incorrectly, you should use the device region geometry, not the electrode region.

**Comment by Kulka21** [comment]
Ok, thank you :)
