### ISSUE TITLE
Cut

### ISSUE THREAD

**Issue by KitchenSong** [zerothi/sisl#53]
I construct a supercell and try to generate the matrix needed for phtrans calculation. When I try to cut the structure for the electrode from a BBB structure into just B, I met this problem and cannot get rid of it by all possible means. I hope you can offer some suggestions to correct this. Thanks.

File "ex48.py", line 418, in <module>
    el = dyn1.cut(3,2,seg=1)
  File "/home/qichen/.local/lib/python2.7/site-packages/sisl-0.9.2+389-py2.7-linux-x86_64.egg/sisl/sparse_geometry.py", line 1378, in cut
    if issubclass(w[-1].category, SislWarning):
NameError: global name 'SislWarning' is not defined

**Comment by zerothi** [comment]
Thanks for your feedback.

I have fixed the code in the latest commit 4e48b7ea.

It however has another problem related

**Comment by KitchenSong** [comment]
I can run the script now. But seems that the final .nc file still contains 3B atoms instead of B, when I do the following.
tmp = sisl.get_sile('DEVICE_gaas.nc')
tmp1 = tmp.read_geometry()
print tmp1.xyz

**Comment by zerothi** [comment]
Could you post the full script? I.e. as I wrote previously cutting a structure requires the initial structure to be _tiled_ (see Geometry.tile)

**Comment by KitchenSong** [comment]
Okay.. I find that the final coordinates provided by GULP is changed such that the z transport position is not longer ordered. But just a general concern, when dealing with
 #!/usr/bin/env python

# This example relies on GULP being installed.

# It calculates the dynamical matrix for ZZ-oriented graphene
# and afterward it can write the dynamical matrix to be processed by
# PHtrans for transport properties.

import sisl
import os

# opti conv 	Set flags for constant volume optimisation.
with open('gaas.gin', 'w') as f:
    f.write("""opti cellonly dist full nosymmetry phon dynamical_matrix
cutd 3.0

cell 
8.324642  4.8062220 188.39512 90 90 90

cartesian 192
Ga  core      4.162321     2.403111     0.000000  0 1 0 1 1 1
 Ga  core      0.000000     0.000000     0.000000  0 1 0 1 1 1
 As  core      4.162321     2.403111     2.942732  0 1 0 1 1 1
 As  core      0.000000     0.000000     2.942732  0 1 0 1 1 1
 Ga  core      1.387468     2.403111     3.924270  0 1 0 1 1 1
 Ga  core      5.549789     0.000000     3.924270  0 1 0 1 1 1
 As  core      1.387468     2.403111     6.868886  0 1 0 1 1 1
 As  core      5.549789     0.000000     6.868886  0 1 0 1 1 1
 Ga  core      6.937174     2.403111     7.850424  0 1 0 1 1 1
 Ga  core      2.774853     0.000000     7.850424  0 1 0 1 1 1
 As  core      6.937174     2.403111    10.793156  0 1 0 1 1 1
 As  core      2.774853     0.000000    10.793156  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    11.774695  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    11.774695  0 1 0 1 1 1
 As  core      4.162321     2.403111    14.719311  0 1 0 1 1 1
 As  core      0.000000     0.000000    14.719311  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    15.698965  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    15.698965  0 1 0 1 1 1
 As  core      1.387468     2.403111    18.643581  0 1 0 1 1 1
 As  core      5.549789     0.000000    18.643581  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    19.625120  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    19.625120  0 1 0 1 1 1
 As  core      6.937174     2.403111    22.567852  0 1 0 1 1 1
 As  core      2.774853     0.000000    22.567852  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    23.549390  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    23.549390  0 1 0 1 1 1
 As  core      4.162321     2.403111    26.492120  0 1 0 1 1 1
 As  core      0.000000     0.000000    26.492120  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    27.473661  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    27.473661  0 1 0 1 1 1
 As  core      1.387468     2.403111    30.418276  0 1 0 1 1 1
 As  core      5.549789     0.000000    30.418276  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    31.399814  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    31.399814  0 1 0 1 1 1
 As  core      6.937174     2.403111    34.342547  0 1 0 1 1 1
 As  core      2.774853     0.000000    34.342547  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    35.324085  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    35.324085  0 1 0 1 1 1
 As  core      4.162321     2.403111    38.266815  0 1 0 1 1 1
 As  core      0.000000     0.000000    38.266815  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    39.248356  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    39.248356  0 1 0 1 1 1
 As  core      1.387468     2.403111    42.192971  0 1 0 1 1 1
 As  core      5.549789     0.000000    42.192971  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    43.174509  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    43.174509  0 1 0 1 1 1
 As  core      6.937174     2.403111    46.117242  0 1 0 1 1 1
 As  core      2.774853     0.000000    46.117242  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    47.098780  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    47.098780  0 1 0 1 1 1
 As  core      4.162321     2.403111    50.041510  0 1 0 1 1 1
 As  core      0.000000     0.000000    50.041510  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    51.023051  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    51.023051  0 1 0 1 1 1
 As  core      1.387468     2.403111    53.967668  0 1 0 1 1 1
 As  core      5.549789     0.000000    53.967668  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    54.949204  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    54.949204  0 1 0 1 1 1
 As  core      6.937174     2.403111    57.891934  0 1 0 1 1 1
 As  core      2.774853     0.000000    57.891934  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    58.873475  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    58.873475  0 1 0 1 1 1
 As  core      4.162321     2.403111    61.816205  0 1 0 1 1 1
 As  core      0.000000     0.000000    61.816205  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    62.797746  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    62.797746  0 1 0 1 1 1
 As  core      1.387468     2.403111    65.742363  0 1 0 1 1 1
 As  core      5.549789     0.000000    65.742363  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    66.723899  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    66.723899  0 1 0 1 1 1
 As  core      6.937174     2.403111    69.666629  0 1 0 1 1 1
 As  core      2.774853     0.000000    69.666629  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    70.648170  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    70.648170  0 1 0 1 1 1
 As  core      4.162321     2.403111    73.590900  0 1 0 1 1 1
 As  core      0.000000     0.000000    73.590900  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    74.572441  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    74.572441  0 1 0 1 1 1
 As  core      1.387468     2.403111    77.517058  0 1 0 1 1 1
 As  core      5.549789     0.000000    77.517058  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    78.498594  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    78.498594  0 1 0 1 1 1
 As  core      6.937174     2.403111    81.441324  0 1 0 1 1 1
 As  core      2.774853     0.000000    81.441324  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    82.422865  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    82.422865  0 1 0 1 1 1
 As  core      4.162321     2.403111    85.365595  0 1 0 1 1 1
 As  core      0.000000     0.000000    85.365595  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    86.347136  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    86.347136  0 1 0 1 1 1
 As  core      1.387468     2.403111    89.291753  0 1 0 1 1 1
 As  core      5.549789     0.000000    89.291753  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    90.273289  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    90.273289  0 1 0 1 1 1
 As  core      6.937174     2.403111    93.216019  0 1 0 1 1 1
 As  core      2.774853     0.000000    93.216019  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    94.197560  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    94.197560  0 1 0 1 1 1
 As  core      4.162321     2.403111    97.140290  0 1 0 1 1 1
 As  core      0.000000     0.000000    97.140290  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    98.121826  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    98.121826  0 1 0 1 1 1
 As  core      6.937174     2.403111   101.066443  0 1 0 1 1 1
 As  core      2.774853     0.000000   101.066443  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   102.047989  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   102.047989  0 1 0 1 1 1
 As  core      1.387468     2.403111   104.990720  0 1 0 1 1 1
 As  core      5.549789     0.000000   104.990720  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   105.972255  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   105.972255  0 1 0 1 1 1
 As  core      4.162321     2.403111   108.914985  0 1 0 1 1 1
 As  core      0.000000     0.000000   108.914985  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   109.896521  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   109.896521  0 1 0 1 1 1
 As  core      6.937174     2.403111   112.841138  0 1 0 1 1 1
 As  core      2.774853     0.000000   112.841138  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   113.822684  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   113.822684  0 1 0 1 1 1
 As  core      1.387468     2.403111   116.765415  0 1 0 1 1 1
 As  core      5.549789     0.000000   116.765415  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   117.746950  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   117.746950  0 1 0 1 1 1
 As  core      4.162321     2.403111   120.689680  0 1 0 1 1 1
 As  core      0.000000     0.000000   120.689680  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   121.671216  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   121.671216  0 1 0 1 1 1
 As  core      6.937174     2.403111   124.615833  0 1 0 1 1 1
 As  core      2.774853     0.000000   124.615833  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   125.597379  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   125.597379  0 1 0 1 1 1
 As  core      1.387468     2.403111   128.540110  0 1 0 1 1 1
 As  core      5.549789     0.000000   128.540110  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   129.521645  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   129.521645  0 1 0 1 1 1
 As  core      4.162321     2.403111   132.464375  0 1 0 1 1 1
 As  core      0.000000     0.000000   132.464375  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   133.445911  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   133.445911  0 1 0 1 1 1
 As  core      6.937174     2.403111   136.390528  0 1 0 1 1 1
 As  core      2.774853     0.000000   136.390528  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   137.372074  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   137.372074  0 1 0 1 1 1
 As  core      1.387468     2.403111   140.314805  0 1 0 1 1 1
 As  core      5.549789     0.000000   140.314805  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   141.296340  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   141.296340  0 1 0 1 1 1
 As  core      4.162321     2.403111   144.239070  0 1 0 1 1 1
 As  core      0.000000     0.000000   144.239070  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   145.220606  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   145.220606  0 1 0 1 1 1
 As  core      6.937174     2.403111   148.165223  0 1 0 1 1 1
 As  core      2.774853     0.000000   148.165223  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   149.146769  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   149.146769  0 1 0 1 1 1
 As  core      1.387468     2.403111   152.089500  0 1 0 1 1 1
 As  core      5.549789     0.000000   152.089500  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   153.071035  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   153.071035  0 1 0 1 1 1
 As  core      4.162321     2.403111   156.013765  0 1 0 1 1 1
 As  core      0.000000     0.000000   156.013765  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   156.995301  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   156.995301  0 1 0 1 1 1
 As  core      6.937174     2.403111   159.939918  0 1 0 1 1 1
 As  core      2.774853     0.000000   159.939918  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   160.921464  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   160.921464  0 1 0 1 1 1
 As  core      1.387468     2.403111   163.864195  0 1 0 1 1 1
 As  core      5.549789     0.000000   163.864195  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   164.845730  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   164.845730  0 1 0 1 1 1
 As  core      4.162321     2.403111   167.788460  0 1 0 1 1 1
 As  core      0.000000     0.000000   167.788460  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   168.769996  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   168.769996  0 1 0 1 1 1
 As  core      6.937174     2.403111   171.714613  0 1 0 1 1 1
 As  core      2.774853     0.000000   171.714613  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   172.696159  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   172.696159  0 1 0 1 1 1
 As  core      1.387468     2.403111   175.638890  0 1 0 1 1 1
 As  core      5.549789     0.000000   175.638890  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   176.620425  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   176.620425  0 1 0 1 1 1
 As  core      4.162321     2.403111   179.563155  0 1 0 1 1 1
 As  core      0.000000     0.000000   179.563155  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   180.544691  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   180.544691  0 1 0 1 1 1
 As  core      6.937174     2.403111   183.489308  0 1 0 1 1 1
 As  core      2.774853     0.000000   183.489308  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   184.470854  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   184.470854  0 1 0 1 1 1
 As  core      1.387468     2.403111   187.413585  0 1 0 1 1 1
 As  core      5.549789     0.000000   187.413585  0 1 0 1 1 1
 
sw2
Ga As 4.6264 1.0 35.7999  0.0 3.8416
sw3
Ga As As 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830
As Ga Ga 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830
""")

# https://journals.aps.org/prb/pdf/10.1103/PhysRevB.83.174304

with open('gaas_s.gin', 'w') as f:
    f.write("""opti cellonly dist full nosymmetry phon dynamical_matrix
cutd 3.0

cell
 8.324642  4.8062220 35.3240850000000 90 90 90
cartesian 36
Ga  core      4.162321     2.403111    47.098780  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    47.098780  0 1 0 1 1 1
 As  core      4.162321     2.403111    50.041510  0 1 0 1 1 1
 As  core      0.000000     0.000000    50.041510  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    51.023051  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    51.023051  0 1 0 1 1 1
 As  core      1.387468     2.403111    53.967668  0 1 0 1 1 1
 As  core      5.549789     0.000000    53.967668  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    54.949204  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    54.949204  0 1 0 1 1 1
 As  core      6.937174     2.403111    57.891934  0 1 0 1 1 1
 As  core      2.774853     0.000000    57.891934  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    58.873475  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    58.873475  0 1 0 1 1 1
 As  core      4.162321     2.403111    61.816205  0 1 0 1 1 1
 As  core      0.000000     0.000000    61.816205  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    62.797746  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    62.797746  0 1 0 1 1 1
 As  core      1.387468     2.403111    65.742363  0 1 0 1 1 1
 As  core      5.549789     0.000000    65.742363  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    66.723899  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    66.723899  0 1 0 1 1 1
 As  core      6.937174     2.403111    69.666629  0 1 0 1 1 1
 As  core      2.774853     0.000000    69.666629  0 1 0 1 1 1
 Ga  core      4.162321     2.403111    70.648170  0 1 0 1 1 1
 Ga  core      0.000000     0.000000    70.648170  0 1 0 1 1 1
 As  core      4.162321     2.403111    73.590900  0 1 0 1 1 1
 As  core      0.000000     0.000000    73.590900  0 1 0 1 1 1
 Ga  core      1.387468     2.403111    74.572441  0 1 0 1 1 1
 Ga  core      5.549789     0.000000    74.572441  0 1 0 1 1 1
 As  core      1.387468     2.403111    77.517058  0 1 0 1 1 1
 As  core      5.549789     0.000000    77.517058  0 1 0 1 1 1
 Ga  core      6.937174     2.403111    78.498594  0 1 0 1 1 1
 Ga  core      2.774853     0.000000    78.498594  0 1 0 1 1 1
 As  core      6.937174     2.403111    81.441324  0 1 0 1 1 1
 As  core      2.774853     0.000000    81.441324  0 1 0 1 1 1
 

sw2
Ga As 4.6264 1.0 35.7999  0.0 3.8416
sw3
Ga As As 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830
As Ga Ga 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830""")

with open('gaas_d.gin', 'w') as f:
    f.write("""opti cellonly dist full nosymmetry phon dynamical_matrix
cutd 3.0

cell
 8.324642  4.8062220 35.3240850000000 90 90 90
cartesian 36
Ga  core      4.162321     2.403111   105.972255  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   105.972255  0 1 0 1 1 1
 As  core      4.162321     2.403111   108.914985  0 1 0 1 1 1
 As  core      0.000000     0.000000   108.914985  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   109.896521  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   109.896521  0 1 0 1 1 1
 As  core      6.937174     2.403111   112.841138  0 1 0 1 1 1
 As  core      2.774853     0.000000   112.841138  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   113.822684  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   113.822684  0 1 0 1 1 1
 As  core      1.387468     2.403111   116.765415  0 1 0 1 1 1
 As  core      5.549789     0.000000   116.765415  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   117.746950  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   117.746950  0 1 0 1 1 1
 As  core      4.162321     2.403111   120.689680  0 1 0 1 1 1
 As  core      0.000000     0.000000   120.689680  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   121.671216  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   121.671216  0 1 0 1 1 1
 As  core      6.937174     2.403111   124.615833  0 1 0 1 1 1
 As  core      2.774853     0.000000   124.615833  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   125.597379  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   125.597379  0 1 0 1 1 1
 As  core      1.387468     2.403111   128.540110  0 1 0 1 1 1
 As  core      5.549789     0.000000   128.540110  0 1 0 1 1 1
 Ga  core      4.162321     2.403111   129.521645  0 1 0 1 1 1
 Ga  core      0.000000     0.000000   129.521645  0 1 0 1 1 1
 As  core      4.162321     2.403111   132.464375  0 1 0 1 1 1
 As  core      0.000000     0.000000   132.464375  0 1 0 1 1 1
 Ga  core      6.937174     2.403111   133.445911  0 1 0 1 1 1
 Ga  core      2.774853     0.000000   133.445911  0 1 0 1 1 1
 As  core      6.937174     2.403111   136.390528  0 1 0 1 1 1
 As  core      2.774853     0.000000   136.390528  0 1 0 1 1 1
 Ga  core      1.387468     2.403111   137.372074  0 1 0 1 1 1
 Ga  core      5.549789     0.000000   137.372074  0 1 0 1 1 1
 As  core      1.387468     2.403111   140.314805  0 1 0 1 1 1
 As  core      5.549789     0.000000   140.314805  0 1 0 1 1 1
 
sw2
Ga As 4.6264 1.0 35.7999  0.0 3.8416
sw3
Ga As As 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830
As Ga Ga 30.0402  109.4712  2.5610 2.5610 4.8830 4.8830
""")

# Create PHtrans input
with open('ZZ.fdf', 'w') as f:
    f.write("""SystemLabel gaas

TBT.DOS.Gf T
TBT.Elecs.Coord.EPS 8e-3 Bohr
TBT.k [1 1 1]

ForceAuxCell .true.

TBT.HS DEVICE_gaas.nc

%block TBT.Contour.line
  part line
   from 0. eV to .33 eV
     points 500
      method mid-rule
%endblock TBT.Contour.line

%block TBT.Elec.Left
  HS ELEC_gaas.nc
  semi-inf-direction -a3
  electrode-position 49
%endblock
%block TBT.Elec.Right
  HS ELEC_gaas1.nc
  semi-inf-direction +a3
  electrode-position end -49
%endblock
%block TBT.Atoms.Buffer
atom [ 1 -- 48 ]
atom [ 145 -- 192 ]
%endblock

""")

##
#%block TBT.Atoms.Buffer
#atom [ 1 -- 12 ]
#atom [ 181 -- 192 ]
#%endblock TBT.Atoms.Buffer



os.system("~/epw/gulp-5.0/Src/gulp <gaas_s.gin>gaas_s.gout")
os.system("~/epw/gulp-5.0/Src/gulp <gaas_d.gin>gaas_d.gout")
os.system("~/epw/gulp-5.0/Src/gulp <gaas.gin>gaas.gout")


if not os.path.exists('gaas.gout'):
    raise ValueError("gaas.gin has not been runned by GULP")


print('Reading output')
gout = sisl.get_sile('gaas.gout')
gout1 = sisl.get_sile('gaas_s.gout')
gout2 = sisl.get_sile('gaas_d.gout')

# Correct what to read from the gulp output

#gout.set_supercell_key("Cartesian lattice vectors")
#gout1.set_supercell_key("Cartesian lattice vectors")
#gout2.set_supercell_key("Cartesian lattice vectors")

geo = gout.read_geometry()
print geo
geo1 = gout1.read_geometry()
print geo1
geo2 = gout2.read_geometry()
print geo2

dyn = gout.read_hessian()
dyn1 = gout1.read_hessian()
dyn2 = gout2.read_hessian()

# In GULP correcting for Newtons second law is already obeyed
# So this need not be used, however, the precision of output
# may require this anyway.
dyn.correct_Newton()
dyn1.correct_Newton()
dyn2.correct_Newton()


dev = dyn
#dev = dyn.cut(4, 2)
dev = dyn #.cut(2,2)
#dev1 = dev.cut(3,2,seg=1)
dev.write('DEVICE_gaas.nc')
tmp = sisl.get_sile('DEVICE_gaas.nc')
tmp1 = tmp.read_geometry()
print tmp1.xyz

#el = dyn1
#el = dev.cut(2, 2,seg=0) # second arg is the axis 0,1,2-->x,y,z
el = dyn1.cut(3,2,seg=1)
el.write('ELEC_gaas.nc')
tmp2 = sisl.get_sile('ELEC_gaas.nc')
tmp3 = tmp2.read_geometry()
print tmp3.xyz
#el2 = dev.cut(3,2,seg=1)
el2 = dyn2.cut(3,2,seg=1)
el2.write('ELEC_gaas1.nc')
tmp4 = sisl.get_sile('ELEC_gaas1.nc')
tmp5 = tmp4.read_geometry()
print tmp5.xyz
#el2 = dev.cut(3,2,seg=2)
#el2 = dyn2 #.cut(4,2)
#el2.write('dev.nc')
os.system("mpirun -np 4 ~/epw/siesta-4.1-new/bin/phtrans < ZZ.fdf > ZZ.out")

**Comment by zerothi** [comment]
@KitchenSong I allowed my-self to add ``` to your comment (this makes it look like code)

**Comment by zerothi** [comment]
It is a bit unclear what you expect and what you get, I can succesfully run the calculation, by adding this to the PHtrans input: `TBT.Elecs.Neglect.Principal true`

**Comment by zerothi** [comment]
You may, however, wish to limit the energy range investigated to say, `0.03 meV`

**Comment by KitchenSong** [comment]
It is a twin boundary so the two electrodes have to be specified separately. I do want to know why the k mesh cannot be larger than 1 1 1 in this calculation.

**Comment by zerothi** [comment]
In order to calculate dispersion along the transverse directions you need the dynamical matrix that connects super-cells. GULP does not save the supercell dynamical matrix. This is why one needs the `cut` method to cut the system while retaining the supercell dynamical matrix.

I.e. if you want to have periodicity along both transverse directions you need to extend your initial gulp calculations just as you did for the electrodes.

**Comment by KitchenSong** [comment]
I will have a try.

**Comment by zerothi** [comment]
@KitchenSong I will mark this question as resolved.

If you have other questions, please open a new issue! :+1:
