### ISSUE TITLE
sisl.nodes (intro documentation) has duplicate parameter argument

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#532]
**Describe the bug**
@pfebrer 

**Reproducable code**
```python
@Node.from_func
def alert_change(val: int, automatic_recalc=True):
    print(f"VALUE CHANGED, it now is {val}")

## error:
/opt/gnu/11.2.0/python/3.9.9/lib/python3.9/inspect.py in __init__(self, parameters, return_annotation, __validate_parameters__)
   2824                     if name in params:
   2825                         msg = 'duplicate parameter name: {!r}'.format(name)
-> 2826                         raise ValueError(msg)
   2827 
   2828                     params[name] = param

ValueError: duplicate parameter name: 'automatic_recalc'
```

I am not sure whether this is related to the 3.9 version, or why you don't see this? This also shows up in the documentation build.

**Comment by pfebrer** [comment]
I think I know what is going on, I'll fix it :) (I didn't recheck the notebook, which I should have done😅)

**Comment by pfebrer** [comment]
Is the `build_docs` script used to build the docs for github pages? I added an environment variable there, but it doesn't seem like it has been applied :sweat_smile:

**Comment by zerothi** [comment]
No, that is for local builds, it needs to be added to the work flow, as I recall.
