### ISSUE TITLE
PDOS calculation 

### ISSUE THREAD

**Issue by novidad21** [zerothi/sisl#536]
**Describe the issue**

I performed a SIESTA calculation without spin-orbit coupling and with netcdf support. I try to calculate the PDOS using the following code:
```

def gauss(x, sigma=1, x0=0.0):
    gauss = physics.distribution.gaussian(x, sigma=0.01, x0=0.0)
    return gauss

def func(sc, N, i,eltol):
    return [1/2-i/(N), eltol, 0]

ne = 1001
emin=-0.5
emax=0.5
nk = 900

E=linspace(emin,emax,ne)

eltol = linspace(-0.5,0.5,nk,endpoint=False)
eltol = eltol[5*int(nk/18):6*int(nk/18)]

dat = get_sile('path_to_fdf')
H=dat.read_hamiltonian()
pDOS = zeros([int(H.atoms.no),ne])
for el in eltol:
    bz = MonkhorstPack.parametrize(H, func, nk, eltol = el)
    pDOS += bz.apply.average.PDOS(E,distribution=gauss)
```
I get back the following error message:

Traceback (most recent call last):
  File "/mnt/st04pool/users/novidad21/home/Python/ABC-DOS/test/l_3_1b/parallel/dos_par.py", line 49, in <module>
    pDOS += bz.apply.average.PDOS(E,distribution=gauss)
  File "/users/novidad21/miniconda3/lib/python3.9/site-packages/sisl/physics/_brillouinzone_apply.py", line 110, in __getattr__
    method = getattr(self._obj.parent, key)
  File "/users/novidad21/miniconda3/lib/python3.9/site-packages/sisl/sparse_geometry.py", line 224, in __getattr__
    return getattr(self.geometry, attr)
AttributeError: 'Geometry' object has no attribute 'PDOS'

**Version details**
'0.0.0.dev+851d78c55d40d1f7aa1f5d8320aae1d3364064b8'
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) [GCC 11.3.0]

**Comment by novidad21** [comment]
It worked great, thank you. It took some time to me to wrap my head around it, but I think I get it.

**Comment by zerothi** [comment]
I presume you also got some significant speedup ;)

Well, in any case, I'll close this issue. Thanks for bringing this to our attention.

**Comment by novidad21** [comment]
Hard to tell, it was a completly new setup, but yes, it was faster :) Thank you for the assistance!
