### ISSUE TITLE
What should `Geometry.swapaxes` do if it includes `xyz` in `what`?

### ISSUE THREAD

**Issue by ahkole** [zerothi/sisl#539]
From the documentation I would expect that calling `Geometry.swapaxes` with `xyz` in the `what` argument would fully swap two Cartesian axes. So essentially you are not changing your geometry but just rotating it space by rotating the Cartesian axes. I.e. if you have a slab with vacuum in the z-direction you could transform it to a slab with vacuum in the x-direction by swapping the Cartesian axes. However, the way it is implemented right now the call only swaps the Cartesian components of the atom positions but leaves the Cartesian components of the cell vectors intact which completely changes your geometry. Is this the intended behaviour or is it a bug?

**Comment by zerothi** [comment]
I believe this is correct as per the documentation. The purpose is to swap the axes of the `what`, so if only `xyz` is in it, then the rest doesn't swap. If you want to swap both, then `cell+xyz` is required input. Consider cases where you are building geometries from sub blocks where the cell is used for some other purpose, or not used at all.  
I believe this is also what the documentation says, no?

**Comment by zerothi** [comment]
Ah, perhaps I misunderstood, you want it to swap `cell[:, (a, b)] `? This is a good point...

**Comment by zerothi** [comment]
I'll create a pr with this in mind, and I'll request your review, if you don't mind? :-)

**Comment by ahkole** [comment]
> Ah, perhaps I misunderstood, you want it to swap cell[:, (a, b)] ? This is a good point...

Yes, exactly. I also expect it to swap the cartesian components of the cell

> I'll create a pr with this in mind, and I'll request your review, if you don't mind? :-)

I would be happy to review :)
