### ISSUE TITLE
numpy.typing and sisl requirements

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#543]
According to [`requirements.txt`](https://github.com/zerothi/sisl/blob/main/requirements.txt), `sisl` needs `numpy>=1.13`. However, the development version now relies on `numpy.typing` that is [new](https://numpy.org/devdocs/reference/typing.html) in `numpy 1.20`. Update?

**Comment by zerothi** [comment]
You are absolutely correct, I'll have a look at it! Thanks for noticing!

**Comment by zerothi** [comment]
I believe this should be fixed in the latest commit.

Thanks for noticing, this is still all new to me, but should be valuable for the documentation etc.
