### ISSUE TITLE
Cut the supercell from GULP

### ISSUE THREAD

**Issue by KitchenSong** [zerothi/sisl#55]
Following the advice you provided in last issue, I tried to generate a supercell with x and y periodicity and then cut it twice by 
`el = el.cut(3,1,seg=1)
el = el.cut(3,0,seg=1) `
But I find that the positions out of this is totally messed up. How should one set the position of supercell initially to make the later cut work perfectly? Also, do we have to add optimization tag in GULP?
For the device region, should I also add x and y periodicity?

**Comment by zerothi** [comment]
When cutting you should do it in opposite order of the tiling, for instance.

**Comment by KitchenSong** [comment]
I wonder how to make tile work in this case. In current situation, I have not used tile at all. Maybe I am wrong...

**Comment by KitchenSong** [comment]
I am following your suggestions: using tile first. But when doing those tiling operation, how to keep track of the atom species information?

**Comment by zerothi** [comment]
What do you mean? The sisl geometry keeps track of everything for you?

**Comment by KitchenSong** [comment]
Here is how I try to do it:

I first run a GULP calculation for a small cell.

Then I read the geometry and generate the supercell using
`gxyz = geo1.tile(3, 0).tile(3, 1).tile(3, 2)
leftpos =  gxyz.xyz`

What you suggests is that in the variable leftpos, there is no longer more atom species information?

**Comment by zerothi** [comment]
I don't get what you mean? `gxyz` contains all species informations.
How would you want the species?
```
gxyz = geo1.tile(3, 0).tile(3, 1).tile(3, 2)
leftpos = gxyz.xyz
species = [atom.symbol for atom in gxyz.atom]
```
For further details look for the `Atoms` and `Atom` class in the sisl documentation.

**Comment by KitchenSong** [comment]
Well, I think you just answered my question. Sorry for the confusion.

**Comment by zerothi** [comment]
Great!
