### ISSUE TITLE
Should we change to `furo` theme?

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#565]
**Describe the feature**

Should we change the documentation theme from rtd, to furo?

See the difference here:
- [furo](https://www.student.dtu.dk/~nicpa/sisl/html/furo/index.html)
- [rtd](https://www.student.dtu.dk/~nicpa/sisl/html/rtd/index.html)

What do you say?

@tfrederiksen @sofiasanz @pfebrer comments? Please note the installation tab which has some "tabs" that I think could be useful for doing various things.

**Comment by zerothi** [comment]
Remarkably the search function works in furo... Hmmm
.

**Comment by pfebrer** [comment]
I like the RTD theme better, I don't know why some packages are moving to other themes for documentation :sweat_smile: 

Of course if the search bar doesn't work that's something to consider... hahah

Is it only me or the furo theme gives a very large margin on the left?:

![Screenshot from 2023-04-18 21-57-25](https://user-images.githubusercontent.com/42074085/232891840-87a26b04-857e-40ad-b3c1-397697708a2a.png)

**Comment by zerothi** [comment]
Yeah, I had the same issue, but actually if you look at the two in neighbouring windows you'll see that RTD has the same margin, just left-aligned.

@pfebrer did you try the dark theme? I kind of like that one...

I think *many* have moved to furo since it is used by `pip` and some of its associated packages. So it is endorsed by the built-devs which always takes many followers :)  
I just found this: https://github.com/readthedocs/sphinx_rtd_theme/issues/1452

This seems to solve the issue, now searching should be back! :)

**Comment by zerothi** [comment]
Ok, we'll not change to furo. :)

**Comment by tfrederiksen** [comment]
I also tend to prefer RTD, mostly because this is what I'm used to. Great you found a fix for the search function!
