### ISSUE TITLE
Interfaces for multiple returns

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#577]
**Describe the bug**
All `read_` routines which may return multiple entries, such as MD, or SCF data should utilize `sile_read_multiple` as a decorator.

However, there are quite a bit of files that implement the wrong interfaces:
```shell
~/codes/sisl/src/sisl/io % grep "all=" **/*.py | grep def                                                                                                                                
openmx/md.py:    def read_geometry(self, *args, all=True, **kwargs):
orca/out.py:    def read_electrons(self, all=False):
orca/out.py:    def read_energy(self, all=False):
orca/out.py:    def read_orbital_energies(self, all=False):
orca/txt.py:    def read_electrons(self, all=False):
orca/txt.py:    def read_energy(self, all=False):
orca/txt.py:    def read_geometry(self, all=False):
siesta/out.py:    def read_geometry(self, last=True, all=False):
siesta/out.py:    def read_force(self, last=True, all=False, total=False, max=False, key="siesta"):
siesta/out.py:    def read_stress(self, key="static", last=True, all=False):
siesta/out.py:    def read_moment(self, orbitals=False, quantity='S', last=True, all=False):
vasp/out.py:    def read_energy(self, all=False):
```
these should all be changed to utilise the decorator.

**Comment by tfrederiksen** [comment]
This would be nice, but how do we get the `sile_read_multiple` to return optionally only the *last* entry?

**Comment by zerothi** [comment]
> This would be nice, but how do we get the `sile_read_multiple` to return optionally only the _last_ entry?

we should probably extend that decorator to return a single element. For instance that can be done via the `postprocess` argument, checking for the size or such. Or simply by checking arguments internally.
The main problems is that:
1. Users may programmatically do something that coincides with a trajectory of size 1, in which case it shouldn't return a single element.
2. I am not sure if we need to add yet another flag to allow this. The thing is that probably the decorator could fix this...

**Comment by zerothi** [comment]
It might also be a `single` flag or `indices=[...]|-1` where if `indices` is not a list, it unwraps the returned argument.

**Comment by tfrederiksen** [comment]
Maybe we should just fix things such that negative values are not simply passed to `range(start, stop, step)`, but instead understood as first reading all entries to build the complete list, and *then* making a selection with counts from the end?

**Comment by zerothi** [comment]
Yeah, probably the simplest, another (simpler) method would be to use the `deque` container to automatically keep the required entries. It should be simple enough to calculate the size if both are negative, and if neither are, then it is a different matter.

**Comment by zerothi** [comment]
Super seeded by #584
