### ISSUE TITLE
`translate2uc` for sparse orbital matrices

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#583]
Just as there is the `translate2uc` method for geometries, it could be nice to have it for sparse orbital matrices.

It would for example facilitate a lot the computation of real space density from the density matrix.

**Comment by zerothi** [comment]
What should `translate2uc` for sparse matrices do?
If you want to translate orbitals I think you should use `self.geometry.translate2uc` instead. I think we shouldn't clutter the sparse matrices with geometry functionality.

**Comment by pfebrer** [comment]
Let's say you have an atom `i` whose "unit cell coordinates" are inside the `[0,0,3]` supercell. This atom connects to some other atom `j` that is in the unit cell because they are 1.5 Ang away from each other. But due to the atom `i` coordinates being outside the unit cell, its their periodic images that interact. In the DM this will result in a matrix element at `[i, j + (0, 0, -3)]`, no?

If you translate atom `i` to the unit cell this connection should then move to `[i, j]`, right?

**Comment by zerothi** [comment]
Hmm, but `geometry.translate2uc` returns a geometry, it would be counter-intuitive to have the sparse matrix overwrite the residing geometry?

Couldn't you do a `geometry = self.geometry.translate2uc()` and work with that internally?

**Comment by pfebrer** [comment]
`dm.translate2uc()` should return a new dm, right? (instead of modifying in place) Perhaps it makes sense that this new dm has also a new geometry.

You could work out the indices in whatever algorithm that you are implementing, but it probably makes the algorithm much more complex to understand/modify/maintain, no? Also I think it's a good idea that this conversion of the indices is centralized, because if there is a bug or something you know that you have to change the code only in one place.

I mean any algorithm that uses the DM could do:

```
dm = dm.translate2uc()

# And from here on assume that the coordinates of the primary atoms are in the unit cell,
# which makes life much easier.
```

**Comment by zerothi** [comment]
Could we instead enable the `Sparse*.copy` function to accept a geometry object, and then users would do this:
```python
dm = dm.copy(geometry=dm.geometry.translate2uc())
```
?
I am a bit hesitant since the `translate2uc` does not do anything for the sparse elements.
Or do you suggest the orbital couplings are also translated? If that's the case, then yes, we could add it. :)

**Comment by pfebrer** [comment]
Indeed, the whole point would be to translate the couplings. Otherwise if you translate only the geometry, the matrix would be just wrong 😅

**Comment by zerothi** [comment]
Ok, this would be great, you should be able to use `translate_columns`, hints in `_translate_cells`. Hope this can guide you! :)

**Comment by zerothi** [comment]
Note that this might be a bit problematic for slab calculations where users put their plane at origo, i.e. 0,0,0. In that case some atoms will be in the neighbouring cell, while others will be in the unit-cell. Even though there is no periodicity along the normal vector.

**Comment by pfebrer** [comment]
> Note that this might be a bit problematic for slab calculations where users put their plane at origo, i.e. 0,0,0. In that case some atoms will be in the neighbouring cell, while others will be in the unit-cell. Even though there is no periodicity along the normal vector.

Ok, so perhaps in general atoms should not be translated in directions where `pbc=False`?

**Comment by zerothi** [comment]
I think so. Actually this should be changed in the `Geometry` class! ;-D

**Comment by zerothi** [comment]
I will fix the geometry class. :)
