### ISSUE TITLE
Remove required dependency of netCDF4

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#595]
**Describe the issue**
Should we remove required dependency of netCDF4?

Currently, it isn't forced in the code, so it *could* be disabled.

The latest commit has added it to all optional dependency additions.

Would there be any objections to this?
The thing is that sisl without io usage does not require netCDF, so it would still be useful for users to test things with sisl like this.

**Comment by tfrederiksen** [comment]
Sounds like a good idea!

**Comment by zerothi** [comment]
Question is if would be annoying for some users? Lots of people (siesta users) will use this by default...

**Comment by tfrederiksen** [comment]
Wouldn't the siesta use cases easily be handled by installs like?
```
python3 -m pip install sisl[analysis]
```

**Comment by zerothi** [comment]
Yes, it's more communicating this to users, but I think it should be done at instantiation of the `SileCdf` class, so should be doable. OK let's do this.
