### ISSUE TITLE
Is there  a memory limit when using sisl.Hamiltonian.read

### ISSUE THREAD

**Issue by AsymmetryChou** [zerothi/sisl#609]
**Describe the issue**

When I use sisl.Hamiltonian.read() to get a Hamiltonian for a usual molecular system( its hamiltonian matrix's size is approximately 500*500)  with code as :
```python
Hmol= sisl.Hamiltonian.read('0/mol.HSX')
# mol.HSX calculated from siesta
```

 sisl got an error as "**STOP Error in reading data, not allocated, Gamma**" . 

It took me  for a long  time to fix it but failed, I guess the input matrix might be a little larger than some memory limit.  I hope you can give me some advice (personally I think the error is due to my naive sisl operation ).Thanks!
 
**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
3.9.17 (main, Jul  5 2023, 20:41:20)
[GCC 11.2.0]
0.0.0.dev+851d78c55d40d1f7aa1f5d8320aae1d3364064b8
```

**Comment by zerothi** [comment]
No, 500x500 should not pose a problem, are you using the latest sisl development commit?

I just submitted a small patch, could you try and install the latest sisl development commit, see [here](https://zerothi.github.io/sisl/installation.html#required-dependencies) and use `dev|pip` tab

**Comment by AsymmetryChou** [comment]
OK! I will try the latest one.

**Comment by AsymmetryChou** [comment]
With the latest version, it runs successfully! Thanks!

**Comment by zerothi** [comment]
Great, I'll close!
