### ISSUE TITLE
`Lattice.boundary_cond` boundary conditions for the lattice

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#626]
**Describe the feature**

this follows the discussion of #553 #625  which discusses the move of `nsc` to another object.

Lets here focus on a more simple thing. Namely how to handle boundary conditions.

It seems to me that the boundary conditions are a more fundamental property of the lattice, and as such belongs in that object.

- currently the boundary conditions are only located in the `Grid` class, but I think we can argue that the `Lattice` is the more natural
  place. Whether or not a grid is used, one can still associate a boundary condition with the `Lattice`
- according to the above I think we have agreed that `nsc` should not be used to predict `bc`. In fact, one might argue that non-periodic boundary conditions when `nsc[axis]>1` is wrong. And this is something that could be checked otherwise.

My proposal:
- move the `bc` arguments of `Grid` into `Lattice` so that the lattice is responsible for the boundary conditions.
- instead of only having `pbc`, we should be more generic, and name it `boundary_cond`/`boundary_condition`. This is very easy to read and shouldn't pose big problems. The current allowed `PERIODIC`, `NEUMANN`, `DIRICHLET`, `OPEN` which should be re-used here as well.
- `pbc` can be a shorthand for checking `boundary_cond == PERIODIC` at its simplest

I think this goes nicely in line with the above points, any comments? @tfrederiksen @pfebrer

**Comment by pfebrer** [comment]
I agree with all the points!

**Comment by tfrederiksen** [comment]
I also agree with this. As for the permitted values of `boundary_condition` (my preference for the naming) could one also include `None/False` (for a nonperiodic direction) and `True`? What would be the meaning of `DIRICHLET/NEUMANN/OPEN` for an atomic lattice?

**Comment by zerothi** [comment]
I'll see if the bool can be incorporated in an enum.

What do  you mean about the dirichlet et al? They have the meaning of how the boundaries are handled. Open is a placeholder for a semi infinite boundary. I don't know if we should name it like that, but in reality it could match any kind of user defined boundary condition. I'll make a pr and ask for review!
Thanks!
