### ISSUE TITLE
sisl.physics.hamiltonian support slice operation in both index or not? 

### ISSUE THREAD

**Issue by AsymmetryChou** [zerothi/sisl#653]
**Describe the issue**

Hi Nick !

Thanks for your help in #650.
Follow your advice, here I test the latest version sisl in graphene:
```python
graphene = sisl.geom.graphene(orthogonal=True)
H = sisl.Hamiltonian(graphene)
H[0,:]=np.ones([4])
print(H[0,:])

## >>>output>>>
[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
## <<<output<<<

print(H[:,:])
## >>>error>>>
  File "xxxx/test_graphene.py", line 12, in <module>
    print(H[:,:])
  File "xxxx/python3.9/site-packages/sisl/sparse_geometry.py", line 1645, in __getitem__
    d = self._csr[key]
  File "xxxx/python3.9/site-packages/sisl/sparse.py", line 1186, in __getitem__
    get_idx = self._get(key[0], key[1])
  File "xxxx/python3.9/site-packages/sisl/sparse.py", line 1109, in _get
    return indices(self.col[ptr : ptr + self.ncol[i]], j, ptr)
ValueError: operands could not be broadcast together with shapes (5,) (4,) 
## <<<error<<<
``` 
The code runs successfully, however I guess the correct output for `H[0,:]` might be `[1,1,1,1]` ? And when I print out `H[:,:]`，something wrong happens.

Furthermore, I test the code:
```python
graphene = sisl.geom.graphene(orthogonal=True)
H = sisl.Hamiltonian(graphene)
H[:,:]=np.ones([4,4])

##error:
  File "xxxx/test_graphene.py", line 5, in <module>
    H[:,:]=np.ones([4,4])
  File "xxxx/python3.9/site-packages/sisl/sparse_geometry.py", line 1668, in __setitem__
    self._csr[key] = val
  File "xxxx/python3.9/site-packages/sisl/sparse.py", line 1316, in __setitem__
    self.__setitem__((i, j), d)
  File "xxxx/python3.9/site-packages/sisl/sparse.py", line 1344, in __setitem__
    self._D[index, :] = data[:, :]
ValueError: shape mismatch: value array of shape (4,1) could not be broadcast to indexing result of shape (1,1)
```

It seems that the latest version sisl don't support slice operation in both index, like `H[:,:]`. I don't know it's a bug or designed feature.

Thanks!

**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
import sys
print(sys.version)
import sisl
print(sisl.__version__)

3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
0.14.4.dev11+g82c1e437a
```

**Comment by zerothi** [comment]
Yeah, don't do double slices like that, if you want to assign everything, then go through the `fromsp` it is *much* faster! So preferred anyways. :)

It all depends on what you want, but generally you should use *simple* ways to construct the Hamiltonian, then afterwards, using `H.Hk()` to access the folded *with phases* Hamiltonian.

**Comment by AsymmetryChou** [comment]
OK, I see! Thank you very much ~

**Comment by zerothi** [comment]
I will close this as **wont-fix**, At least this is far off the priority list as there are better ways to do this :)

Thanks!
