### ISSUE TITLE
TBtrans support non-zero bias TB-NEGF self-consistently ?

### ISSUE THREAD

**Issue by AsymmetryChou** [zerothi/sisl#656]
**Describe the issue**

Hello, Nick!

Recently I want to use TBtrans for TB-NEGF calculation in non-zero bias condition. However I search for the detailed operation in https://github.com/zerothi/ts-tbt-sisl-tutorial/blob/main/tutorial.ipynb but only find that in DFT-NEGF in TranSiesta.

Although I have seen some fdf.options in TBtrans Manual, I'm not sure whether TBtrans could do non-zero bias TB-NEGF. If TBtrans could, can it determine the electrostatic distribution self-consistently or use some empirical method?

This problem comes from that I didn't find some options in TBtrans like TS.Contours in TranSiesta to do calculation self-consistently in complex plane.

Thank you very much!

**Comment by zerothi** [comment]
Please, next time a question is only about TBtrans, please ask this at the gitlab site! https://gitlab.com/siesta-project/siesta

No, TBtrans is not self-consistent, it does one shot calculations, however, if the Hamiltonian is calculated from a self-consistent method at any bias, then TBtrans will solve the biased problem.
