### ISSUE TITLE
Return of missing diagonal elements error

### ISSUE THREAD

**Issue by AleksBL** [zerothi/sisl#661]
**Code to reproduce problem**
```python
print(Hd.nsc)
Hd.write('out.TSHS')
```
Gives
[1 1 1]
SislError: The diagonal elements of your orthogonal Hamiltonian have not been defined, this is a requirement.

Redefining by
```python
Hd2 = sisl.Hamiltonian(sisl.Geometry(Hd.xyz, atoms=Hd.atoms))
import scipy.sparse as sp
Hd2 = Hd2.fromsp(sisl.Geometry(Hd.xyz, atoms=Hd.atoms), Hd.Hk(), S = sp.eye(Hd.na))
Hd2.write('out.TSHS')
```
makes it write without error.

This bug has appeared at several updates it seems, or it might be some strange stuff going on in the dependencies. I dont know, but i think it was fixed in a 0.13 version.

I didnt understand the origin of it when it was fixed previously, so I wondered if you know where this error comes from?

Best,
Aleksander

**Version details**
Run the below code and add to bug-report:

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
0.14.2

**Comment by zerothi** [comment]
Yes, the matrices that are to be written for TBTrans inputs is that it requires the diagonal elements to be defined. So I think the error makes sense? What did you expect?

**Comment by AleksBL** [comment]
How to define them without requiring to make a new Hamiltonian with the fromsp method?
even if i do
```python
for i in range(Hd.no):
    Hd[i,i] = 0.5
```
it still wont write

**Comment by zerothi** [comment]
@AleksBL it is fixed in the latest commit, some things have changed a bit.
