### ISSUE TITLE
xyz coordinates for entire grid

### ISSUE THREAD

**Issue by JoshRackers** [zerothi/sisl#677]
The function `index2xyz` for a grid is very helpful. It might be nice to quickly get the xyz coordinates for an entire grid that has been read in. Is there a nice way to do this quickly without iterating through every index with `index2xyz`?

**Comment by pfebrer** [comment]
It is not necessary to iterate, you can pass an array of indices to `index2xyz`:

```python
import sisl
import sisl.viz

import numpy as np

# Create a geometry
geom = sisl.geom.graphene()
# And a 4x4x4 grid.
grid = sisl.Grid((4, 4, 4), geometry=geom)

# Get the indices for all the grid points
indices = np.mgrid[0:grid.shape[0], 0:grid.shape[1], 0:grid.shape[2]]
indices = np.transpose(indices, (1,2,3,0))

# Convert them to XYZ
xyz = grid.index2xyz(indices)

# Plot the xyz points along with the geometry to check that everything
# went fine
sisl.viz.merge_plots(
    geom.plot(), 
    sisl.Geometry(xyz.reshape(-1, 3)).plot(atoms_style={"size": 0.2, "color": "green"}, show_bonds=False)
)
```

![newplot (35)](https://github.com/zerothi/sisl/assets/42074085/9cf3179a-48d8-4194-9bcf-651fb9fd9d54)

**Comment by JoshRackers** [comment]
Aha! I did not realize you can pass an array of indices. That solves it- thanks.
