### ISSUE TITLE
Classification of atoms using categories

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#689]
Following discussion in #688

I think it would be nice that categories facilitated classification. Imagine you have three categories `cat1`, `cat2` and `cat3`. There could be a nice way of grouping atoms based on whether they belong to those categories or not.  I.e. if I have a geometry, I could do something like:

```python
geometry.classify((cat1, cat2, cat3))
```

And I would get an array saying to which group each atom belongs:

```
[0, 0, 0, 2, 1, 2, ..., -1, 0]
```

This I think is basically what the "Or" category does, but returning indices instead of the categories themselves.

Another thing that would be useful for classification is to provide some property and ask for the creation of groups based on that property:

```python
geometry.classify(AtomNneighbors)
```
and you get maybe a tuple with the group indices and the meaning of each group:
```python
[0, 0, 0, 1, 0, 2, 0, 1, 2], (AtomNneighbors(0), AtomNneighbors(1), AtomNneighbors(2) )
```

**Comment by zerothi** [comment]
Or perhaps `catA.indices(result)` would give back the indices that are the same?

**Comment by ialcon** [comment]
From what I see in the example by Pol, I understand that the implementation you are thinking about would require each atom to be uniquely associated to one category, right?

**Comment by zerothi** [comment]
> From what I see in the example by Pol, I understand that the implementation you are thinking about would require each atom to be uniquely associated to one category, right?

Yes, and I think that can be surprising to end users when that isn't the case. Then I guess it would be better to return the category that matches *any* of them.

**Comment by pfebrer** [comment]
If the goal is to classify, yes :) 

Maybe it would be best to have a separate thing for classifying. So `Classifier` would be separate from `Category`. I just saw some sinergies between the two things. But I guess what both things share is to compute some atom-wise property, and then they perform different operations with it.

So perhaps it could be worth it to implement `AtomProperty` and then make categories and classifiers potentially use them.

**Comment by zerothi** [comment]
This I would argue aims at us changing what the categories _can_ do. Meaning, that possibly a category should be able to contain more content, and not just index like.

I am primarily worried about the implications on documenting `Category` vs `Classifier` for end-users. From a first glance they look very similar, and I bet `Category` would just be a subset of `Classifier`, so hence we might as well change everything to do what you want the `Classifier` to do, no?

**Comment by ialcon** [comment]
Just one question for me to follow... What is the difference between classifier and categorize?

**Comment by zerothi** [comment]
> Just one question for me to follow... What is the difference between classifier and categorize?

currently we don't have a `Classifier` @pfebrer is advocating on adding this. I am trying to figure out if we can have a single way to do both (i.e. only have a `Category`, or name it `Classifier`).  
So an open discussion on that for now. :)

**Comment by ialcon** [comment]
Ok, thanks Nick. I will try to read your various issues commenting on this topic early next week - so that I have a better overall picture. For me it is hard to see how classifier/category could be used to classify atoms in *different* hexagons within, say, a GNR - specially because such hexagons would have common (sharing) atoms.. But there might be the way to do this.

**Comment by zerothi** [comment]
> Ok, thanks Nick. I will try to read your various issues commenting on this topic early next week - so that I have a better overall picture. For me it is hard to see how classifier/category could be used to classify atoms in _different_ hexagons within, say, a GNR - specially because such hexagons would have common (sharing) atoms.. But there might be the way to do this.

The idea here, would be to fundamentally restructure the `Category` class. So that it can re-act to the surroundings (other atoms than it-self).
