### ISSUE TITLE
Grid.isosurface for complex values?

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#709]
**Describe the bug**

Currently when doing `Grid.isosurface` it truncates the complex part. So it might be rather difficult for end users to see this.

`scikit-image` is (I think) keeping the floats, and it might be a long time to allow complex values https://github.com/scikit-image/scikit-image/issues/4308

**Comment by zerothi** [comment]
@pfebrer should we warn about complex data-type, and then only pass the float, or simply accept the warning that arises?

**Comment by pfebrer** [comment]
Hmm interesting, do complex value iso surfaces even make sense? Can you say that some complex value is larger/smaller than another? You would have to compute some real number out of them (e.g. the modulus) and then compute an isosurface for that, right?

I think a warning from our side wouldn't solve much. We could either keep the scikit-image warning or raise an error (which maybe is the best option).

**Comment by zerothi** [comment]
Yeah, probably the modulus would be the best thing, shouldn't we then silently do that for a complex grid?
In that case I would do something like this:

1. convert the grid to the modulus
2. define a projection angle (lets default to 0, real axis choice), then choose the sign of the modulus depending on the projection?

Or would you do something else?

**Comment by pfebrer** [comment]
I'm not sure if we should do anything silently 😅 In any case, I would do it only if the isosurface level requested by the user is also a complex value, so that we are more certain that this is what the user wants to do.

Otherwise I would raise an error.

**Comment by zerothi** [comment]
> I'm not sure if we should do anything silently 😅 In any case, I would do it only if the isosurface level requested by the user is also a complex value, so that we are more certain that this is what the user wants to do.
> 
> Otherwise I would raise an error.

Asking for a complex isosurface would be horrendous :)
It will be individual points, I think perhaps the modulus would be the most appropriate.
