### ISSUE TITLE
Rename `stdoutSileVASP` to `outcarSileVASP`

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#719]
Currently OUTCAR files are read with `stdoutSileVASP`. However I find this naming unfortunate as the OUTCAR is **not** stdout.

I've uploaded some examples here: https://github.com/zerothi/sisl-files/pull/10

My suggestion is to change the name for OUTCAR to `outcarSileVASP`. (And maybe we could later develop another interface for stdout.)

**Comment by zerothi** [comment]
Sounds like a good idea! :)

**Comment by tfrederiksen** [comment]
Closed with https://github.com/zerothi/sisl/commit/f6195feece59588a50bc86dffba9b4faaed4636f

**Comment by zerothi** [comment]
sorry, forgot to add that here! yes!

**Comment by tfrederiksen** [comment]
> sorry, forgot to add that here! yes!

No problem!
