### ISSUE TITLE
Documentation of SileBinder methods

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#728]
The documentation is not very informative for the `SileBinder` methods, e.g., in `txtSileORCA`:
https://zerothi.github.io/sisl/api/io/generated/sisl.io.orca.txtSileORCA.html#sisl.io.orca.txtSileORCA.read_energy just shows:
```
read_energy = <sisl.io._multiple.SileBound object> [source]
```
Here, for instance, the optional `units` argument is not shown.

Can this be improved?

**Comment by zerothi** [comment]
It is a known issue, see #632. I have yet to figure out why it exactly happens...
I'll close this as it is a duplicate of #632

**Comment by tfrederiksen** [comment]
Indeed 😅
