### ISSUE TITLE
Math in sisl documentation

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#731]
**Describe the issue**

I would like to open up the discussion on how we should format math/equations in the documentation.

There are a few details that requires explicitness (IMHO).

- which values should we use for atomic indices, and for looping
  
  Suggestion: $i\in I$, where $i$ is an atomic index, and $I$ is an atomic index range
- which values should we use for orbital indices

  Suggestion: $\nu\in\alpha$ where $\alpha$ is an orbital range (e.g. $\alpha_i$ orbitals on atom $i$), and $\nu$ is a single index

- how should index ranges be written?

  Suggestion: above we just did $I$, but should it be $`\{I\}`$ or?
- how should matrices be written?

  Suggestion: $\mathbf A$ (capital bold-faced letters)
- how should vectors be written?

  Suggestion: $\vec a$
- how should scalares be written?

  Suggestion: $a$

With a convention, we can also formalize how math should be understood:

- $\vec a \cdot \vec b$ is dot-product
- $\vec a \mathbf A$ (no need for $\cdot$)
- $\mathbf A \mathbf B$, or $\mathbf A \times \mathbf B$, where I would argue $\times$ can be optional

Are there things forgotten?

this came about due to #722 where (I plead guilty) the math got changed after merge.

The floor is open to suggestions!

**Comment by tfrederiksen** [comment]
What about sticking with the Latin alphabet for orbitals and atoms, i.e.,
 - lowercase for **orbital indices** (e.g. $i, j, \ldots$) and uppercase for **atom indices** $I, J, \ldots$? The understanding would be that $i\in I$ etc.
 - Ranges could then be indicated by curly brackets "{ }" as you suggest.
 
Maybe the Greek alphabet could then be reserved for any other labels **not** representing orbital or atom indices? E.g., spin components ($\alpha,\beta$) or Cartesian directions as in https://zerothi.github.io/sisl/api/generated/sisl.physics.electron.berry_curvature.html#sisl.physics.electron.berry_curvature

**Comment by nils-wittemeier** [comment]
I like the suggestion of lowercase for orbital indices and uppercase for atomic indices!

For scalars, I would consider using lower italics (similar to typical latex). That would also make the arrows for vectors unnecessary because lowercase bold letters could represent vectors.

**Comment by zerothi** [comment]
thanks for your inputs! I will create some templates surrounding your suggestions! Thanks for entering the discussion!

**Comment by zerothi** [comment]
> What about sticking with the Latin alphabet for orbitals and atoms, i.e.,
> 
>     * lowercase for **orbital indices** (e.g. i,j,…) and uppercase for **atom indices** I,J,…? The understanding would be that i∈I etc.
> 
>     * Ranges could then be indicated by curly brackets "{ }" as you suggest.
> 
> 
> Maybe the Greek alphabet could then be reserved for any other labels **not** representing orbital or atom indices? E.g., spin components (α,β) or Cartesian directions as in https://zerothi.github.io/sisl/api/generated/sisl.physics.electron.berry_curvature.html#sisl.physics.electron.berry_curvature

One thing here, typically one uses `i` as a sum index. Perhaps we could suggest $a$, $A$ as orbital/atom indices? But...
I think $i$ and $j$ can be reserved for summations. Say state indices. Suggestions?

**Comment by tfrederiksen** [comment]
> One thing here, typically one uses `i` as a sum index. Perhaps we could suggest a, A as orbital/atom indices? But... I think i and j can be reserved for summations. Say state indices. Suggestions?

Why not use Greek letters in these other cases? Say sum over state coefficients $\sum_\alpha c_{i\alpha}$ for orbital $i$? Here I think $\sum_i c_{ai}$ would be a little less clear.
