### ISSUE TITLE
how can i use param_circle for graphene

### ISSUE THREAD

**Issue by masume70** [zerothi/sisl#740]
Hi, I want to know how can I use param_circle for graphene?
Thank you

**Comment by zerothi** [comment]
Could you be a bit more specific? Param circle creates a circular path around a given k-point.
What have you tried, what did you expect and get?

**Comment by masume70** [comment]
I mean that I want to use param_circle for the graphene lattice because to the best of my knowledge param_circle is used with lattice

**Comment by zerothi** [comment]
I don't understand ;)

What have you tried, and what is your code?

**Comment by zerothi** [comment]
I think #741 is a duplicate on this? I'll close, otherwise re-open.
