### ISSUE TITLE
use tocartesian

### ISSUE THREAD

**Issue by masume70** [zerothi/sisl#741]
Hi all,
I want to choose a list for k points and convert them with tocartesian but I don't know how. Could anyone please help me?

**Comment by masume70** [comment]
I'm attempting to obtain a 2D band structure and its contour plot. Below is my code:

kx= np.linspace(-1,1,40)
ky= np.linspace(-1,1,40)
mat=[]
for x in kx:
    for y in ky:
        ei = H.eigh(k=(x, y, 0))  # Assuming this retrieves the eigenvalues
        mat.append([x,y] + ei.tolist())  # Append kx, ky, and eigenvalues as a single list
print(mat)
# Convert mat to a NumPy array
mat_array = np.array(mat)
print(mat_array)
# Save the array to a CSV file
np.savetxt('graphene.csv', mat_array, delimiter=',')
x = mat_array[:, 0]
y = mat_array[:, 1]
energies1 = mat_array[:, 2]  # You can also use the fourth column if it represents energies
energies2 = mat_array[:, 3]  # Fourth column
# Create a 3D scatter plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
for i in range(2,4):
    energies = mat_array[:, i]
    ax.scatter(x, y, energies, c=energies, cmap='viridis')
# Set labels and title
ax.set_xlabel('kx')
ax.set_ylabel('ky')
ax.set_zlabel('Energy')
plt.title('3D Plot of Energy vs kx and ky')
plt.show()


![2d](https://github.com/zerothi/sisl/assets/52975502/18ff1c1e-1a74-4625-947b-e5947caa56aa)
![contour](https://github.com/zerothi/sisl/assets/52975502/3f8656a6-6377-406d-b3ca-ba5649571f7c)

As can be seen, it exhibits rotation. I have already encountered a similar question on this link: https://github.com/zerothi/sisl/issues/438, but I couldn't solve the problem.

As I found out, the eigenvalues should be obtained with the Cartesian k-point grid. Now, I want to know how I can achieve this. I searched the manual and found that "tocartesian" can accomplish this, but I'm unsure of the exact procedure.

**Comment by zerothi** [comment]
have you read the documentation for the `tocartesian` method? it just accepts some k-points, and converts them to cartesian points.

Instead of doing `kx` and `ky` do:
```python
mp = sisl.MonkhorstPack(H, [40, 40, 1], trs=False)
eigs = mp.apply.array.eigh()
```
now `eigs` contains all eigenvalues for all k-points

To convert the k-points into cartesian, do:
```python
kcart = mp.tocartesian(mp.k)
```
done

**Comment by masume70** [comment]
Thank you for your response. I tried it and the following plot was obtained:
![Untitled](https://github.com/zerothi/sisl/assets/52975502/0edc0208-cfa9-4748-913c-40ab3c371b8d)

What I want to plot is for a range of kx and ky. For instance, from -1 to 1. Is that possible?

**Comment by masume70** [comment]
like this:
![1](https://github.com/zerothi/sisl/assets/52975502/7079e980-f191-4e2a-b779-28e588af2f00)

**Comment by zerothi** [comment]
your left plot is a bandstructure, so you should use the `BandStructure` thing.
As for the right plot, just change the axis, use `kx=mp.tocartesian(mp.k)[:, 0]`.

**Comment by masume70** [comment]
Yes, thank you. I meant the right plot. How about when I want arbitrary ranges for k points, not what is produced by MonkhorstPack? Is that possible?

**Comment by zerothi** [comment]
Your plot is from -1 to 1? If you want a band-structure plot, then use `BandStructure`?

**Comment by masume70** [comment]
I really appreciate your answers. I have one more question; Is it possible to make a range for kx and ky like kx= np.linspace(-1,1,120) and ky= np.linspace(-1,1,120) then change them to reduced coordination (as I studied the manual, there is a function called "toreduced" but I couldn't use it) for obtaining the eigenvalues instead of using MonkhorstPack?

**Comment by zerothi** [comment]
I expect this to have been resolved, if not, please continue the discussion here, and we will re-open.
