### ISSUE TITLE
Remove function in SparseOrbital class

### ISSUE THREAD

**Issue by tanocalogero** [zerothi/sisl#76]
**Describe the bug**
"remove" function in "SparseOrbital" class fails if atom is an array and not an Atom object.
Instead "sub" works.
So I guess the problem is that the function "_remove_atoms" should include the option for using atomic indices as "atom" argument.

**Comment by zerothi** [comment]
Fixed, thanks for the bug-report! ;)

**Comment by tanocalogero** [comment]
You’re welcome ;)
