### ISSUE TITLE
Writing Hamiltonian with sisl from Wannier

### ISSUE THREAD

**Issue by monx-ne** [zerothi/sisl#760]
We are trying to write a .nc file for a tbtrans simulation using a Hamiltonian read with sisl (0.14.3) from a Wannier90 run. Since the Wannier90 Hamiltonian has complex terms, we run into the following message:

NotImplementedError: Currently we only allow writing a floating point Hamiltonian to the Siesta format

Is there a fundamental reason why it can not be complex? Is this issue related to siesta, sisl or tbtrans?

Also @nils-wittemeier might know/be interested in this issue. This might be relevant for studying other Hamiltonians that have complex terms, for instance topological insulators.

**Comment by zerothi** [comment]
There are two issues:

1) if your Wannier Hamiltonian is complex, likely the minimization process is not complete, at least that doesn't sound good!
2) Siesta and TBtrans does *not* allow one to do complex hamiltonians, only real-spin dependent components. If you want to use a complex Hamiltonian, you have to use the `dH` approach. There you can basically do whatever you *want*. ;)

**Comment by zerothi** [comment]
And since tbtrans isn't fully SO (then you'll have to play with Nils's branch, then you can't do a SO Hamiltonian with 8 components. So you basically have to emulate the 2 spin-components as individual orbitals.

**Comment by zerothi** [comment]
If there are no more information or feedback here, I'll close this soonish :)
Thanks!
