### ISSUE TITLE
Custom colormaps for 3D plots

### ISSUE THREAD

**Issue by saru1799** [zerothi/sisl#785]
**Describe the feature**
Hi, I am making plots with the geometry plot visualization, where I aim to do a 3D plot with a colormap that depends on the charge of each of the atoms. However, when I wanted to use the "balance" colormap, and it did not work. Therefore I changed the layout (plot.update_layout(coloraxis_colorscale=...), but it does not work in 3D (while it does in 2D for example). I would like a specific feature to customize the colormaps in 3D plots.

**Comment by zerothi** [comment]
Thanks for the question, I must admit, I am no expert on this field, I guess it also depends on the backend @pfebrer you have inputs here?

**Comment by pfebrer** [comment]
Yes, I didn't answer because Sara is from our group at ICN2, I told her to submit the issue so that I would remember :)

**Comment by pfebrer** [comment]
>  I guess it also depends on the backend

We don't do 3D plots in matplotlib, so this would need to be implemented in `plotly`, `blender` and `py3dmol` (if it is possible for all of them :sweat_smile: )
