### ISSUE TITLE
sisl release policy

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#794]
I was just wondering about your thoughts regarding `sisl` version releases. What constitutes a sufficient advancement for a new release?

The latest one [`v0.14.3`](https://github.com/zerothi/sisl/releases/tag/v0.14.3) is from November 2023 and lots of changes have been introduced since then. Would it make sense to have some more frequent minor/micro releases?

**Comment by zerothi** [comment]
I have planned to make a release very soon! Indeed lots has happened... However, now since numpy 2.0.0 has come out, I think this needs to be revised before we can actually make the release. Otherwise we should release, and stick people with old numpy releases, I guess this could work, temporarily.

**Comment by tfrederiksen** [comment]
Wouldn't it make sense to have a minor release _before_ stepping to numpy 2.0.0?

**Comment by zerothi** [comment]
I will do a 0.15, no minor release should be done for all the things that has happened. ;)

**Comment by zerothi** [comment]
I really would like a speedy release, but the current cibuildwheel just fails, so this requires quite a bit of work.

I'll have to look at this when time allows...

**Comment by tfrederiksen** [comment]
Sure, I understand, no stress! I was just curious about your thoughts and plans.

**Comment by zerothi** [comment]
It seems everything has been solved, will release pretty soon ;)
