### ISSUE TITLE
lorbit10 files not tested?

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#811]
**Describe the issue**

Once https://github.com/zerothi/sisl-files/issues/14 has been implemented, we should revise the `lorbit10` tests for vasp.

They are there, but currently not used.

@tfrederiksen what was your intention with these tests?

**Comment by tfrederiksen** [comment]
I wanted to implement also reading the $spd$- and site-resolved data from the extended DOSCAR written with the `LORBIT 10` flag.

**Comment by zerothi** [comment]
Ok, so this is something to come? Should I add them? Or do you think you'll be changing inputs more?

**Comment by zerothi** [comment]
In the restructuring, I will delete these for now. So no rush! ;)

**Comment by zerothi** [comment]
I'll close then! Thanks!
