### ISSUE TITLE
Difference between Hamiltonian from .HSX and .TSHS files

### ISSUE THREAD

**Issue by AsymmetryChou** [zerothi/sisl#826]
**Describe the issue**

Hi developer!

When read Hamiltonian after TranSIESTA calculation, I'am confused about some difference among Hamiltonian elements read by different methods. I hope you give me some help! 

**Background**: a DFT-NEGF SCF in 1D Au atom chain system( include 12 atoms in Scattering Region L-C-R , 4 in L, 4 in C, 4 in R), and analyze the results with sisl. I'm not sure whether it is sisl's bug or just due to my misunderstanding about TranSIESTA.

1.  **H from .HSX and .TSHS**:  For isolated electrode calculation ( 4 Au atom as one Principal Layer ), I read H from .HSX and .TSHS with **sisl.io.siesta.hsxSileSiesta** and **sisl.Hamiltonian.read** respectively. I find that the two H is different. It seems that there is an onsite shift between them. And I test and found that H_tshs = H_hsx - Ef * S， that is to say, Fermi-Level is taken as the energy zero-point in H_tshs. I don't know whether it's just a coincide or general ? This operation( take Ef as zero-point) is taken by sisl as postprocess or .TSHS itself is saved with Ef=0 ？

After that,  I found another interesting thing! 

2.  **H in electrode part inside Scattering-Region is different from that in isolated electrode calculation**: With sisl, I compare H from isolated electrode calculation (4 Au atom) and that corresponding to L part in Scattering Region. Both read by **sisl.Hamiltonian.read**.  However H in each atom of  L part in Scattering Region seems not to be identical, and  the H is different from that in isolated electrode calculation. I guess that Transiesta only take H from isolated electrode calculation to substitute the H in L/R part **as a start point** in DFT-NEGF SCF. Otherwise my way using sisl have some problem. Here is the code:
```python

lead_HS_file = 'lead.TSHS'
lead_ts_H = sisl.Hamiltonian.read(lead_HS_file)
lead_ts_S = sisl.Overlap.read(lead_HS_file)

tran_HS_file = 'tran.TSHS'
tran_ts_H = sisl.Hamiltonian.read(tran_HS_file)
tran_ts_S = sisl.Overlap.read(tran_HS_file)

lead_ts_H = lead_ts_H.tocsr()
tran_ts_H = tran_ts_H.tocsr()

lead_ts_S = lead_ts_S.tocsr()
tran_ts_S = tran_ts_S.tocsr()

diff_H = lead_ts_H[:18,:18].toarray()-tran_ts_H[:18,:18].toarray() - diff_Ef * tran_ts_S[:18,:18].toarray()
diff_S = lead_ts_S[:54,:54].toarray()-tran_ts_S[:54,:54].toarray()

plt.matshow(diff_H,cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('diff lead_H - tranH')
plt.show()

plt.matshow(diff_S,cmap='bwr',vmin=-1e-3,vmax=1e-3)
plt.title('diff lead_S - tranS')
plt.show()

```
            

I'm sorry that my question might be too long and tedious. Thank you very much !

**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
[sys]
3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0]
[sisl]
version                       0.15.0
path                          /opt/mamba/envs/base/lib/python3.9/site-packages/sisl
CC                            /usr/bin/gcc
CFLAGS                        -O3 -DNDEBUG
C version                     11.3.0
FC                            /usr/bin/gfortran
FFLAGS                        -O3 -DNDEBUG -O3
FC version                    11.3.0
cython build version          Cython version 3.0.11
numpy build version           2.0.2
[cmake_args]
CMAKE_BUILD_TYPE              Release
WITH_FORTRAN                  ON
WITH_COVERAGE                 OFF
WITH_LINE_DIRECTIVES          OFF
WITH_ANNOTATE                 OFF
WITH_GDB                      OFF
NO_COMPILATION                
[runtime modules]
numpy                         1.24.4
scipy                         1.9.1
xarray                        2024.7.0
netCDF4                       1.7.1.post2
pandas                        2.2.2
matplotlib                    3.9.2
dill                          not found
                              No module named 'dill'
pathos                        not found
                              No module named 'pathos'
skimage                       not found
                              No module named 'skimage'
plotly                        not found
                              No module named 'plotly'
ase                           3.23.0
pymatgen                      not found
                              No module named 'pymatgen'
[env]
pip                           numpy==1.24.4 scipy==1.9.1 xarray==2024.7.0 netCDF4==1.7.1.post2 pandas==2.2.2 matplotlib==3.9.2 ase==3.23.0
conda                         numpy==1.24.4 scipy==1.9.1 xarray==2024.7.0 netCDF4==1.7.1.post2 pandas==2.2.2 matplotlib==3.9.2 ase==3.23.0
```

**Comment by zerothi** [comment]
>     1. **H from .HSX and .TSHS**:  For isolated electrode calculation ( 4 Au atom as one Principal Layer ), I read H from .HSX and .TSHS with **sisl.io.siesta.hsxSileSiesta** and **sisl.Hamiltonian.read** respectively. I find that the two H is different. It seems that there is an onsite shift between them. And I test and found that H_tshs = H_hsx - Ef * S， that is to say, Fermi-Level is taken as the energy zero-point in H_tshs. I don't know whether it's just a coincide or general ? This operation( take Ef as zero-point) is taken by sisl as postprocess or .TSHS itself is saved with Ef=0 ？

That is the intended behaviour, but I can see why the confusion is happening.
I will make some checks for this.

The reason is that the `HSX` file format does not contain the Fermi-level, hence it can't shift the electronic structure to something.
So when you read directly from the `HSX` sile, you don't shift the electronic structure.

Generally I would recommend one to read these quantities using the `fdf` file.
So something like this would give you the most generic, and consistent behaviour:

```python
fdf = si.get_sile("RUN.fdf")

HSX = fdf.read_hamiltonian(order="HSX")
# or
HSX = si.Hamiltonian.read(fdf, order="HSX")
```
But, even better is just to let sisl decide on the best order `H = fdf.read_hamiltonian()`.

> 
>     2. **H in electrode part inside Scattering-Region is different from that in isolated electrode calculation**: With sisl, I compare H from isolated electrode calculation (4 Au atom) and that corresponding to L part in Scattering Region. Both read by **sisl.Hamiltonian.read**.  However H in each atom of  L part in Scattering Region seems not to be identical, and  the H is different from that in isolated electrode calculation. I guess that Transiesta only take H from isolated electrode calculation to substitute the H in L/R part **as a start point** in DFT-NEGF SCF. Otherwise my way using sisl have some problem. Here is the code:

This is not suprising, the electrode region of the device calculation is *not* the same as the electrode region.
You typically want them to be roughly the same, as that indicates that the defect region is sufficiently screened (so a GOOD check you did here!!!!).  
However, it is not formally correct.

When you do `tocsr` you are folding to the $\Gamma$-point, which means that the couplings in the electrode region are folded into the electrode Hamiltonian.

In your case, when you want to compare these things, you should do:
```python
Hdev = si.Hamiltonian.read(<DEVICE>)
Helec = si.Hamiltonian.read(<ELEC>)

Hdev_L = Hdev.sub(range(4))

# These atoms have no couplings along the semi-infinite direction.
# Hence we need to explicitly remove the same couplings from the electrode Hamilotian
# Note, that by doing this we *destroy* the Hamiltonian, you can't use it for band-structure, DOS etc.
Helec.set_nsc(c=1)
# the above will remove all couplings along the 3rd lattice vector.
dH = Hdev_L - Helec
```
now you should be able to compare `dH`.



As for your code, I would highly recommend you to do atomic `sub` on the Hamiltonian.

For instance:
```python
H = si.Hamiltonian.read(...)

Hleft = H.sub(range(4))
```
After this, `Hleft` will be a Hamiltonian matrix that can be used like any other Hamiltonian object.


Hope this helps.

**Comment by zerothi** [comment]
I have commited a change 3a4f50eb3d7f2a73e30316eb6e7747e13169cf6d which now throws a warning:
```
warn:0: MissingFermiLevelWarning: silicon.HSX does not contain Ef, electronic structure not shifted to Fermi level.
```
It will also do this for `fdf` files, in case the `fermi-level cannot be read.

**Comment by AsymmetryChou** [comment]
Thank you very much for your detailed response!!!!  I would try that in the newest version sisl !

However,  in  Question2 I'm curious about your statement "You typically want them to be roughly the same, as that indicates that the defect region is sufficiently screened.However, it is not formally correct."  Actually I read the original TranSIESTA paper() again just now (Brandbyge, M., et al. (2002). "Density-functional method for nonequilibrium electron transport." Physical Review B 65(16): 165401.) and get the Hamiltonian in Scattering Region.
![image](https://github.com/user-attachments/assets/d9b45f41-c9f0-44ab-ae9d-b598e5519c36)

So personally I guess that: in the first step of TranSIESTA calculation, the code set $H_L$ and $H_R$ as bulk value( from isolated electrode SIESTA calculation), then the whole Hamiltonian is updated in DFT-NEGF SCF, therefore $H_L$ and $H_R$ would diff from bulk value. And  sisl would only read out the final converged Scattering Region Hamiltonian.  

I'm not sure that my understanding is correct, but it seems to be reasonally :)

**Comment by AsymmetryChou** [comment]
OK! Thank you very much!!! I would try the screening test in my system.

Btw, before that, still in the  12 Au atom chain,  there is something strange when I compare the Hamiltonain from isolated electrode calculation and  that from electrode part of Scattering Region(results from TranSIESTA). 
They are different. The code and  results are shown in  the bottom and sorry  I don't know the reason.  As you say, 

> Once TranSiesta starts, it doesn't touch the electrode regions of the device, it directly inserts 
HL  from the electrode calculations

the electrode part H of Scattering Region should be same as that from  isolated electrode calculation, at most differ by a 
 constant $\Delta E_F \cdot S$.  So this difference might be a little strange.   Maybe I misunderstanding your statement?


Personally, inspired by the obtained results, I guess the whole story maybe like this:
1. **Initial SIESTA calculation**:   obtain a good initial guess for DM and find out the Fermi-Level
2.  **Formal TranSIESTA calculation**:  obtain $H_L$ and $H_R$ from isolated electrode calculation, insert them in the whole Hamiltonian in respective position, and begein DFT-NEGF SCF. In the SCF, the whole Hamiltonian corresponding to Scattering Region would all be updated. Therefore, finally in the converged Hamiltonian(.TSHS file) $H_L$ and $H_R$ may differ slight from that in isolated electrode calculation.

Thank you!


```python
import sisl
import matplotlib.pyplot as plt
import   numpy as np

lead_HS_file = 'lead.TSHS'
lead_ts_H = sisl.Hamiltonian.read(lead_HS_file)
lead_ts_S = sisl.Overlap.read(lead_HS_file)

tran_HS_file = 'tran.TSHS'
tran_ts_H = sisl.Hamiltonian.read(tran_HS_file)
tran_ts_S = sisl.Overlap.read(tran_HS_file)

#only care about electrode part(4 Au atom)  
tran_ts_leadpart_H = tran_ts_H.sub(range(4))
tran_ts_leadpart_S = tran_ts_S.sub(range(4))

#each Au atom with 9 orbitals, therefore 36 orbs totally
lead_H_value = np.zeros((36,36))
lead_S_value = np.zeros((36,36))
tran_leadpart_H = np.zeros((36,36))
tran_leadpart_S = np.zeros((36,36))
for i in range(36):
    for j in range(36):
        lead_H_value[i,j] = lead_ts_H[i,j,0]
        tran_leadpart_H[i,j] = tran_ts_leadpart_H[i,j,0]
        lead_S_value[i,j] = lead_ts_S[i,j,0]
        tran_leadpart_S[i,j] = tran_ts_leadpart_S[i,j,0]
        
plt.matshow(lead_H_value[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead H')
plt.show()

plt.matshow(tran_leadpart_H[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('tran_leadpart_H')
plt.show()

plt.matshow(lead_S_value[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead S')
plt.show()
```
![image](https://github.com/user-attachments/assets/8527fc47-a8a4-4ee1-afb2-6b0fb28af982)
![image](https://github.com/user-attachments/assets/5cd0c608-0246-4c90-b5f4-7aa1c1316697)
![image](https://github.com/user-attachments/assets/db2cc1e6-6314-4369-8cee-0f870a261fca)

**Comment by zerothi** [comment]
When comparing these systems, it is also important to look at SCF details, for instance `MeshCutoff`, k-point samplings etc.

Also, these comparisons should be done at $V=0$.

Your code could be reduced to this:
```
import sisl
import matplotlib.pyplot as plt
import   numpy as np

# these will automatically shift to Ef=0, so they should always have the same Ef.
lead_HS_file = 'lead.TSHS'
lead_H = sisl.Hamiltonian.read(lead_HS_file)

tran_HS_file = 'tran.TSHS'
tran_H = sisl.Hamiltonian.read(tran_HS_file)

#only care about electrode part(4 Au atom)  
tran_left_H = tran_H.sub(range(4))

#each Au atom with 9 orbitals, therefore 36 orbs totally
lead_H_value = np.zeros((36,36))
lead_S_value = np.zeros((36,36))
tran_leadpart_H = np.zeros((36,36))
tran_leadpart_S = np.zeros((36,36))
for i in range(36):
    for j in range(36):
        lead_H_value[i,j] = lead_H[i,j,0]
        tran_leadpart_H[i,j] = tran_left_H[i,j,0]
        lead_S_value[i,j] = lead_H[i,j,-1]
        tran_leadpart_S[i,j] = tran_left_H[i,j,-1]

plt.matshow(lead_H_value[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead H')
plt.show()

plt.matshow(tran_leadpart_H[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('tran_leadpart_H')
plt.show()

plt.matshow(lead_S_value[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead S')
plt.show()
```
The Hamiltonian also stores the overlap.


The fact that your `S` matrix is different tells me that the two calculations are not fully commensurate. It could be a MeshCutoff thing, or basis set difference. S is not dependent on the SCF steps, it is the same for every atomic configuration, so you can just do electrode and siesta calculation and check S. S is calculated on an internal grid related to the basis set, so it seems to me that you have done something different in the two calculations?

**Comment by AsymmetryChou** [comment]
Sorry maybe I don't paste above the Overlap's difference between electrode calculation and electrode part in Scattering Region.
The TranSIESTA calculation is done in $V=0$. Here is the updated code and comparion between two Overlap. The Overlap matrixs are same.  And I check the MeshCutoff,  both are same as well.

It seems that something else is wrong?

```python
import sisl
import matplotlib.pyplot as plt
import   numpy as np

# these will automatically shift to Ef=0, so they should always have the same Ef.
lead_HS_file = '/share/Au_organic_mol/Au_chain_test/TS/chain/lead.TSHS'
lead_H = sisl.Hamiltonian.read(lead_HS_file)

tran_HS_file = '/share/Au_organic_mol/Au_chain_test/TS/chain/tran.TSHS'
tran_H = sisl.Hamiltonian.read(tran_HS_file)

#only care about electrode part(4 Au atom)  
tran_left_H = tran_H.sub(range(4))

#each Au atom with 9 orbitals, therefore 36 orbs totally
lead_H_value = np.zeros((36,36))
lead_S_value = np.zeros((36,36))
tran_leadpart_H = np.zeros((36,36))
tran_leadpart_S = np.zeros((36,36))
for i in range(36):
    for j in range(36):
        lead_H_value[i,j] = lead_H[i,j,0]
        tran_leadpart_H[i,j] = tran_left_H[i,j,0]
        lead_S_value[i,j] = lead_H[i,j,-1]
        tran_leadpart_S[i,j] = tran_left_H[i,j,-1]

plt.matshow(lead_H_value[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead H')
plt.show()

plt.matshow(tran_leadpart_H[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('tran_leadpart_H')
plt.show()

plt.matshow(lead_S_value[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead S')
plt.show()

plt.matshow(lead_S_value[:18,:18]-tran_leadpart_S[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
plt.title('lead S - tran_leadpart_S')
plt.show()

```
![image](https://github.com/user-attachments/assets/fad4a37d-d4e1-45e1-9d80-5c742907e895)
![image](https://github.com/user-attachments/assets/d50c1d73-0863-4e4c-a8fc-37f546abf01d)
![image](https://github.com/user-attachments/assets/69adb66a-9cef-485b-8898-a25f62b9c661)
![image](https://github.com/user-attachments/assets/bf99d3cc-6993-46fc-aa2d-3ea33dbad4bb)

**Comment by zerothi** [comment]
What about simulation parameters?

**Comment by AsymmetryChou** [comment]
OK. I list the two input fdf for electrode calculation and TranSIESTA calculation.
The two calcualtion use the same Au.psf.
Thank you very much !

1. Input fdf for electrode calculation:
```python
SystemName          lead
SystemLabel         lead

%block PAO.Basis                 # Define Basis set
Au     3     0.025                  # Species label, number of l-shells
 n=6   0   1    E  99.0 3.76
   6.520
   1.000
 n=6   1   1    E  54.3 3.96
   6.90
   1.000
 n=5   2   1    E  54.3 4.11                       # n, l, Nzeta
   6.180
   1.000 
%endblock PAO.Basis

%block PS.lmax
 Au      3
%endblock PS.lmax

# real space mesh grid
MeshCutoff                   250.0 Ry

#kgrid_cutoff          0.00      Bohr   #Default=BZk,0=Gamma
%block kgrid_Monkhorst_Pack
     1     0     0          0.0
     0     1    0          0.0
     0     0    20          0.0
%endblock kgrid_Monkhorst_Pack

 
xc.functional           GGA           # Exchange-correlation functional                            
xc.authors              PBE              # Exchange-correlation version 
 
# Convergence of SCF 
MaxSCFIterations        1000
DM.MixingWeight         0.01
DM.NumberPulay          6
DM.Tolerance            1.0E-9
ElectronicTemperature   300 K
DM.UseSaveDM            T
 
# Type of solver
SolutionMethod          diagon
MD.TypeOfRun            CG           # Type of dynamics:                                         
MD.NumCGsteps           0         # Number of CG steps for
MD.MaxCGDispl           0.20 bohr     # Maximum atomic displacement
MD.MaxForceTol          0.03 eV/Ang  # Tolerance in the maximum
MD.MaxStressTol         0.1 Gpa
MD.UseSaveXV            T
 
WriteForces             T
WriteCoorStep           T
WriteMDhistory          T
SaveHS                  T
SaveRHO                 T
WriteMullikenPop        1

LatticeConstant 1.0 Ang
%block LatticeVectors
 10.0000000 0.00000000 0.00000000
 0.00000000 10.0000000 0.00000000
 0.00000000 0.00000000  10.800000
%endblock LatticeVectors

NumberOfAtoms  4
AtomicCoordinatesFormat Ang
%block AtomicCoordinatesAndAtomicSpecies
  0.00000000  0.00000000  0.00000000 1 #   1: Au
  0.00000000  0.00000000  2.70000000 1 #   2: Au
  0.00000000  0.00000000  5.40000000 1 #   3: Au
  0.00000000  0.00000000  8.10000000 1 #   4: Au
%endblock AtomicCoordinatesAndAtomicSpecies

NumberOfSpecies 1
%block ChemicalSpeciesLabel
 1 79 Au
%endblock ChemicalSpeciesLabel

```
2. Input fdf for TranSIESTA calculation
``` python
SystemName                   tran           # Descriptive name of the system
SystemLabel                  tran           # Short name for naming files


# ps
%block Ps.lmax
 Au    3 
%endblock Ps.lmax

%block PAO.Basis                 # Define Basis set
Au     3     0.025                  # Species label, number of l-shells
 n=6   0   1    E  99.0 3.76
   6.520
   1.000
 n=6   1   1    E  54.3 3.96
   6.90
   1.000
 n=5   2   1    E  54.3 4.11                       # n, l, Nzeta
   6.180
   1.000 
%endblock PAO.Basis


# real space mesh grid
MeshCutoff                   250.0 Ry

# reciprocal space
%block kgrid_Monkhorst_Pack
  1   0    0    0.0
  0   1    0    0.0
  0   0    1    0.0
%endblock kgrid_Monkhorst_Pack

 
xc.functional           GGA           # Exchange-correlation functional                            
xc.authors              PBE              # Exchange-correlation version 
 
# Convergence of SCF 
MaxSCFIterations        1000
DM.MixingWeight         0.01
DM.NumberPulay          6
DM.Tolerance            1.0E-9
ElectronicTemperature   300 K
DM.UseSaveDM            T
 
# Type of solver
SolutionMethod          transiesta
MD.TypeOfRun            CG           # Type of dynamics:                                         
MD.NumCGsteps           0         # Number of CG steps for
MD.MaxCGDispl           0.20 bohr     # Maximum atomic displacement
MD.MaxForceTol          0.03 eV/Ang  # Tolerance in the maximum
MD.MaxStressTol         0.1 Gpa
MD.UseSaveXV            T
Force
 
WriteForces             T
WriteCoorStep           T
WriteMDhistory          T
SaveHS                  T
SaveRHO                 T
WriteMullikenPop        1
ForceAuxCell            T

TS.Voltage      0.000000000     Ry                           
 
%block TS.ChemPots
  Left
  Right
%endblock TS.ChemPots
 
%block TS.ChemPot.Left
  mu V/2
  contour.eq
    begin
      c-Left
      t-Left
    end
%endblock TS.ChemPot.Left
%block TS.ChemPot.Right
  mu -V/2
  contour.eq
    begin
      c-Right
      t-Right
    end
%endblock TS.ChemPot.Right
 
TS.Elecs.Bulk true
TS.Elecs.DM.Update none
#TS.Elecs.GF.ReUse false

%block TS.Elecs
  Left
  Right
%endblock TS.Elecs
 
%block TS.Elec.Left
  TSHS lead.TSHS
  chem-pot Left
  semi-inf-dir -a3
  elec-pos begin 1
  bloch 1 1 1
%endblock TS.Elec.Left
 
%block TS.Elec.Right
  TSHS lead.TSHS
  chem-pot Right
  semi-inf-dir +a3
  elec-pos end -1
  bloch 1 1 1
%endblock TS.Elec.Right
 
TS.Contours.Eq.Pole.N 6
%block TS.Contour.c-Left
  part circle
   from   -3.00000 Ry + V/2 to -10. kT + V/2
    points 30
     method g-legendre
%endblock TS.Contour.c-Left
%block TS.Contour.t-Left
  part tail
   from prev to inf
    points 10
     method g-fermi
%endblock TS.Contour.t-Left
%block TS.Contour.c-Right
  part circle
   from   -3.00000 Ry - V/2 to -10. kT - V/2
    points 30
     method g-legendre
%endblock TS.Contour.c-Right
%block TS.Contour.t-Right
  part tail
   from prev to inf
    points 10
     method g-fermi
%endblock TS.Contour.t-Right
 
TS.Contours.nEq.Eta    0.0000010000 Ry                                
%block TS.Contours.Bias.Window
  neq
%endblock TS.Contours.Bias.Window
%block TS.Contour.Bias.Window.neq
  part line
   from -|V|/2 to |V|/2
    delta 0.01 eV
     method simpson-mix
%endblock TS.Contour.Bias.Window.neq
 

LatticeConstant 1.0 Ang
%block LatticeVectors
 10.0000000 0.00000000 0.00000000
 0.00000000 10.0000000 0.00000000
 0.00000000 0.00000000  32.400000
%endblock LatticeVectors

NumberOfAtoms  12
AtomicCoordinatesFormat Ang
%block AtomicCoordinatesAndAtomicSpecies
  0.00000000  0.00000000  0.00000000 1 #   1: Au
  0.00000000  0.00000000  2.70000000 1 #   2: Au
  0.00000000  0.00000000  5.40000000 1 #   3: Au
  0.00000000  0.00000000  8.10000000 1 #   4: Au
  0.00000000  0.00000000  10.80000000 1 #   5: Au
  0.00000000  0.00000000  13.50000000 1 #   6: Au
  0.00000000  0.00000000  16.20000000 1 #   7: Au
  0.00000000  0.00000000  18.90000000 1 #   8: Au
  0.00000000  0.00000000  21.60000000 1 #   9: Au
  0.00000000  0.00000000  24.30000000 1 #   10: Au
  0.00000000  0.00000000  27.00000000 1 #   11: Au
  0.00000000  0.00000000  29.70000000 1 #   12: Au
%endblock AtomicCoordinatesAndAtomicSpecies

NumberOfSpecies 1
%block ChemicalSpeciesLabel
 1 79 Au
%endblock ChemicalSpeciesLabel

```

**Comment by zerothi** [comment]
Try and do your device calculation with 3 k-points along z!

**Comment by zerothi** [comment]
And also, delete this line: `TS.Elecs.DM.Update none`

**Comment by zerothi** [comment]
First thing, do this with a siesta calculation (not `SolutionMethod transiesta`).

**Comment by AsymmetryChou** [comment]
OK. I set 3 k-points along z in tran.fdf
```python
# reciprocal space
%block kgrid_Monkhorst_Pack
  1   0    0    0.0
  0   1    0    0.0
  0   0    3    0.0
%endblock kgrid_Monkhorst_Pack
```

and run. The results of the above code are in the bottom. The results still show that the H are different but S are same.

![image](https://github.com/user-attachments/assets/f7df11f8-3658-4fc8-ad4d-2174fa13bd31)
![image](https://github.com/user-attachments/assets/4eb4332b-734c-4e03-a05d-13d0d81733dc)
![image](https://github.com/user-attachments/assets/c00ef9ca-00ae-4dce-9904-a19a8e0125da)
![image](https://github.com/user-attachments/assets/22eab981-d858-4a97-982f-caa7efa7eee0)

**Comment by zerothi** [comment]
You have to plot the difference, plotting absolute values is hard to quantify.

And, as I said, the electronic structure are not commensurate. Try to make 2 fully commensurate calculations, and compare these. That should be your baseline.

**Comment by AsymmetryChou** [comment]
Hi developer!

Follow your advice, I make a new analysis here. The results( see buttom) show that Overlap Matrix are **strictly same** between isolated electrode calculation and electrode part in device from TranSIESTA calculation. However, the Hamiltonian would **slightly differ** (in sub-mev order).

To make my input parameters definitly correct, I use your graphene example in https://github.com/zerothi/ts-tbt-sisl-tutorial/tree/main/TS_01.  And maybe there is **a tiny error** that  PAO.EnergyShift is set as **0.01 Ry** in RUN_ELEC.fdf ,but in RUN.fdf, PAO.EnergyShift use the default value (**0.02 Ry** in SIESTA v4.1.5).  Therefore the generated orbitals would be different.   After setting the same parameters in both fdf files, the results are analyzed.

As you can see, lead_H and tran_leadpart_H is nearly same (Having consider the difference created by different Fermi level) while the overlap are strictly identical. So is it reasonable?  As you say, once TranSIESTA starts, it takes the Hamiltonian in  electrode part of device  from isolated electrode calculation and fixs them forever till DFT-NEGF SCF is over. However, from what we get in this graphene calculation, it seems that the electrode part Hamiltonian would be updated in DFT-NEGF SCF, and due to the existence of screening layer, the degree of updating would be very small, resulting in the nearly same Hamiltonian compared with the isolated electrode calculation.

I don't know the results here meet your expectation or not :)

THANK YOU!

Here is the code and results:
```python
import sisl
import matplotlib.pyplot as plt
import   numpy as np

# these will automatically shift to Ef=0, so they should always have the same Ef.
lead_ts_H = sisl.Hamiltonian.read('/share/Au_organic_mol/Au_chain_test/TS/graphene/ELEC.TSHS')
lead_ts_S = sisl.Overlap.read('/share/Au_organic_mol/Au_chain_test/TS/graphene/ELEC.TSHS')

tran_ts_H = sisl.Hamiltonian.read('/share/Au_organic_mol/Au_chain_test/TS/graphene/siesta.TSHS')
tran_ts_S = sisl.Overlap.read('/share/Au_organic_mol/Au_chain_test/TS/graphene/siesta.TSHS')

#only care about electrode part(4 C atom)  
tran_left_H = tran_ts_H.sub(range(4))

#each C atom with 9 orbitals, therefore 36 orbs totally
lead_H_value = np.zeros((36,36))
lead_S_value = np.zeros((36,36))
tran_leadpart_H = np.zeros((36,36))
tran_leadpart_S = np.zeros((36,36))
for i in range(36):
    for j in range(36):
        lead_H_value[i,j] = lead_ts_H[i,j,0]
        tran_leadpart_H[i,j] = tran_left_H[i,j,0]
        lead_S_value[i,j] = lead_ts_H[i,j,-1]
        tran_leadpart_S[i,j] = tran_left_H[i,j,-1]

# Ef of lead and tran read from output file
lead_H_Ef = -6.365694
tran_H_Ef = -6.365187

diff_Ef = lead_H_Ef - tran_H_Ef

fig, axs = plt.subplots(1,5,figsize=(20,4))

axs[0].matshow(lead_H_value[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
axs[0].set_title('lead H')
fig.colorbar(axs[0].matshow(lead_H_value[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4))   

axs[1].matshow(tran_leadpart_H[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4)
axs[1].set_title('tran_leadpart_H')
fig.colorbar(axs[1].matshow(tran_leadpart_H[:9,:9],cmap='bwr',vmin=-1e-4,vmax=1e-4))

diff_H = lead_H_value[:9,:9]-tran_leadpart_H[:9,:9] + diff_Ef * lead_S_value[:9,:9]
print('diff_H:',np.diag(diff_H))
axs[2].matshow(diff_H,cmap='bwr',vmin=-1e-3,vmax=1e-3)
axs[2].set_title('lead H - tran_leadpart_H')
fig.colorbar(axs[2].matshow(diff_H,cmap='bwr',vmin=-1e-3,vmax=1e-3))

axs[3].matshow(lead_S_value[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
axs[3].set_title('lead S')
fig.colorbar(axs[3].matshow(lead_S_value[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4))

axs[4].matshow(lead_S_value[:18,:18]-tran_leadpart_S[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4)
axs[4].set_title('lead S - tran_leadpart_S')
fig.colorbar(axs[4].matshow(lead_S_value[:18,:18]-tran_leadpart_S[:18,:18],cmap='bwr',vmin=-1e-4,vmax=1e-4))
plt.tight_layout()
plt.show()

```
![image](https://github.com/user-attachments/assets/ac8415d0-1799-4f15-b25c-abe6a32f3185)

**Comment by zerothi** [comment]
1. When reading from the TSHS files, the Hamiltonian gets shifted to Ef = 0. So you shouldn't do anything with respect to the fermi levels.
2. It is hard to say anything quantitatively, it is your feeling for the system that tells if it is good enough or not. Is the differences so small that potential differences are negligeble... That will have to be your responsibility to understand. It might be fine for this, but other cases (say spin-orbit) these differences might not be enough. I don't know.

Thanks for the heads up on the tutorials, I'll fix it!

**Comment by AsymmetryChou** [comment]
OK, I see!  

Actually this is literally a tiny difference bewtween the two Hamiltonian. So my understanding for TranSIESTA is correct, right? That is, the Hamiltonian might have some change in TranSIESTA DFT-NEGF SCF,  and with the help of enough screening effect, the change is negligible, and the H in electrode part of device is very very similar to that in isolated electrode calculation.

**Comment by zerothi** [comment]
Sounds right.
