### ISSUE TITLE
Slightly wrong energy written to TBTGF by sisl?

### ISSUE THREAD

**Issue by AleksBL** [zerothi/sisl#827]
When writing a custom tbtgf file using the write_header of "sisl.io.tbtgfSileTBtrans" the energies in read by TBtrans will differ by x1.00000785 from the input value given inside python.

The calculation of the greens function is going on in the python code below:
![image](https://github.com/user-attachments/assets/df530587-6317-4797-a6e3-11f1d3c4c2d4)
There doesnt seem to be any descrepancy when iterating over the f:
![image](https://github.com/user-attachments/assets/36390b28-0854-490a-87a1-ea545eeac5f7)
The fail happens in TBtrans, in the output:
![image](https://github.com/user-attachments/assets/6ad6c462-80cd-490c-ab86-bf7efa6ddd8a)

sisl v. 0.15
tbtrans from siesta-rel-5.0,  but also happens with tbtrans from siesta v.4.1.5

The script below shows that it seems to be consistent across python, but something it seems to be some intermediate step

```python
import sisl
import numpy as np
import tqdm

g      = sisl.geom.graphene()
H_elec = sisl.Hamiltonian(g)
H_elec.construct([[0.1,1.5], [0.0, -2.7]])
gamma = sisl.MonkhorstPack(H_elec, [1] * 3)
E    = np.linspace(-1,1)
eta  = 0.001
mu   = None

with sisl.io.tbtgfSileTBtrans('Test.TBTGF') as f:
    val = E + 1j * eta
    # print(val[0])
    # print(val.dtype)
    if mu is not None:f.write_header(gamma, E + 1j * eta, mu = mu)
    else:             f.write_header(gamma, E + 1j * eta)
    
    for ispin, new_k, k, e in tqdm.tqdm(f):
        if new_k:
            f.write_hamiltonian(H_elec.Hk(format='array', dtype=np.complex128),
                                H_elec.Sk(format='array', dtype=np.complex128))
        
        # else:          SeHSE = SRSSE.self_energy(e + 1j*eta, bulk=True, coupling=True)
        rand_mat  = np.random.random((H_elec.no, H_elec.no))
        rand_mat += rand_mat.T
        
        f.write_self_energy(rand_mat)

gf = sisl.get_sile('Test.TBTGF')
```

**Version details**
Run the below code and add to bug-report:
```python
import sisl._debug_info as sd
sd.print_debug_info()
```

**Comment by zerothi** [comment]
and how is the input file for tbtrans? Because that is where the real problem enters.

**Comment by AleksBL** [comment]
These are the first couple of energies in the file containing the custom energies (my_energies from the tbtrans manual i think)

-3.9999 0.01 1.0 eV
-3.933233333333333 0.01 1.0 eV
-3.8665666666666665 0.01 1.0 eV
-3.7998999999999996 0.01 1.0 eV
-3.733233333333333 0.01 1.0 eV
-3.6665666666666663 0.01 1.0 eV
-3.5999 0.01 1.0 eV
-3.533233333333333 0.01 1.0 eV
-3.4665666666666666 0.01 1.0 eV

The script im using for this used to work I think.

**Comment by zerothi** [comment]
how are you writing it??

**Comment by zerothi** [comment]
Share the code please.

**Comment by AleksBL** [comment]
I have added fmt='.12e' to the write_data function, and the contour.E file now has higher precision:
-3.999900000000e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.933233333333e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.866566666667e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.799900000000e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.733233333333e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.666566666667e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.599900000000e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.533233333333e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.466566666667e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.399900000000e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
-3.333233333333e+00+1.000000000000e-02j	0.000000000000e+00+0.000000000000e+00j
.....


Electrode E1 has no transfer matrix.
Assuming ../E1/E1.TBTGF contains H, S and E*S - H - \Sigma for calculating the correct self-energies and scattering matrices.
 E1 principal cell is perfect!
 Electrode Green's function file: '../E1/E1.TBTGF' already exist.
  Warning: contours differ by >   9.9999999999999995E-007
  ERROR  : contours differ by >   9.9999999999999991E-006
            TS E.real [eV]            TS E.imag [eV]           File E.real [eV]          File E.imag [eV]
  -0.39999000000000002E+01   0.10000000000000002E-01   -0.39998685797720466E+01   0.99999214474663038E-02
  -0.39332333333333334E+01   0.10000000000000002E-01   -0.39332024367889376E+01   0.99999214474663038E-02
  -0.38665666666666665E+01   0.10000000000000002E-01   -0.38665362938058294E+01   0.99999214474663038E-02
  -0.37999000000000001E+01   0.10000000000000002E-01   -0.37998701508227199E+01   0.99999214474663038E-02
  -0.37332333333333332E+01   0.10000000000000002E-01   -0.37332040078396123E+01   0.99999214474663038E-02
  -0.36665666666666663E+01   0.10000000000000002E-01   -0.36665378648565028E+01   0.99999214474663038E-02
  -0.35998999999999999E+01   0.10000000000000002E-01   -0.35998717218733947E+01   0.99999214474663038E-02
  -0.35332333333333330E+01   0.10000000000000002E-01   -0.35332055788902856E+01   0.99999214474663038E-02
  -0.34665666666666666E+01   0.10000000000000002E-01   -0.34665394359071775E+01   0.99999214474663038E-02
  -0.33998999999999997E+01   0.10000000000000002E-01   -0.33998732929240680E+01   0.99999214474663038E-02
  -0.33332333333333333E+01   0.10000000000000002E-01   -0.33332071499409599E+01   0.99999214474663038E-02



Maybe the old number used for converting between Rydberg and eV is still hanging around somewhere in the TBtrans code when loading custom self energies?

**Comment by zerothi** [comment]
ah, you are right, I thought I had fixed this, try and do `tbtGfSileSiesta(..., version="new")`
I'll fix this so that it is handled by an env.

**Comment by zerothi** [comment]
Thanks for raising the issue!
