### ISSUE TITLE
Change `tbt.Eindex` to only work for float

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#829]
**Describe the issue**
Users are confused about the `Eindex(0)` behaving different from `Eindex(0.)`.
Better to completely remove this ambiguity... Aren't users always using float for grabbing an energy index...?

This will likely break some scripts, but I think it is necessary for future-profing its use.

**Comment by ialcon** [comment]
So, if I get it right, what you are suggesting is that if you do something like `Eindex(1)` the code would crash?

If that is the case, I would suggest to, instead, homogenize both of them, so that `Eindex(1)` and `Eindex(0)`, etc, are equivalent to `Eindex(1.)`, `Eindex(0.)`... I doubt very much that anybody would be specifying `Eindex(1)` using **1** as an array index. On the contrary, I guess, the most generalized case would be to refer to **1 eV**, right?

**Comment by zerothi** [comment]
> So, if I get it right, what you are suggesting is that if you do something like `Eindex(1)` the code would crash?
No... The problem is that `Eindex(1)` was not the same as `Eindex(1.)`.


> If that is the case, I would suggest to, instead, homogenize both of them, so that `Eindex(1)` and `Eindex(0)`, etc, are equivalent to `Eindex(1.)`, `Eindex(0.)`... I doubt very much that anybody would be specifying `Eindex(1)` using **1** as an array index. On the contrary, I guess, the most generalized case would be to refer to **1 eV**, right?

Yes, this is exactly the point, perhaps I should just do it now, because it can really be understood as a bug...

**Comment by zerothi** [comment]
This is completed in f.f911fc94

**Comment by ialcon** [comment]
> > So, if I get it right, what you are suggesting is that if you do something like `Eindex(1)` the code would crash?
> > No... The problem is that `Eindex(1)` was not the same as `Eindex(1.)`.
> 
> > If that is the case, I would suggest to, instead, homogenize both of them, so that `Eindex(1)` and `Eindex(0)`, etc, are equivalent to `Eindex(1.)`, `Eindex(0.)`... I doubt very much that anybody would be specifying `Eindex(1)` using **1** as an array index. On the contrary, I guess, the most generalized case would be to refer to **1 eV**, right?
> 
> Yes, this is exactly the point, perhaps I should just do it now, because it can really be understood as a bug...

Completely agree... Well done!
