### ISSUE TITLE
tutorial 09: KeyError: Right

### ISSUE THREAD

**Issue by mbarbry** [zerothi/sisl#83]
Hi,

I'm new in sisl, tbtrans and transiesta. I'm following the tutorials from 
https://github.com/zerothi/ts-tbt-sisl-tutorial/

In the tutorial 9, everythings works fine until the end to get the current.

    I[i] = sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v)).current()

I get the following error,

    sisl/io/sile.pyc in _variables(n, name, tree)
        777                 g = g.groups[t]
        778         else:
    --> 779             g = g.groups[tree]
        780 
        781         return g.variables[name]

    KeyError: u'Right'

effectively, printing the dictionary `g`, I get,

    OrderedDict([(u'Left', <type 'netCDF4._netCDF4.Group'>
    group /Left:
        dimensions(sizes): 
        variables(dimensions): float64 mu(one), float64 kT(one), float32 Right.T(nkpt,ne)
        groups: 
    )])
    OrderedDict([(u'Left', <type 'netCDF4._netCDF4.Group'>
    group /Left:
        dimensions(sizes): 
        variables(dimensions): float64 mu(one), float64 kT(one), float32 Right.T(nkpt,ne)
        groups: 
    )])
    OrderedDict([(u'Left', <type 'netCDF4._netCDF4.Group'>
     group /Left:
        dimensions(sizes): 
        variables(dimensions): float64 mu(one), float64 kT(one), float32 Right.T(nkpt,ne)
        groups: 
     )])
     OrderedDict([(u'Left', <type 'netCDF4._netCDF4.Group'>
     group /Left:
         dimensions(sizes): 
         variables(dimensions): float64 mu(one), float64 kT(one), float32 Right.T(nkpt,ne)
         groups: 
     )])

the key `Right` is clearly missing. Do you have an idea of what I did wrong?

**Comment by zerothi** [comment]
Could you try and add this:
```python
print(sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v))._elec(0))
print(sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v))._elec(1))
```
and give me the output?

**Comment by mbarbry** [comment]
The prints seem to give the expected values

    print(sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v)).elecs)
    ['Left', 'Right']

    print(sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v))._elec(0))
    Left

    print(sisl.get_sile('TBT_{:.1f}/siesta.TBT.nc'.format(v))._elec(1))
    Right

But I still get the same error when calculating the current.

**Comment by zerothi** [comment]
Could you print `print(sisl.__version__)`

**Comment by zerothi** [comment]
Also do you have a full stacktrace of the error?

**Comment by zerothi** [comment]
Ah, yes, this is because the latest sisl version requires the coming 4.1-b4 which adds this information.
So nothing is wrong ;)

**Comment by zerothi** [comment]
I am gonna close this issue.
Thanks for reporting.

**Comment by mbarbry** [comment]
Works fine with the development version of Siesta, thanks!
