### ISSUE TITLE
Stress can not be read from a siesta out file: si.io.siesta.stdoutSileSiesta

### ISSUE THREAD

**Issue by mbrandbyge** [zerothi/sisl#832]
The "Voigt" reads ok, but the standard stress returns nothing.

**Comment by zerothi** [comment]
What did you try? What table of the stress wasn't read? There are some tests for these things, so I am wondering if you called it wrongly, or the output had other flags?

**Comment by mbrandbyge** [comment]
![image](https://github.com/user-attachments/assets/0d2847e9-c5e1-42b6-a22f-5b3deb7d9fd8)

**Comment by mbrandbyge** [comment]
Calling without key does not return anything either.

**Comment by zerothi** [comment]
It's because that MD simulations has the stress tensor duplicated. So you should add `read_stress(skip_final=False)` to force it to return the last one.

Perhaps the sile should figure out if this is an MD simulation, or not, then return it if nothing is valued

**Comment by mbrandbyge** [comment]
Ah, ok. In principle, it would be nice if there was a reader for out files for MD returning values for each step in the out.

**Comment by zerothi** [comment]
> Ah, ok. In principle, it would be nice if there was a reader for out files for MD returning values for each step in the out.

There already is:

```
stdout = sisl.get_sile(...)
stdout.read_stress[:10]()
```
will read the first 10 stresses.

**Comment by zerothi** [comment]
@mbrandbyge could you share the file? I am trying to streamline the process, and I think I have the solution, just need the output to test it on!
