### ISSUE TITLE
Incorrect changelog?

### ISSUE THREAD

**Issue by ahkole** [zerothi/sisl#852]
https://github.com/zerothi/sisl/blob/d9aacc0df8e5ab52cdcb533648cc014b53b2d54a/CHANGELOG.md?plain=1#L95

Hi @zerothi , I noticed that this was included in the list of additions of `v0.15.0`, but as far as I can see this version was released before the merge so it's probably not included there, right? I don't know if this was accidentally added here automatically because the milestone in the PR was still set to an incorrect version or something?

**Comment by zerothi** [comment]
Thanks for noticing this! I didn't, indeed  it should be moved up to the new section! I'll do that!
