### ISSUE TITLE
Cutoff radius from ion.xml files is ignored.

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#858]
When reading a basis from an `ion.xml` file, the cutoff radius is ignored and instead is computed with the `radial_minimize_range` function here:

https://github.com/zerothi/sisl/blob/6ef44002aa6b41118e93272fb08a081ad70a6d2a/src/sisl/_core/orbital.py#L340

Wouldn't it make more sense to use the cutoff that is specified in the file?

**Comment by zerothi** [comment]
Agreed, sounds like the way to go!

What you care for a PR, I would like to release a small release, I have some reading problems of charges with the new 5.2 release.

@nils-wittemeier FYI in terms of the school next week, I plan on doing a release soon (tonight/morrow) because of #856.

**Comment by nils-wittemeier** [comment]
That's great! The latest release would be available via pip, right?

**Comment by zerothi** [comment]
Yes!

**Comment by nils-wittemeier** [comment]
Perfect.
